import type { BestForDefinition } from "./types";

export const BEST_FOR = [
  { slug: "shirting", label: "Shirts" },
  { slug: "trousers", label: "Trousers" },
  { slug: "dresses", label: "Dresses" },
  { slug: "jackets", label: "Jackets" },
  { slug: "chore-jackets", label: "Chore jackets" },
  { slug: "bottoms", label: "Bottoms" },
  { slug: "knitwear", label: "Knitwear" },
  { slug: "resortwear", label: "Resortwear" },
  { slug: "soft-tailoring", label: "Soft tailoring" },
  { slug: "blouses", label: "Blouses" },
  { slug: "scarves", label: "Scarves" },
  { slug: "overlays", label: "Overlays" },
  { slug: "volume-sleeves", label: "Volume sleeves" },
  { slug: "ruffles", label: "Ruffles" },
  { slug: "occasionwear", label: "Occasionwear" },
  { slug: "full-skirts", label: "Full skirts" },
  { slug: "lightweight-outerwear", label: "Lightweight outerwear" },
  { slug: "slip-dresses", label: "Slip dresses" },
  { slug: "linings", label: "Linings" },
  { slug: "home-decor", label: "Home textiles / interiors" },
  { slug: "suiting", label: "Suiting" },
  { slug: "unstructured-jackets", label: "Unstructured jackets" },
  { slug: "layering-pieces", label: "Layering pieces" },
  { slug: "baselayers", label: "Baselayers" },
  { slug: "swimwear", label: "Swimwear" },
  { slug: "citywear", label: "Citywear" },
  { slug: "loungewear", label: "Loungewear" },
  { slug: "performance-apparel", label: "Activewear" },
  { slug: "coats", label: "Coats" },
  { slug: "unlined-coats", label: "Unlined coats" },
  { slug: "statement-knits", label: "Statement knits" },
  { slug: "workwear-trousers", label: "Workwear trousers" },
  { slug: "workwear-jackets", label: "Workwear jackets" },
  { slug: "interiors", label: "Interiors" },
  { slug: "city-outerwear", label: "City outerwear" },
  { slug: "outerwear", label: "Outerwear" },
  { slug: "garment-insulation", label: "Garment insulation" },
  { slug: "upholstery", label: "Upholstery" },
  { slug: "curtains", label: "Curtains" },
  { slug: "sheers", label: "Sheers" },
  { slug: "acoustic-drapes", label: "Acoustic drapes" },
  { slug: "bedding", label: "Bedding" },
  { slug: "rugs", label: "Rugs" },
  { slug: "contract-textiles", label: "Contract textiles" },
] as const satisfies readonly BestForDefinition[];

export type BestForSlug = (typeof BEST_FOR)[number]["slug"];

export const BEST_FOR_BY_SLUG = Object.fromEntries(
  BEST_FOR.map((application) => [application.slug, application]),
) as Record<BestForSlug, (typeof BEST_FOR)[number]>;
