import type { CatalogProduct } from "./types";

/**
 * Frontend-only expansion requested for the customer-facing catalog.
 *
 * These are material identities, not supplier listings. Commercial fields stay
 * absent until real backend inventory exists.
 */
export const EXPANDED_FABRICS = [
  {
    id: "fs-fabric-exp-001",
    slug: "silk-charmeuse",
    name: "Silk Charmeuse",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% silk"],
    measurements: [{ unit: "momme", min: 12, max: 19 }],
    construction: ["Satin weave"],
    characteristics: ["Fluid drape", "Lustrous face", "Soft matte reverse"],
    applications: ["slip-dresses", "blouses", "linings", "scarves"],
    source: "Frontend catalog expansion requested 2026-09-12; standard silk charmeuse specification",
  },
  {
    id: "fs-fabric-exp-002",
    slug: "silk-satin",
    name: "Silk Satin",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% silk"],
    measurements: [{ unit: "momme", min: 16, max: 22 }],
    construction: ["Satin weave"],
    characteristics: ["High silk sheen", "Smooth surface", "Fluid drape"],
    applications: ["occasionwear", "dresses", "linings"],
    source: "Frontend catalog expansion requested 2026-09-12; standard silk satin specification",
  },
  {
    id: "fs-fabric-exp-003",
    slug: "silk-twill",
    name: "Silk Twill",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% silk"],
    measurements: [{ unit: "momme", min: 14, max: 19 }],
    construction: ["Twill weave"],
    characteristics: ["Subtle diagonal grain", "Soft sheen", "Supple body"],
    applications: ["scarves", "blouses", "dresses"],
    source: "Frontend catalog expansion requested 2026-09-12; standard silk twill specification",
  },
  {
    id: "fs-fabric-exp-004",
    slug: "silk-noil",
    name: "Silk Noil",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% silk noil"],
    measurements: [{ unit: "gsm", min: 90, max: 150 }],
    construction: ["Plain weave"],
    characteristics: ["Matte surface", "Dry hand", "Visible short-fiber texture"],
    applications: ["blouses", "dresses", "resortwear"],
    source: "Frontend catalog expansion requested 2026-09-12; standard silk noil specification",
  },
  {
    id: "fs-fabric-exp-005",
    slug: "silk-tussar",
    name: "Silk Tussar",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% silk"],
    measurements: [{ unit: "momme", min: 18, max: 28 }],
    construction: ["Plain weave"],
    characteristics: ["Pronounced slub", "Crisp hand", "Irregular natural sheen"],
    applications: ["jackets", "occasionwear", "full-skirts"],
    source: "Frontend catalog expansion requested 2026-09-12; standard silk tussar specification",
  },
  {
    id: "fs-fabric-exp-006",
    slug: "silk-crepe",
    name: "Silk Crepe",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% silk"],
    measurements: [{ unit: "gsm", min: 70, max: 140 }],
    construction: ["Crepe weave"],
    characteristics: ["Fine pebbled surface", "Fluid drape", "Low sheen"],
    applications: ["dresses", "blouses", "slip-dresses"],
    source: "Frontend catalog expansion requested 2026-09-12; standard silk crepe specification",
  },
  {
    id: "fs-fabric-exp-007",
    slug: "silk-faille",
    name: "Silk Faille",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% silk"],
    measurements: [{ unit: "gsm", min: 130, max: 220 }],
    construction: ["Fine ribbed weave"],
    characteristics: ["Subtle crosswise rib", "Firm body", "Moderate sheen"],
    applications: ["jackets", "full-skirts", "occasionwear"],
    source: "Frontend catalog expansion requested 2026-09-12; standard silk faille specification",
  },
  {
    id: "fs-fabric-exp-008",
    slug: "silk-broadcloth",
    name: "Silk Broadcloth",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% silk"],
    measurements: [{ unit: "momme", min: 12, max: 18 }],
    construction: ["Plain weave"],
    characteristics: ["Fine close weave", "Crisp light hand", "Soft silk lustre"],
    applications: ["shirting", "blouses", "linings"],
    source: "Frontend catalog expansion requested 2026-09-12; standard silk broadcloth specification",
  },
  {
    id: "fs-fabric-exp-009",
    slug: "silk-chiffon-crepe",
    name: "Silk Chiffon Crepe",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% silk"],
    measurements: [{ unit: "gsm", min: 25, max: 55 }],
    construction: ["Crepe weave"],
    characteristics: ["Sheer", "Fine pebbled surface", "Floating drape"],
    applications: ["overlays", "scarves", "dresses"],
    source: "Frontend catalog expansion requested 2026-09-12; standard silk chiffon crepe specification",
  },
  {
    id: "fs-fabric-exp-010",
    slug: "polyester-chiffon",
    name: "Polyester Chiffon",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["100% polyester"],
    measurements: [{ unit: "gsm", min: 35, max: 70 }],
    construction: ["Plain weave"],
    characteristics: ["Sheer", "Lightweight", "Soft flowing drape"],
    applications: ["overlays", "scarves", "blouses"],
    source: "Frontend catalog expansion requested 2026-09-12; standard polyester chiffon specification",
  },
  {
    id: "fs-fabric-exp-011",
    slug: "recycled-polyester-chiffon",
    name: "Recycled Polyester Chiffon",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Recycled polyester"],
    measurements: [{ unit: "gsm", min: 35, max: 70 }],
    construction: ["Plain weave"],
    characteristics: ["Sheer", "Lightweight", "Soft flowing drape"],
    applications: ["overlays", "blouses", "scarves"],
    source: "Frontend catalog expansion requested 2026-09-12; standard recycled polyester chiffon specification",
  },
  {
    id: "fs-fabric-exp-012",
    slug: "matte-chiffon",
    name: "Matte Chiffon",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Polyester"],
    measurements: [{ unit: "gsm", min: 45, max: 85 }],
    construction: ["Plain weave"],
    characteristics: ["Semi-sheer", "Matte surface", "Soft fluid drape"],
    applications: ["dresses", "blouses", "overlays"],
    source: "Frontend catalog expansion requested 2026-09-12; standard matte chiffon specification",
  },
  {
    id: "fs-fabric-exp-013",
    slug: "stretch-chiffon",
    name: "Stretch Chiffon",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Polyester and elastane"],
    measurements: [{ unit: "gsm", min: 55, max: 95 }],
    construction: ["Plain weave"],
    characteristics: ["Semi-sheer", "Soft flowing drape", "Light crosswise recovery"],
    applications: ["dresses", "blouses", "overlays"],
    source: "Frontend catalog expansion requested 2026-09-12; standard stretch chiffon specification",
  },
  {
    id: "fs-fabric-exp-014",
    slug: "crinkle-chiffon",
    name: "Crinkle Chiffon",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Polyester"],
    measurements: [{ unit: "gsm", min: 45, max: 85 }],
    construction: ["Crinkled plain weave"],
    characteristics: ["Sheer", "Permanent puckered texture", "Airy drape"],
    applications: ["dresses", "scarves", "overlays"],
    source: "Frontend catalog expansion requested 2026-09-12; standard crinkle chiffon specification",
  },
  {
    id: "fs-fabric-exp-015",
    slug: "printed-chiffon",
    name: "Printed Chiffon",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Polyester"],
    measurements: [{ unit: "gsm", min: 40, max: 80 }],
    construction: ["Plain weave", "Surface print"],
    characteristics: ["Sheer", "Lightweight", "Soft flowing drape"],
    applications: ["dresses", "blouses", "scarves"],
    source: "Frontend catalog expansion requested 2026-09-12; standard printed chiffon specification",
  },
  {
    id: "fs-fabric-exp-016",
    slug: "double-layer-chiffon",
    name: "Double-Layer Chiffon",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Polyester"],
    measurements: [{ unit: "gsm", min: 80, max: 140 }],
    construction: ["Two-layer plain weave"],
    characteristics: ["Semi-sheer", "Increased opacity", "Fluid drape"],
    applications: ["dresses", "blouses", "overlays"],
    source: "Frontend catalog expansion requested 2026-09-12; standard double-layer chiffon specification",
  },
  {
    id: "fs-fabric-exp-017",
    slug: "cotton-lawn",
    name: "Cotton Lawn",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 70, max: 110 }],
    construction: ["Fine high-count plain weave"],
    characteristics: ["Lightweight", "Crisp hand", "Breathable matte surface"],
    applications: ["shirting", "blouses", "dresses"],
    source: "Frontend catalog expansion requested 2026-09-12; standard cotton lawn specification",
  },
  {
    id: "fs-fabric-exp-018",
    slug: "batiste-lawn",
    name: "Batiste Lawn",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 55, max: 90 }],
    construction: ["Fine plain weave"],
    characteristics: ["Very lightweight", "Soft crisp hand", "Breathable"],
    applications: ["blouses", "dresses", "linings"],
    source: "Frontend catalog expansion requested 2026-09-12; standard cotton batiste lawn specification",
  },
  {
    id: "fs-fabric-exp-019",
    slug: "printed-cotton-lawn",
    name: "Printed Cotton Lawn",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 75, max: 115 }],
    construction: ["Fine high-count plain weave", "Surface print"],
    characteristics: ["Lightweight", "Crisp hand", "Matte cotton surface"],
    applications: ["shirting", "dresses", "blouses"],
    source: "Frontend catalog expansion requested 2026-09-12; standard printed cotton lawn specification",
  },
  {
    id: "fs-fabric-exp-020",
    slug: "embroidered-cotton-lawn",
    name: "Embroidered Cotton Lawn",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 80, max: 130 }],
    construction: ["Fine plain weave", "Embroidery"],
    characteristics: ["Lightweight", "Breathable", "Raised stitched surface"],
    applications: ["blouses", "dresses", "overlays"],
    source: "Frontend catalog expansion requested 2026-09-12; standard embroidered cotton lawn specification",
  },
  {
    id: "fs-fabric-exp-021",
    slug: "organic-cotton-lawn",
    name: "Organic Cotton Lawn",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["100% organic cotton"],
    measurements: [{ unit: "gsm", min: 75, max: 115 }],
    construction: ["Fine high-count plain weave"],
    characteristics: ["Lightweight", "Crisp breathable hand", "Matte surface"],
    applications: ["shirting", "blouses", "dresses"],
    source: "Frontend catalog expansion requested 2026-09-12; standard organic cotton lawn specification",
  },
  {
    id: "fs-fabric-exp-022",
    slug: "mercerised-cotton-lawn",
    name: "Mercerised Cotton Lawn",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["100% mercerised cotton"],
    measurements: [{ unit: "gsm", min: 75, max: 115 }],
    construction: ["Fine plain weave"],
    characteristics: ["Lightweight", "Clean close weave", "Subtle cotton sheen"],
    applications: ["shirting", "blouses", "dresses"],
    source: "Frontend catalog expansion requested 2026-09-12; standard mercerised cotton lawn specification",
  },
  {
    id: "fs-fabric-exp-023",
    slug: "voile-lawn",
    name: "Voile Lawn",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 55, max: 90 }],
    construction: ["Fine open plain weave"],
    characteristics: ["Lightweight", "Slightly sheer", "Soft breathable hand"],
    applications: ["blouses", "overlays", "dresses"],
    source: "Frontend catalog expansion requested 2026-09-12; standard voile lawn specification",
  },
  {
    id: "fs-fabric-exp-024",
    slug: "slub-cotton-lawn",
    name: "Slub Cotton Lawn",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 80, max: 125 }],
    construction: ["Fine plain weave"],
    characteristics: ["Lightweight", "Subtle irregular slub", "Dry breathable hand"],
    applications: ["shirting", "blouses", "resortwear"],
    source: "Frontend catalog expansion requested 2026-09-12; standard slub cotton lawn specification",
  },
] as const satisfies readonly CatalogProduct[];
