import type { BestForSlug } from "./best-for";
import type {
  CatalogMeasurement,
  CatalogProduct,
  CatalogSeason,
} from "./types";

type CottonSpec = {
  id: string;
  slug: string;
  name: string;
  summary: string;
  description: string;
  composition: readonly string[];
  measurements: readonly CatalogMeasurement[];
  construction: readonly string[];
  characteristics: readonly string[];
  applications: readonly BestForSlug[];
};

const COTTON_SEASON: readonly CatalogSeason[] = ["SS 27"];

function cottonProduct(spec: CottonSpec): CatalogProduct {
  return {
    ...spec,
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: COTTON_SEASON,
    source:
      "Frontend catalog expansion requested 2026-09-12; standard trade description for the named cotton construction",
  };
}

export const EXPANDED_COTTON_FABRICS = [
  cottonProduct({
    id: "fs-cotton-exp-001",
    slug: "egyptian-cotton-poplin",
    name: "Egyptian Cotton Poplin",
    summary: "Fine long-staple cotton poplin with a clean, breathable plain weave.",
    description:
      "A refined shirting cotton with a smooth natural surface, crisp light body and the clean yarn definition expected from long-staple fibre.",
    composition: ["100% Egyptian cotton"],
    measurements: [{ unit: "gsm", min: 100, max: 135 }],
    construction: ["Fine plain weave", "Poplin rib"],
    characteristics: ["Smooth natural cotton surface", "Crisp", "Breathable"],
    applications: ["shirting", "blouses", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-002",
    slug: "egyptian-cotton-percale",
    name: "Egyptian Cotton Percale",
    summary: "Crisp long-staple cotton percale with a cool matte hand.",
    description:
      "A tightly woven, breathable cotton with a dry clean surface and stable body for premium shirts, summer dresses and bedding-led programmes.",
    composition: ["100% Egyptian cotton"],
    measurements: [{ unit: "gsm", min: 105, max: 145 }],
    construction: ["Close plain weave", "Percale construction"],
    characteristics: ["Crisp", "Matte", "Cool breathable hand"],
    applications: ["shirting", "dresses", "bedding"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-003",
    slug: "egyptian-cotton-sateen",
    name: "Egyptian Cotton Sateen",
    summary: "Smooth long-staple cotton sateen with a restrained soft lustre.",
    description:
      "A refined cotton sateen whose longer floats create a smoother face without turning the fabric into silk; it keeps a breathable, medium-weight cotton body.",
    composition: ["100% Egyptian cotton"],
    measurements: [{ unit: "gsm", min: 120, max: 180 }],
    construction: ["Sateen weave"],
    characteristics: ["Smooth face", "Subtle cotton lustre", "Soft drape"],
    applications: ["dresses", "blouses", "bedding"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-004",
    slug: "egyptian-cotton-voile",
    name: "Egyptian Cotton Voile",
    summary: "Lightweight fine cotton voile with a soft, breathable openness.",
    description:
      "A delicate long-staple cotton voile with an airy plain weave, gentle transparency and soft movement for warm-weather layering.",
    composition: ["100% Egyptian cotton"],
    measurements: [{ unit: "gsm", min: 50, max: 85 }],
    construction: ["Fine open plain weave"],
    characteristics: ["Lightweight", "Slightly sheer", "Soft breathable hand"],
    applications: ["blouses", "dresses", "overlays"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-005",
    slug: "egyptian-cotton-twill",
    name: "Egyptian Cotton Twill",
    summary: "Fine long-staple cotton twill with a soft diagonal grain.",
    description:
      "A breathable cotton twill with more body than poplin, combining refined yarn definition with a practical diagonal structure for shirts and lightweight trousers.",
    composition: ["100% Egyptian cotton"],
    measurements: [{ unit: "gsm", min: 150, max: 230 }],
    construction: ["2/1 twill"],
    characteristics: ["Fine diagonal grain", "Soft structure", "Breathable"],
    applications: ["shirting", "trousers", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-006",
    slug: "egyptian-cotton-broadcloth",
    name: "Egyptian Cotton Broadcloth",
    summary: "Fine-count long-staple cotton broadcloth with a compact smooth surface.",
    description:
      "A lightweight close plain weave that delivers an even, polished cotton surface while retaining the matte hand and breathability required for premium shirting.",
    composition: ["100% Egyptian cotton"],
    measurements: [{ unit: "gsm", min: 90, max: 125 }],
    construction: ["Fine close plain weave"],
    characteristics: ["Even yarn structure", "Smooth matte hand", "Light body"],
    applications: ["shirting", "blouses", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-007",
    slug: "egyptian-cotton-flannel",
    name: "Egyptian Cotton Flannel",
    summary: "Long-staple cotton flannel with a softly brushed, breathable face.",
    description:
      "A warmer cotton shirting cloth with a light brushed nap, natural fibre softness and enough body for premium casual shirts and sleepwear.",
    composition: ["100% Egyptian cotton"],
    measurements: [{ unit: "gsm", min: 150, max: 220 }],
    construction: ["Plain weave", "Light brushed finish"],
    characteristics: ["Soft brushed nap", "Warm breathable hand", "Moderate body"],
    applications: ["shirting", "loungewear", "bedding"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-008",
    slug: "egyptian-cotton-seersucker",
    name: "Egyptian Cotton Seersucker",
    summary: "Long-staple cotton seersucker with a breathable puckered surface.",
    description:
      "A lightweight cotton with alternating tension that lifts the cloth away from the skin, giving summer shirts and dresses a dry, airy character.",
    composition: ["100% Egyptian cotton"],
    measurements: [{ unit: "gsm", min: 90, max: 135 }],
    construction: ["Puckered plain weave", "Seersucker stripe"],
    characteristics: ["Puckered surface", "Airy", "Low-crease character"],
    applications: ["shirting", "dresses", "resortwear"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-009",
    slug: "classic-oxford-cotton",
    name: "Classic Oxford Cotton",
    summary: "Breathable cotton Oxford with a recognizable basketweave grain.",
    description:
      "A medium-light shirt cloth built from a slightly textured basketweave that gives more visual depth and body than plain poplin.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 125, max: 180 }],
    construction: ["Oxford basketweave"],
    characteristics: ["Textured grain", "Moderate body", "Breathable"],
    applications: ["shirting", "workwear-jackets", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-010",
    slug: "pinpoint-oxford-cotton",
    name: "Pinpoint Oxford Cotton",
    summary: "Fine Oxford cotton with a compact, polished basketweave.",
    description:
      "A finer Oxford construction that keeps the characteristic two-yarn texture but offers a cleaner surface and lighter handle for formal and premium shirts.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 110, max: 155 }],
    construction: ["Fine Oxford basketweave"],
    characteristics: ["Fine textured surface", "Crisp hand", "Stable"],
    applications: ["shirting", "workwear-jackets", "blouses"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-011",
    slug: "royal-oxford-cotton",
    name: "Royal Oxford Cotton",
    summary: "Dimensional Oxford shirting with a refined geometric texture.",
    description:
      "A dressier Oxford option with a more pronounced basketweave relief, combining breathable cotton comfort with a polished structured appearance.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 130, max: 185 }],
    construction: ["Royal Oxford basketweave"],
    characteristics: ["Raised geometric texture", "Smooth reverse", "Moderate body"],
    applications: ["shirting", "blouses", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-012",
    slug: "oxford-chambray-cotton",
    name: "Oxford Chambray Cotton",
    summary: "Light Oxford cotton with chambray colour contrast and a woven grain.",
    description:
      "A breathable coloured-yarn Oxford that reads lighter and more casual than classic white shirting while retaining its structured basketweave surface.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 110, max: 160 }],
    construction: ["Oxford basketweave", "Coloured warp and weft"],
    characteristics: ["Subtle colour contrast", "Textured", "Light structured body"],
    applications: ["shirting", "loungewear", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-013",
    slug: "soft-oxford-cotton",
    name: "Soft Oxford Cotton",
    summary: "Washed Oxford cotton with a softened hand and visible weave.",
    description:
      "A lightly softened Oxford that keeps its breathable basketweave definition while reducing the crispness for relaxed shirts and everyday uniform programmes.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 130, max: 190 }],
    construction: ["Oxford basketweave", "Softened finish"],
    characteristics: ["Softened hand", "Visible texture", "Breathable body"],
    applications: ["shirting", "loungewear", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-014",
    slug: "heavy-oxford-cotton",
    name: "Heavy Oxford Cotton",
    summary: "Substantial Oxford cotton for structured shirts and workwear.",
    description:
      "A heavier basketweave cotton with clear yarn relief and dependable body, suited to overshirts, chore shirts and durable uniform separates.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 180, max: 260 }],
    construction: ["Heavy Oxford basketweave"],
    characteristics: ["Substantial", "Textured", "Stable body"],
    applications: ["shirting", "workwear-jackets", "chore-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-015",
    slug: "stretch-oxford-cotton",
    name: "Stretch Oxford Cotton",
    summary: "Textured Oxford cotton with measured comfort stretch.",
    description:
      "A cotton Oxford with a restrained elastane component that preserves the recognizable basketweave while helping fitted shirts and uniforms move comfortably.",
    composition: ["98% cotton / 2% elastane"],
    measurements: [{ unit: "gsm", min: 130, max: 185 }],
    construction: ["Oxford basketweave"],
    characteristics: ["Textured", "Light comfort stretch", "Breathable"],
    applications: ["shirting", "workwear-jackets", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-016",
    slug: "organic-oxford-cotton",
    name: "Organic Oxford Cotton",
    summary: "Organic cotton Oxford with a natural basketweave texture.",
    description:
      "A breathable Oxford construction using organic cotton yarns, with the same slightly granular shirt-fabric character and moderate everyday body.",
    composition: ["100% organic cotton"],
    measurements: [{ unit: "gsm", min: 125, max: 180 }],
    construction: ["Oxford basketweave"],
    characteristics: ["Natural yarn character", "Textured", "Breathable"],
    applications: ["shirting", "workwear-jackets", "loungewear"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-017",
    slug: "pima-cotton-jersey",
    name: "Pima Cotton Jersey",
    summary: "Smooth fine Pima cotton jersey with a soft, clean face.",
    description:
      "A refined single jersey with fine Pima cotton yarns, a soft matte surface and fluid light-to-medium body for premium everyday knitwear.",
    composition: ["100% Pima cotton"],
    measurements: [{ unit: "gsm", min: 150, max: 190 }],
    construction: ["Single jersey knit"],
    characteristics: ["Fine smooth face", "Soft cotton hand", "Light fluid drape"],
    applications: ["baselayers", "knitwear", "knitwear"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-018",
    slug: "pima-cotton-interlock",
    name: "Pima Cotton Interlock",
    summary: "Smooth double-faced Pima cotton knit with stable body.",
    description:
      "A fine interlock made from Pima cotton, offering a smooth face and reverse, greater stability than jersey and a soft breathable hand for premium basics.",
    composition: ["100% Pima cotton"],
    measurements: [{ unit: "gsm", min: 190, max: 260 }],
    construction: ["Interlock knit"],
    characteristics: ["Double-faced smoothness", "Stable", "Soft breathable hand"],
    applications: ["knitwear", "baselayers", "loungewear"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-019",
    slug: "pima-cotton-poplin",
    name: "Pima Cotton Poplin",
    summary: "Fine Pima cotton poplin with a smooth crisp plain weave.",
    description:
      "A lightweight woven Pima cotton with clean yarn definition, a crisp hand and understated matte surface for premium shirting and summer dresses.",
    composition: ["100% Pima cotton"],
    measurements: [{ unit: "gsm", min: 95, max: 135 }],
    construction: ["Fine plain weave", "Poplin rib"],
    characteristics: ["Smooth fine surface", "Crisp", "Breathable"],
    applications: ["shirting", "dresses", "blouses"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-020",
    slug: "pima-cotton-sateen",
    name: "Pima Cotton Sateen",
    summary: "Smooth Pima cotton sateen with a low, natural cotton lustre.",
    description:
      "A fine sateen using long, smooth Pima yarns; it has a clean face and soft drape, but retains a breathable cotton hand rather than a silk-like shine.",
    composition: ["100% Pima cotton"],
    measurements: [{ unit: "gsm", min: 115, max: 170 }],
    construction: ["Sateen weave"],
    characteristics: ["Smooth face", "Subtle lustre", "Soft medium body"],
    applications: ["dresses", "blouses", "linings"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-021",
    slug: "pima-cotton-voile",
    name: "Pima Cotton Voile",
    summary: "Fine Pima cotton voile with airy transparency and soft movement.",
    description:
      "An exceptionally light cotton voile with a delicate open structure, fine yarn surface and breathable drape for warm-weather layers.",
    composition: ["100% Pima cotton"],
    measurements: [{ unit: "gsm", min: 50, max: 85 }],
    construction: ["Fine open plain weave"],
    characteristics: ["Lightweight", "Slightly sheer", "Soft matte cotton"],
    applications: ["blouses", "dresses", "overlays"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-022",
    slug: "pima-cotton-fleece",
    name: "Pima Cotton Fleece",
    summary: "Soft Pima cotton fleece with a brushed inner face and clean outer knit.",
    description:
      "A premium cotton fleece with fine yarn definition, a smooth outer surface and a softly brushed reverse for comfortable sweatshirts and loungewear.",
    composition: ["100% Pima cotton"],
    measurements: [{ unit: "gsm", min: 260, max: 360 }],
    construction: ["Fleece knit", "Brushed back"],
    characteristics: ["Smooth outer face", "Soft brushed reverse", "Warm body"],
    applications: ["loungewear", "knitwear", "layering-pieces"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-023",
    slug: "pima-cotton-rib",
    name: "Pima Cotton Rib",
    summary: "Fine Pima cotton rib with soft stretch and clean recovery.",
    description:
      "A smooth rib knit using fine Pima yarns, balancing breathable cotton softness with the natural crosswise movement needed for close-to-body basics.",
    composition: ["100% Pima cotton"],
    measurements: [{ unit: "gsm", min: 180, max: 260 }],
    construction: ["1×1 rib knit"],
    characteristics: ["Fine vertical ribs", "Natural stretch", "Soft smooth hand"],
    applications: ["baselayers", "knitwear", "loungewear"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-024",
    slug: "pima-cotton-broadcloth",
    name: "Pima Cotton Broadcloth",
    summary: "Light Pima cotton broadcloth with an even fine-count surface.",
    description:
      "A clean close plain weave with a smooth matte face, light body and refined yarn regularity for premium shirts, blouses and summer uniforms.",
    composition: ["100% Pima cotton"],
    measurements: [{ unit: "gsm", min: 90, max: 125 }],
    construction: ["Fine close plain weave"],
    characteristics: ["Even fine yarns", "Smooth matte surface", "Light body"],
    applications: ["shirting", "blouses", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-025",
    slug: "mercerized-cotton-poplin",
    name: "Mercerized Cotton Poplin",
    summary: "Refined mercerized cotton poplin with a clean, subtle lustre.",
    description:
      "A smooth plain-weave cotton finished to improve surface clarity and lustre without losing its breathable woven character or crisp shirting body.",
    composition: ["100% mercerized cotton"],
    measurements: [{ unit: "gsm", min: 100, max: 140 }],
    construction: ["Fine plain weave", "Mercerized finish"],
    characteristics: ["Clean yarn surface", "Subtle lustre", "Crisp breathable body"],
    applications: ["shirting", "blouses", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-026",
    slug: "mercerized-cotton-jersey",
    name: "Mercerized Cotton Jersey",
    summary: "Smooth mercerized cotton jersey with a refined face and soft drape.",
    description:
      "A fine jersey whose cotton yarns have been treated for a cleaner, slightly brighter surface; it remains matte-to-softly lustrous rather than satin-like.",
    composition: ["100% mercerized cotton"],
    measurements: [{ unit: "gsm", min: 145, max: 195 }],
    construction: ["Single jersey knit", "Mercerized finish"],
    characteristics: ["Smooth refined face", "Soft subtle lustre", "Breathable"],
    applications: ["knitwear", "baselayers", "knitwear"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-027",
    slug: "mercerized-cotton-sateen",
    name: "Mercerized Cotton Sateen",
    summary: "Smooth cotton sateen with an enhanced but controlled surface lustre.",
    description:
      "A refined cotton sateen with cleaner yarn definition and slightly increased light reflection, while retaining a substantial breathable cotton handle.",
    composition: ["100% mercerized cotton"],
    measurements: [{ unit: "gsm", min: 120, max: 180 }],
    construction: ["Sateen weave", "Mercerized finish"],
    characteristics: ["Smooth face", "Controlled lustre", "Soft body"],
    applications: ["dresses", "blouses", "linings"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-028",
    slug: "mercerized-cotton-voile",
    name: "Mercerized Cotton Voile",
    summary: "Fine mercerized cotton voile with a cleaner translucent surface.",
    description:
      "A lightweight voile with fine cotton yarns and a restrained finish that sharpens the surface while preserving its breathable openness and delicate movement.",
    composition: ["100% mercerized cotton"],
    measurements: [{ unit: "gsm", min: 55, max: 90 }],
    construction: ["Fine open plain weave", "Mercerized finish"],
    characteristics: ["Lightweight", "Slightly sheer", "Clean subtle lustre"],
    applications: ["blouses", "dresses", "overlays"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-029",
    slug: "mercerized-cotton-pique",
    name: "Mercerized Cotton Piqué",
    summary: "Dimensional cotton piqué with a smoother, cleaner finished face.",
    description:
      "A breathable piqué with raised texture and a mercerized yarn finish that clarifies the surface; the geometric relief remains more important than the subtle lustre.",
    composition: ["100% mercerized cotton"],
    measurements: [{ unit: "gsm", min: 180, max: 250 }],
    construction: ["Piqué knit", "Mercerized finish"],
    characteristics: ["Raised texture", "Clean subtle lustre", "Breathable body"],
    applications: ["shirting", "knitwear", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-030",
    slug: "mercerized-cotton-twill",
    name: "Mercerized Cotton Twill",
    summary: "Smooth cotton twill with refined yarn clarity and soft lustre.",
    description:
      "A medium-weight cotton twill whose finish sharpens the diagonal grain and gives the surface a quiet polish without making the fabric glossy or synthetic.",
    composition: ["100% mercerized cotton"],
    measurements: [{ unit: "gsm", min: 160, max: 240 }],
    construction: ["2/1 twill", "Mercerized finish"],
    characteristics: ["Clear diagonal grain", "Subtle lustre", "Stable drape"],
    applications: ["trousers", "workwear-jackets", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-031",
    slug: "mercerized-cotton-broadcloth",
    name: "Mercerized Cotton Broadcloth",
    summary: "Fine broadcloth with clean mercerized cotton yarns.",
    description:
      "A lightweight close weave for polished shirts and blouses, combining crisp cotton body with the smoother surface and restrained brightness of mercerization.",
    composition: ["100% mercerized cotton"],
    measurements: [{ unit: "gsm", min: 90, max: 130 }],
    construction: ["Fine close plain weave", "Mercerized finish"],
    characteristics: ["Fine yarn structure", "Smooth face", "Restrained brightness"],
    applications: ["shirting", "blouses", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-032",
    slug: "mercerized-cotton-lawn",
    name: "Mercerized Cotton Lawn",
    summary: "Lightweight cotton lawn with a clean fine weave and soft lustre.",
    description:
      "A fine lawn with a mercerized finish that gives the breathable cotton surface extra clarity while keeping its crisp, light construction visible.",
    composition: ["100% mercerized cotton"],
    measurements: [{ unit: "gsm", min: 70, max: 110 }],
    construction: ["Fine high-count plain weave", "Mercerized finish"],
    characteristics: ["Lightweight", "Crisp", "Subtle natural lustre"],
    applications: ["shirting", "blouses", "dresses"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-033",
    slug: "classic-cotton-pique",
    name: "Classic Cotton Piqué",
    summary: "Breathable cotton piqué with a clear raised geometric texture.",
    description:
      "A dependable polo and shirting construction with a dimensional piqué face, dry cotton hand and enough body to hold a clean casual silhouette.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 180, max: 240 }],
    construction: ["Piqué knit"],
    characteristics: ["Raised geometric texture", "Breathable", "Moderate body"],
    applications: ["shirting", "knitwear", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-034",
    slug: "fine-cotton-pique",
    name: "Fine Cotton Piqué",
    summary: "Light fine-gauge piqué for breathable premium polos.",
    description:
      "A finer piqué with smaller surface relief and a lighter hand, keeping the characteristic dimensional cotton texture for warm-weather polos and refined basics.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 150, max: 200 }],
    construction: ["Fine-gauge piqué knit"],
    characteristics: ["Fine raised texture", "Lightweight", "Breathable"],
    applications: ["shirting", "knitwear", "baselayers"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-035",
    slug: "honeycomb-cotton-pique",
    name: "Honeycomb Cotton Piqué",
    summary: "Cotton piqué with an open honeycomb surface and airy body.",
    description:
      "A visibly dimensional honeycomb construction that increases surface texture and ventilation while retaining a stable cotton polo-fabric character.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 190, max: 260 }],
    construction: ["Honeycomb piqué knit"],
    characteristics: ["Open geometric relief", "Airy", "Textured body"],
    applications: ["shirting", "performance-apparel", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-036",
    slug: "birdseye-cotton-pique",
    name: "Birdseye Cotton Piqué",
    summary: "Compact cotton piqué with a fine birdseye relief.",
    description:
      "A smaller-scale dimensional piqué with a neat surface pattern and breathable cotton hand, suited to polished polos and understated uniforms.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 170, max: 225 }],
    construction: ["Birdseye piqué knit"],
    characteristics: ["Fine raised pattern", "Compact", "Breathable"],
    applications: ["shirting", "workwear-jackets", "knitwear"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-037",
    slug: "stretch-cotton-pique",
    name: "Stretch Cotton Piqué",
    summary: "Textured cotton piqué with restrained stretch and recovery.",
    description:
      "A dimensional cotton piqué blended with elastane for fitted polos and uniform tops, keeping the raised breathable surface visible through movement.",
    composition: ["96% cotton / 4% elastane"],
    measurements: [{ unit: "gsm", min: 190, max: 260 }],
    construction: ["Piqué knit"],
    characteristics: ["Raised texture", "Comfort stretch", "Breathable"],
    applications: ["shirting", "workwear-jackets", "performance-apparel"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-038",
    slug: "double-cotton-pique",
    name: "Double Cotton Piqué",
    summary: "Heavier double piqué with a stable dimensional cotton surface.",
    description:
      "A dense double-layer piqué with extra body and warmth, designed for structured polo shirts, outer layers and durable premium casualwear.",
    composition: ["100% cotton"],
    measurements: [{ unit: "gsm", min: 240, max: 330 }],
    construction: ["Double piqué knit"],
    characteristics: ["Dense raised texture", "Stable body", "Breathable warmth"],
    applications: ["shirting", "jackets", "layering-pieces"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-039",
    slug: "organic-cotton-pique",
    name: "Organic Cotton Piqué",
    summary: "Organic cotton piqué with a natural dimensional texture.",
    description:
      "A breathable polo construction made with organic cotton yarns, retaining a dry hand, raised geometric face and stable everyday body.",
    composition: ["100% organic cotton"],
    measurements: [{ unit: "gsm", min: 180, max: 245 }],
    construction: ["Piqué knit"],
    characteristics: ["Raised texture", "Natural yarn character", "Breathable"],
    applications: ["shirting", "knitwear", "workwear-jackets"],
  }),
  cottonProduct({
    id: "fs-cotton-exp-040",
    slug: "cotton-rich-pique",
    name: "Cotton-Rich Piqué",
    summary: "Cotton-rich piqué with a soft dimensional face and easy body.",
    description:
      "A cotton-dominant piqué blend that keeps the geometric surface and breathable polo character while adding a softer hand for premium casualwear.",
    composition: ["80% cotton / 20% recycled polyester"],
    measurements: [{ unit: "gsm", min: 190, max: 260 }],
    construction: ["Piqué knit"],
    characteristics: ["Dimensional surface", "Soft hand", "Stable breathable body"],
    applications: ["shirting", "loungewear", "workwear-jackets"],
  }),
] as const satisfies readonly CatalogProduct[];
