import { BEST_FOR, BEST_FOR_BY_SLUG } from "./best-for";
import {
  COLLECTION_BY_SLUG,
  COLLECTIONS,
  SOURCE_FAMILIES,
  SOURCE_FAMILY_BY_SLUG,
} from "./collections";
import { EXPANDED_COTTON_FABRICS } from "./expanded-cotton";
import { EXPANDED_JERSEY_CELLULOSIC_WOOL } from "./expanded-jersey-cellulosic-wool";
import { EXPANDED_FABRICS } from "./expanded-fabrics";
import { MEDIA_BY_FABRIC_SLUG } from "./media";
import type { CatalogProduct, FabricMedia } from "./types";

export const FABRICS_2027 = [
  {
    id: "fs-fabric-2027-001",
    slug: "european-flax-linen",
    name: "European Flax Linen",
    family: "linen-and-linen-blends",
    collection: "linen-lightweight",
    seasons: ["SS 27"],
    composition: ["100% flax"],
    measurements: [{ unit: "gsm", min: 120, max: 200 }],
    applications: ["shirting", "trousers", "dresses", "jackets"],
    source: "fabrics-2027.md — Part 1 §1.1, table row “European flax linen”",
  },
  {
    id: "fs-fabric-2027-002",
    slug: "linen-cotton",
    name: "Linen–Cotton",
    family: "linen-and-linen-blends",
    collection: "linen-lightweight",
    seasons: ["SS 27"],
    composition: ["55% linen / 45% cotton", "70% linen / 30% cotton"],
    measurements: [{ unit: "gsm", min: 140, max: 220 }],
    applications: ["shirting", "chore-jackets", "bottoms"],
    source: "fabrics-2027.md — Part 1 §1.1, table row “Linen–cotton”",
  },
  {
    id: "fs-fabric-2027-003",
    slug: "linen-silk",
    name: "Linen–Silk",
    family: "linen-and-linen-blends",
    collection: "linen-lightweight",
    seasons: ["SS 27"],
    composition: ["70% linen / 30% mulberry silk"],
    measurements: [{ unit: "gsm", min: 130, max: 180 }],
    applications: ["knitwear", "dresses", "resortwear"],
    source: "fabrics-2027.md — Part 1 §1.1, table row “Linen–silk”",
  },
  {
    id: "fs-fabric-2027-004",
    slug: "linen-viscose",
    name: "Linen–Viscose",
    family: "linen-and-linen-blends",
    collection: "linen-lightweight",
    seasons: ["SS 27"],
    composition: ["55% linen / 45% viscose"],
    measurements: [{ unit: "gsm", min: 130, max: 170 }],
    characteristics: ["Drapey"],
    applications: ["trousers", "soft-tailoring"],
    source:
      "fabrics-2027.md — Part 1 §1.1, table row “Linen–viscose / linen–lyocell”",
  },
  {
    id: "fs-fabric-2027-005",
    slug: "linen-lyocell",
    name: "Linen–Lyocell",
    family: "linen-and-linen-blends",
    collection: "linen-lightweight",
    seasons: ["SS 27"],
    composition: ["55% linen / 45% lyocell"],
    measurements: [{ unit: "gsm", min: 130, max: 170 }],
    characteristics: ["Drapey"],
    applications: ["trousers", "soft-tailoring"],
    source:
      "fabrics-2027.md — Part 1 §1.1, table row “Linen–viscose / linen–lyocell”",
  },
  {
    id: "fs-fabric-2027-006",
    slug: "cotton-poplin",
    name: "Cotton Poplin",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["Cotton"],
    construction: ["Fine-count, high-twist"],
    characteristics: ["Crisp", "Translucent"],
    applications: ["shirting"],
    source: "fabrics-2027.md — Part 1 §1.2, table row “Poplin and voile”",
  },
  {
    id: "fs-fabric-2027-007",
    slug: "cotton-voile",
    name: "Cotton Voile",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["Cotton"],
    construction: ["Fine-count, high-twist"],
    characteristics: ["Crisp", "Translucent"],
    applications: ["shirting"],
    source: "fabrics-2027.md — Part 1 §1.2, table row “Poplin and voile”",
  },
  {
    id: "fs-fabric-2027-008",
    slug: "cotton-organdy",
    name: "Cotton Organdy",
    aliases: ["Cotton organza"],
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["Cotton"],
    characteristics: ["Stiff", "Sheer", "Holds volume"],
    applications: ["layering-pieces"],
    source:
      "fabrics-2027.md — Part 1 §1.2, table row “Organdy / organza cotton”",
  },
  {
    id: "fs-fabric-2027-009",
    slug: "cotton-boucle-yarn",
    name: "Cotton Bouclé Yarn",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["100% cotton"],
    construction: ["Bouclé yarn"],
    characteristics: ["Volume without weight"],
    applications: ["knitwear"],
    source: "fabrics-2027.md — Part 1 §1.2, table row “Cotton bouclé yarn”",
  },
  {
    id: "fs-fabric-2027-010",
    slug: "cotton-seersucker",
    name: "Cotton Seersucker",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["Cotton"],
    characteristics: ["Puckered surface", "No pressing"],
    applications: [],
    source: "fabrics-2027.md — Part 1 §1.2, table row “Seersucker and crinkle”",
  },
  {
    id: "fs-fabric-2027-011",
    slug: "crinkle-cotton",
    name: "Crinkle Cotton",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["Cotton"],
    characteristics: ["Puckered surface", "No pressing"],
    applications: [],
    source: "fabrics-2027.md — Part 1 §1.2, table row “Seersucker and crinkle”",
  },
  {
    id: "fs-fabric-2027-012",
    slug: "slub-cotton",
    name: "Slub Cotton",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["Cotton"],
    characteristics: ["Irregular yarn", "Handmade character"],
    applications: [],
    source: "fabrics-2027.md — Part 1 §1.2, table row “Slub and khadi-effect”",
  },
  {
    id: "fs-fabric-2027-013",
    slug: "khadi-effect-cotton",
    name: "Khadi-Effect Cotton",
    family: "cotton-light-open-textured",
    collection: "cotton",
    seasons: ["SS 27"],
    composition: ["Cotton"],
    characteristics: ["Irregular yarn", "Handmade character"],
    applications: [],
    source: "fabrics-2027.md — Part 1 §1.2, table row “Slub and khadi-effect”",
  },
  {
    id: "fs-fabric-2027-014",
    slug: "silk-chiffon",
    name: "Silk Chiffon",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Silk"],
    measurements: [{ unit: "momme", min: 8, max: 12 }],
    construction: ["Plain weave", "High-twist yarns"],
    characteristics: ["Sheer", "Floating"],
    applications: ["dresses", "blouses", "scarves"],
    source: "fabrics-2027.md — Part 1 §1.3, table row “Chiffon”",
  },
  {
    id: "fs-fabric-2027-015",
    slug: "silk-georgette",
    name: "Silk Georgette",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Silk"],
    characteristics: [
      "Crinkled",
      "Slightly heavier than chiffon",
      "Better drape",
    ],
    applications: ["dresses", "trousers"],
    source: "fabrics-2027.md — Part 1 §1.3, table row “Georgette”",
  },
  {
    id: "fs-fabric-2027-016",
    slug: "silk-organza",
    name: "Silk Organza",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Silk"],
    characteristics: ["Sheer", "Stiff", "Holds shape"],
    applications: ["volume-sleeves", "overlays", "ruffles"],
    source: "fabrics-2027.md — Part 1 §1.3, table row “Organza”",
  },
  {
    id: "fs-fabric-2027-017",
    slug: "silk-taffeta",
    name: "Silk Taffeta",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Silk"],
    construction: ["Plain weave"],
    characteristics: ["Crisp", "Papery rustle"],
    applications: ["occasionwear", "full-skirts", "lightweight-outerwear"],
    source: "fabrics-2027.md — Part 1 §1.3, table row “Taffeta”",
  },
  {
    id: "fs-fabric-2027-018",
    slug: "crepe-de-chine",
    name: "Crepe de Chine",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Silk"],
    characteristics: ["Matte", "Fluid", "Hangs close to the body"],
    applications: ["slip-dresses", "shirting", "linings"],
    source: "fabrics-2027.md — Part 1 §1.3, table row “Crepe de chine”",
  },
  {
    id: "fs-fabric-2027-019",
    slug: "silk-habotai",
    name: "Silk Habotai",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Silk"],
    measurements: [{ unit: "momme", min: 8, max: 12 }],
    characteristics: ["Thin", "Smooth"],
    applications: ["linings", "scarves"],
    source: "fabrics-2027.md — Part 1 §1.3, table row “Habotai”",
  },
  {
    id: "fs-fabric-2027-020",
    slug: "silk-dupion",
    name: "Silk Dupion",
    aliases: ["Silk shantung"],
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["Silk"],
    characteristics: ["Slubby", "Irregular", "High sheen"],
    applications: ["jackets", "occasionwear", "home-decor"],
    source: "fabrics-2027.md — Part 1 §1.3, table row “Dupion / shantung”",
  },
  {
    id: "fs-fabric-2027-021",
    slug: "silk-boucle",
    name: "Silk Bouclé",
    family: "silk-and-ethereal",
    collection: "silk-sheer",
    seasons: ["SS 27"],
    composition: ["99% silk / 1% bouclé yarn"],
    characteristics: [
      "Lightly elasticized",
      "Structured",
      "Natural silk lustre",
    ],
    applications: ["knitwear", "jackets"],
    source: "fabrics-2027.md — Part 1 §1.3, table row “Silk bouclé”",
  },
  {
    id: "fs-fabric-2027-022",
    slug: "merino-roica-stretch-tailoring",
    name: "Merino + Roica Stretch Tailoring",
    family: "summer-wools-and-tailoring",
    collection: "tailoring",
    seasons: ["SS 27"],
    composition: ["Merino wool with Roica elastomer"],
    characteristics: ["Wrinkle resistant", "Elastic", "Comfortable", "Durable"],
    applications: ["suiting"],
    source: "fabrics-2027.md — Part 1 §1.4, bullet “Merino + Roica stretch”",
  },
  {
    id: "fs-fabric-2027-023",
    slug: "wool-silk-bi-stretch",
    name: "Wool–Silk Bi-Stretch",
    family: "summer-wools-and-tailoring",
    collection: "tailoring",
    seasons: ["SS 27"],
    composition: ["Wool and silk"],
    characteristics: [
      "Natural bi-stretch",
      "Lightweight",
      "Crease resistant",
      "Breathable",
    ],
    applications: ["suiting"],
    source: "fabrics-2027.md — Part 1 §1.4, bullet “Wool–silk bi-stretch”",
  },
  {
    id: "fs-fabric-2027-024",
    slug: "wool-linen-open-weave",
    name: "Wool–Linen Open Weave",
    family: "summer-wools-and-tailoring",
    collection: "tailoring",
    seasons: ["SS 27"],
    composition: ["Wool and linen"],
    measurements: [{ unit: "gsm", min: 180, max: 240 }],
    construction: ["Open weave"],
    applications: ["unstructured-jackets"],
    source:
      "fabrics-2027.md — Part 1 §1.4, bullet “Wool–linen and wool–mohair open weaves”",
  },
  {
    id: "fs-fabric-2027-025",
    slug: "wool-mohair-open-weave",
    name: "Wool–Mohair Open Weave",
    family: "summer-wools-and-tailoring",
    collection: "tailoring",
    seasons: ["SS 27"],
    composition: ["Wool and mohair"],
    measurements: [{ unit: "gsm", min: 180, max: 240 }],
    construction: ["Open weave"],
    applications: ["unstructured-jackets"],
    source:
      "fabrics-2027.md — Part 1 §1.4, bullet “Wool–linen and wool–mohair open weaves”",
  },
  {
    id: "fs-fabric-2027-026",
    slug: "tropical-wool-super-110s-130s",
    name: "Super 110s–130s Tropical Wool",
    family: "summer-wools-and-tailoring",
    collection: "tailoring",
    seasons: ["SS 27"],
    composition: ["Wool"],
    construction: ["Tropical wool", "Super 110s–130s"],
    applications: ["suiting"],
    source:
      "fabrics-2027.md — Part 1 §1.4, bullet “Super 110s–130s tropical wool”",
  },
  {
    id: "fs-fabric-2027-027",
    slug: "open-stitch-knit",
    name: "Open-Stitch Knit",
    family: "year-round-knitwear",
    collection: "knitwear",
    seasons: ["SS 27"],
    composition: ["Cotton, linen or blends"],
    measurements: [{ unit: "gauge", min: 7, max: 12 }],
    construction: ["Open stitch"],
    applications: ["resortwear"],
    source:
      "fabrics-2027.md — Part 1 §1.5, table row “Open-stitch / pointelle / crochet-effect”",
  },
  {
    id: "fs-fabric-2027-028",
    slug: "pointelle-knit",
    name: "Pointelle Knit",
    family: "year-round-knitwear",
    collection: "knitwear",
    seasons: ["SS 27"],
    composition: ["Cotton, linen or blends"],
    measurements: [{ unit: "gauge", min: 7, max: 12 }],
    construction: ["Pointelle"],
    applications: ["resortwear"],
    source:
      "fabrics-2027.md — Part 1 §1.5, table row “Open-stitch / pointelle / crochet-effect”",
  },
  {
    id: "fs-fabric-2027-029",
    slug: "crochet-effect-knit",
    name: "Crochet-Effect Knit",
    family: "year-round-knitwear",
    collection: "knitwear",
    seasons: ["SS 27"],
    composition: ["Cotton, linen or blends"],
    measurements: [{ unit: "gauge", min: 7, max: 12 }],
    construction: ["Crochet effect"],
    applications: ["resortwear"],
    source:
      "fabrics-2027.md — Part 1 §1.5, table row “Open-stitch / pointelle / crochet-effect”",
  },
  {
    id: "fs-fabric-2027-030",
    slug: "fine-gauge-semi-sheer-knit",
    name: "Fine-Gauge Semi-Sheer Knit",
    family: "year-round-knitwear",
    collection: "knitwear",
    seasons: ["SS 27"],
    composition: ["Silk", "Silk-cotton", "Fine merino"],
    measurements: [{ unit: "gauge", min: 14, max: 18 }],
    characteristics: ["Semi-sheer"],
    applications: ["layering-pieces"],
    source: "fabrics-2027.md — Part 1 §1.5, table row “Fine-gauge semi-sheer”",
  },
  {
    id: "fs-fabric-2027-031",
    slug: "cotton-boucle-knit",
    name: "Cotton Bouclé Knit",
    family: "year-round-knitwear",
    collection: "knitwear",
    seasons: ["SS 27"],
    composition: ["Cotton"],
    construction: ["Bouclé knit"],
    characteristics: ["Volume without weight"],
    applications: ["knitwear"],
    source:
      "fabrics-2027.md — Part 1 §1.5, table row “Cotton and linen bouclé”",
  },
  {
    id: "fs-fabric-2027-032",
    slug: "linen-boucle-knit",
    name: "Linen Bouclé Knit",
    family: "year-round-knitwear",
    collection: "knitwear",
    seasons: ["SS 27"],
    composition: ["Linen"],
    construction: ["Bouclé knit"],
    characteristics: ["Volume without weight"],
    applications: ["knitwear"],
    source:
      "fabrics-2027.md — Part 1 §1.5, table row “Cotton and linen bouclé”",
  },
  {
    id: "fs-fabric-2027-033",
    slug: "lightweight-merino-knit",
    name: "Lightweight Merino Knit",
    family: "year-round-knitwear",
    collection: "knitwear",
    seasons: ["SS 27"],
    composition: ["Merino wool"],
    measurements: [{ unit: "micron", min: 17.5, max: 19.5 }],
    characteristics: ["Lightweight", "Shoulder-season weight"],
    applications: ["layering-pieces"],
    source:
      "fabrics-2027.md — Part 1 §1.5, table row “Lightweight merino (17.5–19.5 micron)”",
  },
  {
    id: "fs-fabric-2027-034",
    slug: "stretch-woven-compression",
    name: "Stretch-Woven Compression",
    family: "performance-swim-next-to-skin",
    collection: "performance",
    seasons: ["SS 27"],
    construction: ["Stretch woven"],
    characteristics: ["Compression", "Barely-there performance"],
    applications: ["baselayers"],
    source: "fabrics-2027.md — Part 1 §1.6, bullet “Stretch-woven compression”",
  },
  {
    id: "fs-fabric-2027-035",
    slug: "crossover-swimwear-fabric",
    name: "Crossover Swimwear Fabric",
    family: "performance-swim-next-to-skin",
    collection: "performance",
    seasons: ["SS 27"],
    characteristics: ["Designed to cross over beyond swimwear"],
    applications: ["swimwear", "citywear", "loungewear"],
    source:
      "fabrics-2027.md — Part 1 §1.6, bullet “Swimwear fabric that crosses over”",
  },
  {
    id: "fs-fabric-2027-036",
    slug: "cooling-performance-construction",
    name: "Cooling Performance Construction",
    family: "performance-swim-next-to-skin",
    collection: "performance",
    seasons: ["SS 27"],
    characteristics: ["Cooling", "Long-lasting fresh feel", "Year-round use"],
    applications: ["performance-apparel"],
    source: "fabrics-2027.md — Part 1 §1.6, bullet “Cooling constructions”",
  },
  {
    id: "fs-fabric-2027-037",
    slug: "ultra-light-semi-sheer-lounge-knit",
    name: "Ultra-Light Semi-Sheer Lounge Knit",
    family: "performance-swim-next-to-skin",
    collection: "performance",
    seasons: ["SS 27"],
    construction: ["Knit"],
    characteristics: ["Ultra-light", "Semi-sheer"],
    applications: ["loungewear"],
    source:
      "fabrics-2027.md — Part 1 §1.6, bullet “Ultra-light semi-sheer knit”",
  },
  {
    id: "fs-fabric-2027-038",
    slug: "retro-sportif-knit",
    name: "Retro Sportif Knit",
    family: "performance-swim-next-to-skin",
    collection: "performance",
    seasons: ["SS 27"],
    construction: ["Piqué", "Mesh", "Tricot", "Colour-blocked ribs"],
    characteristics: ["1990s soccer and basketball kit reference"],
    applications: ["performance-apparel"],
    source: "fabrics-2027.md — Part 1 §1.6, bullet “Retro sportif”",
  },
  {
    id: "fs-fabric-2027-039",
    slug: "melton",
    name: "Melton",
    family: "brushed-and-felted",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Wool", "Wool blend"],
    measurements: [{ unit: "gsm", min: 500, max: 800 }],
    construction: ["Heavily felted and cropped"],
    characteristics: ["Cut edges need no finishing"],
    applications: ["coats"],
    source: "fabrics-2027.md — Part 2 §2.1, table row “Melton”",
  },
  {
    id: "fs-fabric-2027-040",
    slug: "boiled-wool",
    name: "Boiled Wool",
    family: "brushed-and-felted",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Wool"],
    measurements: [{ unit: "gsm", min: 350, max: 550 }],
    construction: ["Knitted then shrunk"],
    applications: ["jackets", "unlined-coats", "soft-tailoring"],
    source: "fabrics-2027.md — Part 2 §2.1, table row “Boiled wool”",
  },
  {
    id: "fs-fabric-2027-041",
    slug: "double-face-wool",
    name: "Double-Face Wool",
    family: "brushed-and-felted",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Wool"],
    measurements: [{ unit: "gsm", min: 400, max: 700 }],
    construction: ["Two faces bonded or woven"],
    characteristics: ["Reversible"],
    applications: ["unlined-coats"],
    source: "fabrics-2027.md — Part 2 §2.1, table row “Double-face wool”",
  },
  {
    id: "fs-fabric-2027-042",
    slug: "brushed-flannel",
    name: "Brushed Flannel",
    family: "brushed-and-felted",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Wool", "Cotton"],
    measurements: [{ unit: "gsm", min: 250, max: 400 }],
    construction: ["Raised nap"],
    applications: ["shirting", "trousers", "suiting"],
    source: "fabrics-2027.md — Part 2 §2.1, table row “Brushed flannel”",
  },
  {
    id: "fs-fabric-2027-043",
    slug: "mohair-blend",
    name: "Mohair Blend",
    family: "brushed-and-felted",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Mohair blend"],
    measurements: [{ unit: "gsm", min: 300, max: 600 }],
    characteristics: ["Long hair fibre", "Halo effect"],
    applications: ["coats", "statement-knits"],
    source:
      "fabrics-2027.md — Part 2 §2.1, table row “Mohair and alpaca blends”",
  },
  {
    id: "fs-fabric-2027-044",
    slug: "alpaca-blend",
    name: "Alpaca Blend",
    family: "brushed-and-felted",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Alpaca blend"],
    measurements: [{ unit: "gsm", min: 300, max: 600 }],
    characteristics: ["Long hair fibre", "Halo effect"],
    applications: ["coats", "statement-knits"],
    source:
      "fabrics-2027.md — Part 2 §2.1, table row “Mohair and alpaca blends”",
  },
  {
    id: "fs-fabric-2027-045",
    slug: "casentino-wool",
    name: "Casentino Wool",
    family: "brushed-and-felted",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Wool"],
    measurements: [{ unit: "gsm", min: 600, qualifier: "600+" }],
    construction: ["Curled ricciolo surface"],
    characteristics: ["Heritage coating", "Craft character"],
    applications: ["coats"],
    source: "fabrics-2027.md — Part 2 §2.1, table row “Casentino”",
  },
  {
    id: "fs-fabric-2027-046",
    slug: "cotton-moleskin",
    name: "Cotton Moleskin",
    family: "suede-touch-and-dry-hand",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Cotton"],
    measurements: [{ unit: "gsm", min: 280, max: 360 }],
    construction: ["Dense sueded twill"],
    applications: ["workwear-trousers", "workwear-jackets"],
    source: "fabrics-2027.md — Part 2 §2.2, bullet “Moleskin”",
  },
  {
    id: "fs-fabric-2027-047",
    slug: "peach-skin",
    name: "Peach-Skin",
    family: "suede-touch-and-dry-hand",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Microfibre polyester", "Poly-cotton"],
    construction: ["Sanded"],
    characteristics: ["Dry, powdery hand"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.2, bullet “Peach-skin”",
  },
  {
    id: "fs-fabric-2027-048",
    slug: "suede-effect-woven",
    name: "Suede-Effect Woven",
    family: "suede-touch-and-dry-hand",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Poly-nylon microfibre"],
    construction: ["Woven", "Brushed on both sides"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.2, bullet “Suede-effect wovens”",
  },
  {
    id: "fs-fabric-2027-093",
    slug: "real-suede",
    name: "Real Suede",
    family: "suede-touch-and-dry-hand",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Suede"],
    construction: [],
    applications: [],
    source:
      "fabrics-2027.md — Part 2 §2.2, bullet “Real suede and leather — plus opulent calf-hair finishes”",
  },
  {
    id: "fs-fabric-2027-094",
    slug: "real-leather",
    name: "Real Leather",
    family: "suede-touch-and-dry-hand",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Leather"],
    construction: [],
    applications: [],
    source:
      "fabrics-2027.md — Part 2 §2.2, bullet “Real suede and leather — plus opulent calf-hair finishes”",
  },
  {
    id: "fs-fabric-2027-095",
    slug: "calf-hair-finish",
    name: "Calf-Hair Finish",
    family: "suede-touch-and-dry-hand",
    collection: "aw-textures",
    seasons: ["AW 27/28"],
    composition: ["Calf hair"],
    construction: [],
    characteristics: ["Opulent finish"],
    applications: [],
    source:
      "fabrics-2027.md — Part 2 §2.2, bullet “Real suede and leather — plus opulent calf-hair finishes”",
  },
  {
    id: "fs-fabric-2027-049",
    slug: "fine-wale-corduroy",
    name: "Fine-Wale Corduroy",
    family: "corduroy-velvet-and-pile",
    collection: "velvet-pile",
    seasons: ["AW 27/28"],
    measurements: [
      { unit: "wale", min: 16, max: 21 },
      { unit: "gsm", min: 280, max: 340 },
    ],
    construction: ["Fine-wale corduroy"],
    applications: ["shirting", "trousers"],
    source: "fabrics-2027.md — Part 2 §2.3, table row “Fine-wale corduroy”",
  },
  {
    id: "fs-fabric-2027-050",
    slug: "jumbo-corduroy",
    name: "Jumbo Corduroy",
    family: "corduroy-velvet-and-pile",
    collection: "velvet-pile",
    seasons: ["AW 27/28"],
    measurements: [
      { unit: "wale", min: 4, max: 8 },
      { unit: "gsm", min: 350, max: 450 },
    ],
    construction: ["Jumbo cord"],
    applications: ["outerwear", "trousers"],
    source: "fabrics-2027.md — Part 2 §2.3, table row “Jumbo cord”",
  },
  {
    id: "fs-fabric-2027-051",
    slug: "cotton-velveteen",
    name: "Cotton Velveteen",
    family: "corduroy-velvet-and-pile",
    collection: "velvet-pile",
    seasons: ["AW 27/28"],
    composition: ["Cotton"],
    construction: ["Short, dense pile"],
    characteristics: ["Matte"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.3, table row “Cotton velveteen”",
  },
  {
    id: "fs-fabric-2027-052",
    slug: "silk-viscose-velvet",
    name: "Silk–Viscose Velvet",
    family: "corduroy-velvet-and-pile",
    collection: "velvet-pile",
    seasons: ["AW 27/28"],
    composition: ["Silk and viscose"],
    characteristics: ["Fluid", "Lustrous"],
    applications: ["occasionwear", "interiors"],
    source: "fabrics-2027.md — Part 2 §2.3, table row “Silk-viscose velvet”",
  },
  {
    id: "fs-fabric-2027-053",
    slug: "crushed-velvet",
    name: "Crushed Velvet",
    family: "corduroy-velvet-and-pile",
    collection: "velvet-pile",
    seasons: ["AW 27/28"],
    characteristics: ["Directional pile", "Irregular light"],
    applications: [],
    source:
      "fabrics-2027.md — Part 2 §2.3, table row “Crushed and panné velvet”",
  },
  {
    id: "fs-fabric-2027-054",
    slug: "panne-velvet",
    name: "Panné Velvet",
    family: "corduroy-velvet-and-pile",
    collection: "velvet-pile",
    seasons: ["AW 27/28"],
    characteristics: ["Directional pile", "Irregular light"],
    applications: [],
    source:
      "fabrics-2027.md — Part 2 §2.3, table row “Crushed and panné velvet”",
  },
  {
    id: "fs-fabric-2027-055",
    slug: "herringbone-tweed",
    name: "Herringbone Tweed",
    family: "structured-classics",
    collection: "structured-classics",
    seasons: ["AW 27/28"],
    construction: ["Herringbone"],
    characteristics: ["Bigger repeats", "Brighter neps"],
    applications: [],
    source:
      "fabrics-2027.md — Part 2 §2.4, bullet “Herringbone and Donegal tweed”",
  },
  {
    id: "fs-fabric-2027-056",
    slug: "donegal-tweed",
    name: "Donegal Tweed",
    family: "structured-classics",
    collection: "structured-classics",
    seasons: ["AW 27/28"],
    construction: ["Donegal tweed"],
    characteristics: ["Bigger repeats", "Brighter neps"],
    applications: [],
    source:
      "fabrics-2027.md — Part 2 §2.4, bullet “Herringbone and Donegal tweed”",
  },
  {
    id: "fs-fabric-2027-057",
    slug: "tartan",
    name: "Tartan",
    family: "structured-classics",
    collection: "structured-classics",
    seasons: ["AW 27/28"],
    characteristics: ["Oversized scale", "Off-register colour"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.4, bullet “Tartan and check”",
  },
  {
    id: "fs-fabric-2027-058",
    slug: "check",
    name: "Check",
    family: "structured-classics",
    collection: "structured-classics",
    seasons: ["AW 27/28"],
    characteristics: ["Oversized scale", "Off-register colour"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.4, bullet “Tartan and check”",
  },
  {
    id: "fs-fabric-2027-059",
    slug: "membrane-backed-gabardine",
    name: "Membrane-Backed Gabardine",
    family: "structured-classics",
    collection: "structured-classics",
    seasons: ["AW 27/28"],
    composition: ["Technical wool"],
    construction: ["Gabardine", "Membrane backing"],
    applications: ["city-outerwear"],
    source: "fabrics-2027.md — Part 2 §2.4, bullet “Gabardine and covert”",
  },
  {
    id: "fs-fabric-2027-060",
    slug: "membrane-backed-covert",
    name: "Membrane-Backed Covert",
    family: "structured-classics",
    collection: "structured-classics",
    seasons: ["AW 27/28"],
    composition: ["Technical wool"],
    construction: ["Covert", "Membrane backing"],
    applications: ["city-outerwear"],
    source: "fabrics-2027.md — Part 2 §2.4, bullet “Gabardine and covert”",
  },
  {
    id: "fs-fabric-2027-061",
    slug: "deconstructed-jacquard",
    name: "Deconstructed Jacquard",
    family: "structured-classics",
    collection: "structured-classics",
    seasons: ["AW 27/28"],
    construction: ["Jacquard"],
    characteristics: ["Broken, blurred or partially rendered motifs"],
    applications: [],
    source:
      "fabrics-2027.md — Part 2 §2.4, bullet “Jacquard and damask deconstruction”",
  },
  {
    id: "fs-fabric-2027-062",
    slug: "deconstructed-damask",
    name: "Deconstructed Damask",
    family: "structured-classics",
    collection: "structured-classics",
    seasons: ["AW 27/28"],
    construction: ["Damask"],
    characteristics: ["Broken, blurred or partially rendered motifs"],
    applications: [],
    source:
      "fabrics-2027.md — Part 2 §2.4, bullet “Jacquard and damask deconstruction”",
  },
  {
    id: "fs-fabric-2027-063",
    slug: "recycled-nylon-ripstop",
    name: "Recycled Nylon Ripstop",
    family: "technical-outerwear",
    collection: "technical-outerwear",
    seasons: ["AW 27/28"],
    composition: ["Recycled nylon"],
    measurements: [{ unit: "denier", min: 40, max: 90 }],
    construction: ["Ripstop"],
    characteristics: ["PFAS-free DWR"],
    applications: ["outerwear"],
    source: "fabrics-2027.md — Part 2 §2.5, bullet “Recycled nylon ripstop”",
  },
  {
    id: "fs-fabric-2027-064",
    slug: "two-layer-membrane-laminate",
    name: "2L Membrane Laminate",
    family: "technical-outerwear",
    collection: "technical-outerwear",
    seasons: ["AW 27/28"],
    construction: ["2-layer membrane laminate"],
    characteristics: ["Membrane specified for PFAS compliance"],
    applications: ["outerwear"],
    source: "fabrics-2027.md — Part 2 §2.5, bullet “Membrane laminates”",
  },
  {
    id: "fs-fabric-2027-065",
    slug: "two-point-five-layer-membrane-laminate",
    name: "2.5L Membrane Laminate",
    family: "technical-outerwear",
    collection: "technical-outerwear",
    seasons: ["AW 27/28"],
    construction: ["2.5-layer membrane laminate"],
    characteristics: ["Membrane specified for PFAS compliance"],
    applications: ["outerwear"],
    source: "fabrics-2027.md — Part 2 §2.5, bullet “Membrane laminates”",
  },
  {
    id: "fs-fabric-2027-066",
    slug: "three-layer-membrane-laminate",
    name: "3L Membrane Laminate",
    family: "technical-outerwear",
    collection: "technical-outerwear",
    seasons: ["AW 27/28"],
    construction: ["3-layer membrane laminate"],
    characteristics: ["Membrane specified for PFAS compliance"],
    applications: ["outerwear"],
    source: "fabrics-2027.md — Part 2 §2.5, bullet “Membrane laminates”",
  },
  {
    id: "fs-fabric-2027-067",
    slug: "wool-technical-hybrid",
    name: "Wool–Technical Hybrid",
    family: "technical-outerwear",
    collection: "technical-outerwear",
    seasons: ["AW 27/28"],
    composition: ["Wool face / membrane middle / mesh back"],
    construction: ["Three-part hybrid"],
    applications: ["outerwear"],
    source: "fabrics-2027.md — Part 2 §2.5, bullet “Wool-technical hybrids”",
  },
  {
    id: "fs-fabric-2027-068",
    slug: "down-alternative-fill",
    name: "Down-Alternative Fill",
    family: "technical-outerwear",
    collection: "technical-outerwear",
    seasons: ["AW 27/28"],
    construction: ["Insulating fill"],
    applications: ["garment-insulation"],
    source:
      "fabrics-2027.md — Part 2 §2.5, bullet “Down-alternative fills and recycled polyester wadding”",
  },
  {
    id: "fs-fabric-2027-069",
    slug: "recycled-polyester-wadding",
    name: "Recycled Polyester Wadding",
    family: "technical-outerwear",
    collection: "technical-outerwear",
    seasons: ["AW 27/28"],
    composition: ["Recycled polyester"],
    construction: ["Wadding"],
    applications: ["garment-insulation"],
    source:
      "fabrics-2027.md — Part 2 §2.5, bullet “Down-alternative fills and recycled polyester wadding”",
  },
  {
    id: "fs-fabric-2027-070",
    slug: "lightweight-denim",
    name: "Lightweight Denim",
    family: "denim-2027",
    collection: "denim",
    seasons: ["AW 27/28"],
    measurements: [{ unit: "oz/yd²", min: 8, max: 11 }],
    characteristics: ["Volume-market weight"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.6, bullet “Lighter weights continue”",
  },
  {
    id: "fs-fabric-2027-071",
    slug: "premium-weight-denim",
    name: "Premium-Weight Denim",
    family: "denim-2027",
    collection: "denim",
    seasons: ["AW 27/28"],
    measurements: [{ unit: "oz/yd²", min: 12, max: 14 }],
    characteristics: ["Premium-market weight"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.6, bullet “Lighter weights continue”",
  },
  {
    id: "fs-fabric-2027-072",
    slug: "recycled-cotton-denim",
    name: "Recycled-Cotton Denim",
    family: "denim-2027",
    collection: "denim",
    seasons: ["AW 27/28"],
    composition: ["20–40% recycled cotton blended with virgin cotton"],
    characteristics: ["Virgin cotton retained for strength"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.6, bullet “Recycled cotton content”",
  },
  {
    id: "fs-fabric-2027-073",
    slug: "laser-and-ozone-finished-denim",
    name: "Laser- and Ozone-Finished Denim",
    family: "denim-2027",
    collection: "denim",
    seasons: ["AW 27/28"],
    characteristics: [
      "Laser finished",
      "Ozone finished",
      "Replaces stonewash and hand-sanding",
    ],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.6, bullet “Laser and ozone finishing”",
  },
  {
    id: "fs-fabric-2027-074",
    slug: "hemp-cotton-denim",
    name: "Hemp–Cotton Denim",
    family: "denim-2027",
    collection: "denim",
    seasons: ["AW 27/28"],
    composition: ["15–30% hemp with cotton"],
    characteristics: ["Hemp hand feel"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.6, bullet “Hemp-cotton denim”",
  },
  {
    id: "fs-fabric-2027-075",
    slug: "selvedge-rigid-denim",
    name: "Selvedge Rigid Denim",
    family: "denim-2027",
    collection: "denim",
    seasons: ["AW 27/28"],
    construction: ["Selvedge", "Rigid"],
    characteristics: ["Heritage", "Longevity-led"],
    applications: [],
    source: "fabrics-2027.md — Part 2 §2.6, bullet “Selvedge and rigid”",
  },
  {
    id: "fs-fabric-2027-076",
    slug: "upholstery-boucle",
    name: "Upholstery Bouclé",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    construction: ["Bouclé"],
    applications: ["upholstery"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Upholstery row",
  },
  {
    id: "fs-fabric-2027-077",
    slug: "heavy-linen-upholstery",
    name: "Heavy Linen Upholstery",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Linen"],
    characteristics: ["Heavy"],
    applications: ["upholstery"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Upholstery row",
  },
  {
    id: "fs-fabric-2027-078",
    slug: "wool-felt-upholstery",
    name: "Wool Felt Upholstery",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Wool"],
    construction: ["Felt"],
    applications: ["upholstery"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Upholstery row",
  },
  {
    id: "fs-fabric-2027-079",
    slug: "performance-upholstery-weave",
    name: "Performance Upholstery Weave",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    measurements: [{ unit: "Martindale", min: 40000, qualifier: "40,000+" }],
    construction: ["Performance weave"],
    applications: ["upholstery"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Upholstery row",
  },
  {
    id: "fs-fabric-2027-080",
    slug: "open-weave-linen-curtain",
    name: "Open-Weave Linen Curtain",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Linen"],
    construction: ["Open weave"],
    applications: ["curtains", "sheers"],
    source:
      "fabrics-2027.md — Part 4, “Fabrics that follow”, Curtain and sheer row",
  },
  {
    id: "fs-fabric-2027-081",
    slug: "technical-voile",
    name: "Technical Voile",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    construction: ["Voile"],
    applications: ["curtains", "sheers"],
    source:
      "fabrics-2027.md — Part 4, “Fabrics that follow”, Curtain and sheer row",
  },
  {
    id: "fs-fabric-2027-082",
    slug: "acoustic-rated-drape",
    name: "Acoustic-Rated Drape",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    characteristics: ["Acoustic-rated"],
    applications: ["acoustic-drapes"],
    source:
      "fabrics-2027.md — Part 4, “Fabrics that follow”, Curtain and sheer row",
  },
  {
    id: "fs-fabric-2027-083",
    slug: "long-staple-cotton-percale",
    name: "Long-Staple Cotton Percale",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Long-staple cotton"],
    construction: ["Percale"],
    applications: ["bedding"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Bedding row",
  },
  {
    id: "fs-fabric-2027-084",
    slug: "long-staple-cotton-sateen",
    name: "Long-Staple Cotton Sateen",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Long-staple cotton"],
    construction: ["Sateen"],
    applications: ["bedding"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Bedding row",
  },
  {
    id: "fs-fabric-2027-085",
    slug: "washed-linen-bedding",
    name: "Washed Linen Bedding",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Linen"],
    characteristics: ["Washed"],
    applications: ["bedding"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Bedding row",
  },
  {
    id: "fs-fabric-2027-086",
    slug: "lyocell-blend-bedding",
    name: "Lyocell-Blend Bedding",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Lyocell blend"],
    applications: ["bedding"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Bedding row",
  },
  {
    id: "fs-fabric-2027-087",
    slug: "undyed-wool-rug",
    name: "Undyed Wool Rug",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Wool"],
    characteristics: ["Undyed"],
    applications: ["rugs"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Rugs row",
  },
  {
    id: "fs-fabric-2027-088",
    slug: "jute-rug",
    name: "Jute Rug",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Jute"],
    applications: ["rugs"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Rugs row",
  },
  {
    id: "fs-fabric-2027-089",
    slug: "recycled-pet-pile-rug",
    name: "Recycled PET Pile Rug",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Recycled PET"],
    construction: ["Pile"],
    applications: ["rugs"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Rugs row",
  },
  {
    id: "fs-fabric-2027-090",
    slug: "inherently-fr-polyester",
    name: "Inherently FR Polyester",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Polyester"],
    characteristics: ["Inherently flame resistant"],
    applications: ["contract-textiles"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Contract row",
  },
  {
    id: "fs-fabric-2027-091",
    slug: "bleach-cleanable-vinyl-alternative",
    name: "Bleach-Cleanable Vinyl Alternative",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    characteristics: ["Bleach-cleanable"],
    applications: ["contract-textiles"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Contract row",
  },
  {
    id: "fs-fabric-2027-092",
    slug: "recycled-pet-acoustic-felt",
    name: "Recycled PET Acoustic Felt",
    family: "home-and-contract",
    collection: "home-contract",
    seasons: ["Home & Contract 27/28"],
    composition: ["Recycled PET"],
    construction: ["Acoustic felt"],
    applications: ["contract-textiles"],
    source: "fabrics-2027.md — Part 4, “Fabrics that follow”, Contract row",
  },
  ...EXPANDED_FABRICS,
  ...EXPANDED_COTTON_FABRICS,
  ...EXPANDED_JERSEY_CELLULOSIC_WOOL,
] as const satisfies readonly CatalogProduct[];

export type Fabric2027 = (typeof FABRICS_2027)[number];
export type Fabric2027Slug = Fabric2027["slug"];

export const FABRIC_2027_BY_SLUG = Object.fromEntries(
  FABRICS_2027.map((fabric) => [fabric.slug, fabric]),
) as Record<Fabric2027Slug, Fabric2027>;

function duplicates(values: readonly string[]): string[] {
  const seen = new Set<string>();
  const duplicatesFound = new Set<string>();

  for (const value of values) {
    if (seen.has(value)) {
      duplicatesFound.add(value);
    }
    seen.add(value);
  }

  return [...duplicatesFound];
}

function assertNoDuplicates(label: string, values: readonly string[]): void {
  const duplicatesFound = duplicates(values);
  if (duplicatesFound.length > 0) {
    throw new Error(
      `Invalid 2027 catalog: duplicate ${label}: ${duplicatesFound.join(", ")}`,
    );
  }
}

export function assertCatalog2027Integrity(): void {
  if (FABRICS_2027.length !== 199) {
    throw new Error(
      `Invalid 2027 catalog: expected 199 products, found ${FABRICS_2027.length}`,
    );
  }
  assertNoDuplicates(
    "product IDs",
    FABRICS_2027.map((fabric) => fabric.id),
  );
  assertNoDuplicates(
    "product slugs",
    FABRICS_2027.map((fabric) => fabric.slug),
  );
  assertNoDuplicates(
    "product names",
    FABRICS_2027.map((fabric) => fabric.name.toLocaleLowerCase("en")),
  );
  assertNoDuplicates(
    "canonical names and aliases",
    FABRICS_2027.flatMap((fabric) => [
      fabric.name.toLocaleLowerCase("en"),
      ...("aliases" in fabric
        ? (fabric.aliases ?? []).map((alias) => alias.toLocaleLowerCase("en"))
        : []),
    ]),
  );
  assertNoDuplicates(
    "collection slugs",
    COLLECTIONS.map((collection) => collection.slug),
  );
  assertNoDuplicates(
    "family slugs",
    SOURCE_FAMILIES.map((family) => family.slug),
  );
  assertNoDuplicates(
    "Best For slugs",
    BEST_FOR.map((application) => application.slug),
  );

  if (COLLECTIONS.length !== 12) {
    throw new Error(
      `Invalid 2027 catalog: expected 12 collections, found ${COLLECTIONS.length}`,
    );
  }
  if (SOURCE_FAMILIES.length !== 13) {
    throw new Error(
      `Invalid 2027 catalog: expected 13 source families, found ${SOURCE_FAMILIES.length}`,
    );
  }

  const productSlugs = new Set(FABRICS_2027.map((fabric) => fabric.slug));

  for (const fabric of FABRICS_2027) {
    if (!fabric.source.trim()) {
      throw new Error(
        `Invalid 2027 catalog: ${fabric.slug} has no source provenance`,
      );
    }
    if (!(fabric.collection in COLLECTION_BY_SLUG)) {
      throw new Error(
        `Invalid 2027 catalog: ${fabric.slug} uses unknown collection ${fabric.collection}`,
      );
    }
    if (!(fabric.family in SOURCE_FAMILY_BY_SLUG)) {
      throw new Error(
        `Invalid 2027 catalog: ${fabric.slug} uses unknown family ${fabric.family}`,
      );
    }
    for (const application of fabric.applications) {
      if (!(application in BEST_FOR_BY_SLUG)) {
        throw new Error(
          `Invalid 2027 catalog: ${fabric.slug} uses unknown Best For value ${application}`,
        );
      }
    }

    const media: FabricMedia | undefined = MEDIA_BY_FABRIC_SLUG[fabric.slug];
    if (!media) {
      throw new Error(
        `Invalid 2027 catalog: ${fabric.slug} has no media registry entry`,
      );
    }
    if (media.status === "placeholder" && media.src !== undefined) {
      throw new Error(
        `Invalid 2027 catalog: placeholder media for ${fabric.slug} must not have src`,
      );
    }
    if (media.status !== "placeholder" && !media.src) {
      throw new Error(
        `Invalid 2027 catalog: ${media.status} media for ${fabric.slug} requires src`,
      );
    }
  }

  for (const mediaSlug of Object.keys(MEDIA_BY_FABRIC_SLUG)) {
    if (!productSlugs.has(mediaSlug as Fabric2027Slug)) {
      throw new Error(
        `Invalid 2027 catalog: media entry ${mediaSlug} has no catalog product`,
      );
    }
  }
}

assertCatalog2027Integrity();
