import type { FabricMedia } from "./types";

export const MEDIA_BY_FABRIC_SLUG: Record<string, FabricMedia> = {
  "european-flax-linen": {
    status: "final",
    src: "/media/fabrics/european-flax-linen-primary.webp",
    alt: "European flax linen with a natural irregular plain weave",
  },
  "linen-cotton": {
    status: "final",
    src: "/media/fabrics/linen-cotton-primary.webp",
    alt: "Linen-cotton blend fabric with a balanced plain weave",
  },
  "linen-silk": {
    status: "final",
    src: "/media/fabrics/linen-silk-primary.webp",
    alt: "Linen-silk blend with a soft sheen and fine natural texture",
  },
  "linen-viscose": {
    status: "final",
    src: "/media/fabrics/linen-viscose-primary.webp",
    alt: "Drapey linen-viscose blend fabric in soft natural folds",
  },
  "linen-lyocell": {
    status: "final",
    src: "/media/fabrics/linen-lyocell-primary.webp",
    alt: "Soft lavender linen-lyocell blend with fluid drape",
  },
  "cotton-poplin": {
    status: "final",
    src: "/media/fabrics/cotton-poplin-primary.webp",
    alt: "Crisp fine-count cotton poplin fabric in soft folds",
  },
  "cotton-voile": {
    status: "final",
    src: "/media/fabrics/cotton-voile-primary.webp",
    alt: "Lightweight translucent cotton voile fabric",
  },
  "cotton-organdy": {
    status: "final",
    src: "/media/fabrics/cotton-organdy-primary.webp",
    alt: "Stiff sheer cotton organdy holding sculptural volume",
  },
  "cotton-boucle-yarn": {
    status: "final",
    src: "/media/fabrics/cotton-boucle-yarn-primary.webp",
    alt: "Textured cotton bouclé yarn fabric with looped surface",
  },
  "cotton-seersucker": {
    status: "final",
    src: "/media/fabrics/cotton-seersucker-primary.webp",
    alt: "Puckered cotton seersucker fabric in pale blue stripes",
  },
  "crinkle-cotton": {
    status: "final",
    src: "/media/fabrics/crinkle-cotton-primary.webp",
    alt: "Dusty rose crinkle cotton with an irregular puckered surface",
  },
  "slub-cotton": {
    status: "final",
    src: "/media/fabrics/slub-cotton-primary.webp",
    alt: "Olive slub cotton with irregular thick yarn texture",
  },
  "khadi-effect-cotton": {
    status: "final",
    src: "/media/fabrics/khadi-effect-cotton-primary.webp",
    alt: "Indigo khadi-effect cotton with handwoven irregular texture",
  },
  "silk-chiffon": {
    status: "final",
    src: "/media/fabrics/silk-chiffon-primary.webp",
    alt: "Deep burgundy transparent silk chiffon in fluid folds",
  },
  "silk-georgette": {
    status: "final",
    src: "/media/fabrics/silk-georgette-primary.webp",
    alt: "Muted teal silk georgette with a fine crepe surface",
  },
  "silk-organza": {
    status: "final",
    src: "/media/fabrics/silk-organza-primary.webp",
    alt: "Champagne silk organza with crisp transparent volume",
  },
  "silk-taffeta": {
    status: "final",
    src: "/media/fabrics/silk-taffeta-primary.webp",
    alt: "Deep plum silk taffeta with structured reflective folds",
  },
  "crepe-de-chine": {
    status: "final",
    src: "/media/fabrics/crepe-de-chine-primary.webp",
    alt: "Cobalt blue silk crepe de chine with a fine matte texture",
  },
  "silk-habotai": {
    status: "final",
    src: "/media/fabrics/silk-habotai-primary.webp",
    alt: "Forest green smooth silk habotai in fluid folds",
  },
  "silk-dupion": {
    status: "final",
    src: "/media/fabrics/silk-dupion-primary.webp",
    alt: "Deep navy silk dupion with pronounced slubbed texture",
  },
  "silk-boucle": {
    status: "final",
    src: "/media/fabrics/silk-boucle-primary.webp",
    alt: "Silk bouclé with dense irregular looped yarns and a subtle tonal sheen",
  },
  "merino-roica-stretch-tailoring": {
    status: "final",
    src: "/media/fabrics/merino-roica-stretch-tailoring-primary.webp",
    alt: "Fine merino tailoring cloth with a compact structured stretch weave",
  },
  "wool-silk-bi-stretch": {
    status: "final",
    src: "/media/fabrics/wool-silk-bi-stretch-primary.webp",
    alt: "Wool-silk bi-stretch tailoring cloth with a fine resilient weave",
  },
  "wool-linen-open-weave": {
    status: "final",
    src: "/media/fabrics/wool-linen-open-weave-primary.webp",
    alt: "Wool-linen open weave with coarse breathable yarn spacing",
  },
  "wool-mohair-open-weave": {
    status: "final",
    src: "/media/fabrics/wool-mohair-open-weave-primary.webp",
    alt: "Wool-mohair open weave with airy gaps and a fine fiber halo",
  },
  "tropical-wool-super-110s-130s": {
    status: "final",
    src: "/media/fabrics/tropical-wool-super-110s-130s-primary.webp",
    alt: "Fine tropical worsted wool with a crisp breathable tailoring weave",
  },
  "open-stitch-knit": {
    status: "final",
    src: "/media/fabrics/open-stitch-knit-primary.webp",
    alt: "Open-stitch knit with visible looped yarns and airy ladder-like gaps",
  },
  "pointelle-knit": {
    status: "final",
    src: "/media/fabrics/pointelle-knit-primary.webp",
    alt: "Pointelle knit with fine loops and repeated decorative eyelets",
  },
  "crochet-effect-knit": {
    status: "final",
    src: "/media/fabrics/crochet-effect-knit-primary.webp",
    alt: "Crochet-effect knit with chunky interlocking cotton loops",
  },
  "fine-gauge-semi-sheer-knit": {
    status: "final",
    src: "/media/fabrics/fine-gauge-semi-sheer-knit-primary.webp",
    alt: "Fine-gauge semi-sheer knit with delicate close-loop construction",
  },
  "cotton-boucle-knit": {
    status: "final",
    src: "/media/fabrics/cotton-boucle-knit-primary.webp",
    alt: "Cotton bouclé knit with a matte looped staple-fiber surface",
  },
  "linen-boucle-knit": {
    status: "final",
    src: "/media/fabrics/linen-boucle-knit-primary.webp",
    alt: "Linen bouclé knit with nubby flax loops and a breathable matte surface",
  },
  "lightweight-merino-knit": {
    status: "final",
    src: "/media/fabrics/lightweight-merino-knit-primary.webp",
    alt: "Lightweight merino knit with fine loops and a soft natural wool halo",
  },
  "stretch-woven-compression": {
    status: "final",
    src: "/media/fabrics/stretch-woven-compression-primary.webp",
    alt: "Dense stretch-woven compression fabric with a fine technical grid",
  },
  "crossover-swimwear-fabric": {
    status: "final",
    src: "/media/fabrics/crossover-swimwear-fabric-primary.webp",
    alt: "Compact resilient swimwear fabric with a fine technical knit surface",
  },
  "cooling-performance-construction": {
    status: "final",
    src: "/media/fabrics/cooling-performance-construction-primary.webp",
    alt: "Cooling performance fabric with breathable micro-mesh channels",
  },
  "ultra-light-semi-sheer-lounge-knit": {
    status: "final",
    src: "/media/fabrics/ultra-light-semi-sheer-lounge-knit-primary.webp",
    alt: "Ultra-light semi-sheer lounge knit with airy open loops",
  },
  "retro-sportif-knit": {
    status: "final",
    src: "/media/fabrics/retro-sportif-knit-primary.webp",
    alt: "Retro sportif knit with compact jersey stitches and coordinated stripes",
  },
  melton: {
    status: "final",
    src: "/media/fabrics/melton-primary.webp",
    alt: "Dense fulled melton wool with a short compact nap and firm body",
  },
  "boiled-wool": {
    status: "final",
    src: "/media/fabrics/boiled-wool-primary.webp",
    alt: "Boiled wool with a dense felted fiber surface and stable body",
  },
  "double-face-wool": {
    status: "final",
    src: "/media/fabrics/double-face-wool-primary.webp",
    alt: "Double-face wool with contrasting charcoal and rust reversible faces",
  },
  "brushed-flannel": {
    status: "final",
    src: "/media/fabrics/brushed-flannel-primary.webp",
    alt: "Brushed flannel with raised nap and a muted burgundy plaid",
  },
  "mohair-blend": {
    status: "final",
    src: "/media/fabrics/mohair-blend-primary.webp",
    alt: "Mohair blend with an airy woven surface and visible long fiber halo",
  },
  "alpaca-blend": {
    status: "final",
    src: "/media/fabrics/alpaca-blend-primary.webp",
    alt: "Alpaca blend with a soft lofty nap and warm natural fiber halo",
  },
  "casentino-wool": {
    status: "final",
    src: "/media/fabrics/casentino-wool-primary.webp",
    alt: "Casentino wool with a dense characteristic curly felted nap",
  },
  "cotton-moleskin": {
    status: "final",
    src: "/media/fabrics/cotton-moleskin-primary.webp",
    alt: "Cotton moleskin with a dense short brushed nap and firm body",
  },
  "peach-skin": {
    status: "final",
    src: "/media/fabrics/peach-skin-primary.webp",
    alt: "Peach-skin woven fabric with a fine short sueded nap",
  },
  "suede-effect-woven": {
    status: "final",
    src: "/media/fabrics/suede-effect-woven-primary.webp",
    alt: "Suede-effect woven fabric with a uniform short brushed textile nap",
  },
  "real-suede": {
    status: "final",
    src: "/media/fabrics/real-suede-primary.webp",
    alt: "Real suede hide with a soft natural nap and supple weighty folds",
  },
  "real-leather": {
    status: "final",
    src: "/media/fabrics/real-leather-primary.webp",
    alt: "Full-grain real leather with natural pores and a supple hide surface",
  },
  "calf-hair-finish": {
    status: "final",
    src: "/media/fabrics/calf-hair-finish-primary.webp",
    alt: "Calf-hair finish leather with a short natural directional hair coat",
  },
  "fine-wale-corduroy": {
    status: "final",
    src: "/media/fabrics/fine-wale-corduroy-primary.webp",
    alt: "Fine-wale corduroy with many narrow raised cotton pile ribs",
  },
  "jumbo-corduroy": {
    status: "final",
    src: "/media/fabrics/jumbo-corduroy-primary.webp",
    alt: "Jumbo corduroy with very wide raised cotton pile wales",
  },
  "cotton-velveteen": {
    status: "final",
    src: "/media/fabrics/cotton-velveteen-primary.webp",
    alt: "Cotton velveteen with dense short directional pile",
  },
  "silk-viscose-velvet": {
    status: "final",
    src: "/media/fabrics/silk-viscose-velvet-primary.webp",
    alt: "Silk-viscose velvet with a dense luminous directional pile",
  },
  "crushed-velvet": {
    status: "final",
    src: "/media/fabrics/crushed-velvet-primary.webp",
    alt: "Crushed velvet with irregular directional pile and burgundy highlights",
  },
  "panne-velvet": {
    status: "final",
    src: "/media/fabrics/panne-velvet-primary.webp",
    alt: "Panné velvet with a flattened reflective teal pile",
  },
  "herringbone-tweed": {
    status: "final",
    src: "/media/fabrics/herringbone-tweed-primary.webp",
    alt: "Herringbone tweed with raised wool V-shaped twill and mixed yarns",
  },
  "donegal-tweed": {
    status: "final",
    src: "/media/fabrics/donegal-tweed-primary.webp",
    alt: "Donegal tweed with irregular colored wool nep flecks",
  },
  tartan: {
    status: "final",
    src: "/media/fabrics/tartan-primary.webp",
    alt: "Woven wool tartan with burgundy, green, navy and cream bands",
  },
  check: {
    status: "final",
    src: "/media/fabrics/check-primary.webp",
    alt: "Woven check fabric with intersecting cobalt, cream and rust bands",
  },
  "membrane-backed-gabardine": {
    status: "final",
    src: "/media/fabrics/membrane-backed-gabardine-primary.webp",
    alt: "Membrane-backed gabardine with dense diagonal technical twill",
  },
  "membrane-backed-covert": {
    status: "final",
    src: "/media/fabrics/membrane-backed-covert-primary.webp",
    alt: "Membrane-backed covert with a compact technical twill and layered edge",
  },
  "deconstructed-jacquard": {
    status: "final",
    src: "/media/fabrics/deconstructed-jacquard-primary.webp",
    alt: "Deconstructed jacquard with raised abstract woven motif relief",
  },
  "deconstructed-damask": {
    status: "final",
    src: "/media/fabrics/deconstructed-damask-primary.webp",
    alt: "Deconstructed damask with contrasting raised woven motifs",
  },
  "recycled-nylon-ripstop": {
    status: "final",
    src: "/media/fabrics/recycled-nylon-ripstop-primary.webp",
    alt: "Recycled nylon ripstop with a reinforced square grid",
  },
  "two-layer-membrane-laminate": {
    status: "final",
    src: "/media/fabrics/two-layer-membrane-laminate-primary.webp",
    alt: "Two-layer membrane laminate with a face fabric and continuous membrane",
  },
  "two-point-five-layer-membrane-laminate": {
    status: "final",
    src: "/media/fabrics/two-point-five-layer-membrane-laminate-primary.webp",
    alt: "Two-and-a-half-layer membrane laminate with technical face and protective layer",
  },
  "three-layer-membrane-laminate": {
    status: "final",
    src: "/media/fabrics/three-layer-membrane-laminate-primary.webp",
    alt: "Three-layer membrane laminate with face, membrane and protective backer",
  },
  "wool-technical-hybrid": {
    status: "final",
    src: "/media/fabrics/wool-technical-hybrid-primary.webp",
    alt: "Wool-technical hybrid combining a natural wool face and performance backing",
  },
  "down-alternative-fill": {
    status: "final",
    src: "/media/fabrics/down-alternative-fill-primary.webp",
    alt: "Down-alternative fill showing soft lofted synthetic staple fibers",
  },
  "recycled-polyester-wadding": {
    status: "final",
    src: "/media/fabrics/recycled-polyester-wadding-primary.webp",
    alt: "Recycled polyester wadding with an airy nonwoven staple-fiber web",
  },
  "lightweight-denim": {
    status: "final",
    src: "/media/fabrics/lightweight-denim-primary.webp",
    alt: "Lightweight blue cotton denim with a fine diagonal twill",
  },
  "premium-weight-denim": {
    status: "final",
    src: "/media/fabrics/premium-weight-denim-primary.webp",
    alt: "Dense dark indigo premium-weight denim with pronounced twill",
  },
  "recycled-cotton-denim": {
    status: "final",
    src: "/media/fabrics/recycled-cotton-denim-primary.webp",
    alt: "Washed blue recycled-cotton denim with authentic diagonal twill",
  },
  "laser-and-ozone-finished-denim": {
    status: "final",
    src: "/media/fabrics/laser-and-ozone-finished-denim-primary.webp",
    alt: "Laser- and ozone-finished denim with controlled tonal fading",
  },
  "hemp-cotton-denim": {
    status: "final",
    src: "/media/fabrics/hemp-cotton-denim-primary.webp",
    alt: "Indigo hemp-cotton denim with dry natural slubs",
  },
  "selvedge-rigid-denim": {
    status: "final",
    src: "/media/fabrics/selvedge-rigid-denim-primary.webp",
    alt: "Raw indigo selvedge rigid denim with a red-and-white edge",
  },
  "upholstery-boucle": {
    status: "final",
    src: "/media/fabrics/upholstery-boucle-primary.webp",
    alt: "Dense ivory upholstery bouclé with irregular looped yarns",
  },
  "heavy-linen-upholstery": {
    status: "final",
    src: "/media/fabrics/heavy-linen-upholstery-primary.webp",
    alt: "Heavy oat linen upholstery with a dense irregular plain weave",
  },
  "wool-felt-upholstery": {
    status: "final",
    src: "/media/fabrics/wool-felt-upholstery-primary.webp",
    alt: "Charcoal wool felt upholstery with a dense compact fiber surface",
  },
  "performance-upholstery-weave": {
    status: "final",
    src: "/media/fabrics/performance-upholstery-weave-primary.webp",
    alt: "Slate performance upholstery with a compact basketweave grid",
  },
  "open-weave-linen-curtain": {
    status: "final",
    src: "/media/fabrics/open-weave-linen-curtain-primary.webp",
    alt: "Open-weave ecru linen curtain fabric with airy yarn spacing",
  },
  "technical-voile": {
    status: "final",
    src: "/media/fabrics/technical-voile-primary.webp",
    alt: "Pale grey technical voile with a stable translucent weave",
  },
  "acoustic-rated-drape": {
    status: "final",
    src: "/media/fabrics/acoustic-rated-drape-primary.webp",
    alt: "Dense charcoal acoustic drape fabric with substantial folds",
  },
  "long-staple-cotton-percale": {
    status: "final",
    src: "/media/fabrics/long-staple-cotton-percale-primary.webp",
    alt: "White long-staple cotton percale with a crisp matte weave",
  },
  "long-staple-cotton-sateen": {
    status: "final",
    src: "/media/fabrics/long-staple-cotton-sateen-primary.webp",
    alt: "Ivory long-staple cotton sateen with a restrained surface sheen",
  },
  "washed-linen-bedding": {
    status: "final",
    src: "/media/fabrics/washed-linen-bedding-primary.webp",
    alt: "Stone washed linen bedding with softened natural slubs",
  },
  "lyocell-blend-bedding": {
    status: "final",
    src: "/media/fabrics/lyocell-blend-bedding-primary.webp",
    alt: "Eucalyptus lyocell-blend bedding with a smooth fluid weave",
  },
  "undyed-wool-rug": {
    status: "final",
    src: "/media/fabrics/undyed-wool-rug-primary.webp",
    alt: "Undyed cream wool rug with a dense soft looped surface",
  },
  "jute-rug": {
    status: "final",
    src: "/media/fabrics/jute-rug-primary.webp",
    alt: "Natural tan jute rug with coarse dry woven bast fibers",
  },
  "recycled-pet-pile-rug": {
    status: "final",
    src: "/media/fabrics/recycled-pet-pile-rug-primary.webp",
    alt: "Grey recycled PET rug with a dense synthetic cut pile",
  },
  "inherently-fr-polyester": {
    status: "final",
    src: "/media/fabrics/inherently-fr-polyester-primary.webp",
    alt: "Graphite inherently flame-resistant polyester contract fabric",
  },
  "bleach-cleanable-vinyl-alternative": {
    status: "final",
    src: "/media/fabrics/bleach-cleanable-vinyl-alternative-primary.webp",
    alt: "Pebble grey bleach-cleanable vinyl alternative with a matte coated surface",
  },
  "recycled-pet-acoustic-felt": {
    status: "final",
    src: "/media/fabrics/recycled-pet-acoustic-felt-primary.webp",
    alt: "Teal recycled PET acoustic felt with visible fiber flecks",
  },
  "silk-charmeuse": {
    status: "final",
    src: "/media/fabrics/silk-charmeuse-primary.webp",
    alt: "Emerald silk charmeuse with liquid drape and natural satin sheen",
  },
  "silk-satin": {
    status: "final",
    src: "/media/fabrics/silk-satin-primary.webp",
    alt: "Ruby silk satin with smooth high sheen and fluid folds",
  },
  "silk-twill": {
    status: "final",
    src: "/media/fabrics/silk-twill-primary.webp",
    alt: "Cobalt silk twill with a fine diagonal grain and soft sheen",
  },
  "silk-noil": {
    status: "final",
    src: "/media/fabrics/silk-noil-primary.webp",
    alt: "Undyed matte silk noil with visible short-fiber texture",
  },
  "silk-tussar": {
    status: "final",
    src: "/media/fabrics/silk-tussar-primary.webp",
    alt: "Copper silk tussar with irregular slubbed plain weave",
  },
  "silk-crepe": {
    status: "final",
    src: "/media/fabrics/silk-crepe-primary.webp",
    alt: "Dusty lilac silk crepe with a fine pebbled surface",
  },
  "silk-faille": {
    status: "final",
    src: "/media/fabrics/silk-faille-primary.webp",
    alt: "Forest green silk faille with a firm crosswise rib",
  },
  "silk-broadcloth": {
    status: "final",
    src: "/media/fabrics/silk-broadcloth-primary.webp",
    alt: "Pale blue silk broadcloth with a fine close plain weave",
  },
  "silk-chiffon-crepe": {
    status: "final",
    src: "/media/fabrics/silk-chiffon-crepe-primary.webp",
    alt: "Blush silk chiffon crepe with sheer pebbled surface and floating drape",
  },
  "polyester-chiffon": {
    status: "final",
    src: "/media/fabrics/polyester-chiffon-primary.webp",
    alt: "Marigold polyester chiffon with lightweight transparent folds",
  },
  "recycled-polyester-chiffon": {
    status: "final",
    src: "/media/fabrics/recycled-polyester-chiffon-primary.webp",
    alt: "Sage recycled polyester chiffon with soft translucent drape",
  },
  "matte-chiffon": {
    status: "final",
    src: "/media/fabrics/matte-chiffon-primary.webp",
    alt: "Dusty lavender matte chiffon with a soft semi-sheer surface",
  },
  "stretch-chiffon": {
    status: "final",
    src: "/media/fabrics/stretch-chiffon-primary.webp",
    alt: "Muted teal stretch chiffon with lightweight semi-sheer folds",
  },
  "crinkle-chiffon": {
    status: "final",
    src: "/media/fabrics/crinkle-chiffon-primary.webp",
    alt: "Burgundy crinkle chiffon with a permanent puckered texture",
  },
  "printed-chiffon": {
    status: "final",
    src: "/media/fabrics/printed-chiffon-primary.webp",
    alt: "Printed chiffon with a small navy abstract pattern and sheer drape",
  },
  "double-layer-chiffon": {
    status: "final",
    src: "/media/fabrics/double-layer-chiffon-primary.webp",
    alt: "Plum double-layer chiffon with increased semi-sheer opacity",
  },
  "cotton-lawn": {
    status: "final",
    src: "/media/fabrics/cotton-lawn-primary.webp",
    alt: "White cotton lawn with a fine close plain weave and crisp hand",
  },
  "batiste-lawn": {
    status: "final",
    src: "/media/fabrics/batiste-lawn-primary.webp",
    alt: "Pale blue cotton batiste lawn with a fine lightweight weave",
  },
  "printed-cotton-lawn": {
    status: "final",
    src: "/media/fabrics/printed-cotton-lawn-primary.webp",
    alt: "Printed cotton lawn with a fine terracotta botanical pattern",
  },
  "embroidered-cotton-lawn": {
    status: "final",
    src: "/media/fabrics/embroidered-cotton-lawn-primary.webp",
    alt: "Sage cotton lawn with raised white floral embroidery",
  },
  "organic-cotton-lawn": {
    status: "final",
    src: "/media/fabrics/organic-cotton-lawn-primary.webp",
    alt: "Undyed organic cotton lawn with a breathable matte weave",
  },
  "mercerised-cotton-lawn": {
    status: "final",
    src: "/media/fabrics/mercerised-cotton-lawn-primary.webp",
    alt: "Coral mercerised cotton lawn with a clean fine plain weave",
  },
  "voile-lawn": {
    status: "final",
    src: "/media/fabrics/voile-lawn-primary.webp",
    alt: "Pale yellow cotton voile lawn with a slightly sheer open weave",
  },
  "slub-cotton-lawn": {
    status: "final",
    src: "/media/fabrics/slub-cotton-lawn-primary.webp",
    alt: "Indigo slub cotton lawn with subtle irregular yarn texture",
  },
  "egyptian-cotton-poplin": {
    status: "final",
    src: "/media/fabrics/egyptian-cotton-poplin-primary.webp",
    alt: "White Egyptian cotton poplin with a fine smooth plain weave",
  },
  "egyptian-cotton-percale": {
    status: "final",
    src: "/media/fabrics/egyptian-cotton-percale-primary.webp",
    alt: "Icy blue Egyptian cotton percale with a crisp matte surface",
  },
  "egyptian-cotton-sateen": {
    status: "final",
    src: "/media/fabrics/egyptian-cotton-sateen-primary.webp",
    alt: "Sage Egyptian cotton sateen with a restrained cotton lustre",
  },
  "egyptian-cotton-voile": {
    status: "final",
    src: "/media/fabrics/egyptian-cotton-voile-primary.webp",
    alt: "Blush Egyptian cotton voile with airy translucent folds",
  },
  "egyptian-cotton-twill": {
    status: "final",
    src: "/media/fabrics/egyptian-cotton-twill-primary.webp",
    alt: "Rust Egyptian cotton twill with a fine diagonal grain",
  },
  "egyptian-cotton-broadcloth": {
    status: "final",
    src: "/media/fabrics/egyptian-cotton-broadcloth-primary.webp",
    alt: "Lavender Egyptian cotton broadcloth with an even fine weave",
  },
  "egyptian-cotton-flannel": {
    status: "final",
    src: "/media/fabrics/egyptian-cotton-flannel-primary.webp",
    alt: "Checked Egyptian cotton flannel with a softly brushed nap",
  },
  "egyptian-cotton-seersucker": {
    status: "final",
    src: "/media/fabrics/egyptian-cotton-seersucker-primary.webp",
    alt: "Blue-and-white Egyptian cotton seersucker with a puckered stripe",
  },
  "classic-oxford-cotton": {
    status: "final",
    src: "/media/fabrics/classic-oxford-cotton-primary.webp",
    alt: "White and blue classic Oxford cotton with a basketweave grain",
  },
  "pinpoint-oxford-cotton": {
    status: "final",
    src: "/media/fabrics/pinpoint-oxford-cotton-primary.webp",
    alt: "Pale blue pinpoint Oxford cotton with a fine compact texture",
  },
  "royal-oxford-cotton": {
    status: "final",
    src: "/media/fabrics/royal-oxford-cotton-primary.webp",
    alt: "Lilac Royal Oxford cotton with pronounced geometric relief",
  },
  "oxford-chambray-cotton": {
    status: "final",
    src: "/media/fabrics/oxford-chambray-cotton-primary.webp",
    alt: "Blue Oxford chambray cotton with coloured-yarn basketweave contrast",
  },
  "soft-oxford-cotton": {
    status: "final",
    src: "/media/fabrics/soft-oxford-cotton-primary.webp",
    alt: "Sage soft Oxford cotton with a softened visible basketweave",
  },
  "heavy-oxford-cotton": {
    status: "final",
    src: "/media/fabrics/heavy-oxford-cotton-primary.webp",
    alt: "Charcoal heavy Oxford cotton with a substantial textured weave",
  },
  "stretch-oxford-cotton": {
    status: "final",
    src: "/media/fabrics/stretch-oxford-cotton-primary.webp",
    alt: "Rust stretch Oxford cotton with a visible basketweave texture",
  },
  "organic-oxford-cotton": {
    status: "final",
    src: "/media/fabrics/organic-oxford-cotton-primary.webp",
    alt: "Ecru organic Oxford cotton with natural basketweave character",
  },
  "pima-cotton-jersey": {
    status: "final",
    src: "/media/fabrics/pima-cotton-jersey-primary.webp",
    alt: "Coral Pima cotton jersey with a smooth fine knit face",
  },
  "pima-cotton-interlock": {
    status: "final",
    src: "/media/fabrics/pima-cotton-interlock-primary.webp",
    alt: "Cream Pima cotton interlock with a smooth stable double face",
  },
  "pima-cotton-poplin": {
    status: "final",
    src: "/media/fabrics/pima-cotton-poplin-primary.webp",
    alt: "Sky blue Pima cotton poplin with a fine crisp plain weave",
  },
  "pima-cotton-sateen": {
    status: "final",
    src: "/media/fabrics/pima-cotton-sateen-primary.webp",
    alt: "Plum Pima cotton sateen with restrained natural lustre",
  },
  "pima-cotton-voile": {
    status: "final",
    src: "/media/fabrics/pima-cotton-voile-primary.webp",
    alt: "Pale yellow Pima cotton voile with airy fine transparency",
  },
  "pima-cotton-fleece": {
    status: "final",
    src: "/media/fabrics/pima-cotton-fleece-primary.webp",
    alt: "Teal Pima cotton fleece with a smooth face and brushed reverse",
  },
  "pima-cotton-rib": {
    status: "final",
    src: "/media/fabrics/pima-cotton-rib-primary.webp",
    alt: "Olive Pima cotton rib with fine raised vertical ribs",
  },
  "pima-cotton-broadcloth": {
    status: "final",
    src: "/media/fabrics/pima-cotton-broadcloth-primary.webp",
    alt: "Terracotta Pima cotton broadcloth with an even fine weave",
  },
  "mercerized-cotton-poplin": {
    status: "final",
    src: "/media/fabrics/mercerized-cotton-poplin-primary.webp",
    alt: "White mercerized cotton poplin with a clean refined surface",
  },
  "mercerized-cotton-jersey": {
    status: "final",
    src: "/media/fabrics/mercerized-cotton-jersey-primary.webp",
    alt: "Emerald mercerized cotton jersey with a subtle smooth lustre",
  },
  "mercerized-cotton-sateen": {
    status: "final",
    src: "/media/fabrics/mercerized-cotton-sateen-primary.webp",
    alt: "Navy mercerized cotton sateen with controlled surface lustre",
  },
  "mercerized-cotton-voile": {
    status: "final",
    src: "/media/fabrics/mercerized-cotton-voile-primary.webp",
    alt: "Mint mercerized cotton voile with fine translucent folds",
  },
  "mercerized-cotton-pique": {
    status: "final",
    src: "/media/fabrics/mercerized-cotton-pique-primary.webp",
    alt: "Cobalt mercerized cotton piqué with raised geometric texture",
  },
  "mercerized-cotton-twill": {
    status: "final",
    src: "/media/fabrics/mercerized-cotton-twill-primary.webp",
    alt: "Olive mercerized cotton twill with a refined diagonal grain",
  },
  "mercerized-cotton-broadcloth": {
    status: "final",
    src: "/media/fabrics/mercerized-cotton-broadcloth-primary.webp",
    alt: "Coral mercerized cotton broadcloth with clean fine yarns",
  },
  "mercerized-cotton-lawn": {
    status: "final",
    src: "/media/fabrics/mercerized-cotton-lawn-primary.webp",
    alt: "Violet mercerized cotton lawn with a crisp fine weave",
  },
  "classic-cotton-pique": {
    status: "final",
    src: "/media/fabrics/classic-cotton-pique-primary.webp",
    alt: "White classic cotton piqué with clear raised geometric texture",
  },
  "fine-cotton-pique": {
    status: "final",
    src: "/media/fabrics/fine-cotton-pique-primary.webp",
    alt: "Dusty rose fine cotton piqué with small raised texture",
  },
  "honeycomb-cotton-pique": {
    status: "final",
    src: "/media/fabrics/honeycomb-cotton-pique-primary.webp",
    alt: "Mustard honeycomb cotton piqué with open geometric relief",
  },
  "birdseye-cotton-pique": {
    status: "final",
    src: "/media/fabrics/birdseye-cotton-pique-primary.webp",
    alt: "Pale blue birdseye cotton piqué with fine dimensional pattern",
  },
  "stretch-cotton-pique": {
    status: "final",
    src: "/media/fabrics/stretch-cotton-pique-primary.webp",
    alt: "Violet stretch cotton piqué with a raised breathable surface",
  },
  "double-cotton-pique": {
    status: "final",
    src: "/media/fabrics/double-cotton-pique-primary.webp",
    alt: "Forest double cotton piqué with dense geometric texture",
  },
  "organic-cotton-pique": {
    status: "final",
    src: "/media/fabrics/organic-cotton-pique-primary.webp",
    alt: "Ecru organic cotton piqué with natural raised texture",
  },
  "cotton-rich-pique": {
    status: "final",
    src: "/media/fabrics/cotton-rich-pique-primary.webp",
    alt: "Charcoal cotton-rich piqué with a dimensional geometric knit",
  },
  "french-terry-lightweight": { status: "final", src: "/media/fabrics/french-terry-lightweight-primary.webp", alt: "french terry lightweight fabric" },
  "french-terry-classic": { status: "final", src: "/media/fabrics/french-terry-classic-primary.webp", alt: "french terry classic fabric" },
  "french-terry-organic": { status: "final", src: "/media/fabrics/french-terry-organic-primary.webp", alt: "french terry organic fabric" },
  "french-terry-modal": { status: "final", src: "/media/fabrics/french-terry-modal-primary.webp", alt: "french terry modal fabric" },
  "french-terry-stretch": { status: "final", src: "/media/fabrics/french-terry-stretch-primary.webp", alt: "french terry stretch fabric" },
  "french-terry-slub": { status: "final", src: "/media/fabrics/french-terry-slub-primary.webp", alt: "french terry slub fabric" },
  "french-terry-loopback": { status: "final", src: "/media/fabrics/french-terry-loopback-primary.webp", alt: "french terry loopback fabric" },
  "french-terry-heavyweight": { status: "final", src: "/media/fabrics/french-terry-heavyweight-primary.webp", alt: "french terry heavyweight fabric" },
  "french-terry-recycled-cotton": { status: "final", src: "/media/fabrics/french-terry-recycled-cotton-primary.webp", alt: "french terry recycled cotton fabric" },
  "french-terry-peached": { status: "final", src: "/media/fabrics/french-terry-peached-primary.webp", alt: "french terry peached fabric" },
  "ponte-rayon-nylon": { status: "final", src: "/media/fabrics/ponte-rayon-nylon-primary.webp", alt: "ponte rayon nylon fabric" },
  "ponte-cotton-rayon": { status: "final", src: "/media/fabrics/ponte-cotton-rayon-primary.webp", alt: "ponte cotton rayon fabric" },
  "ponte-double-knit": { status: "final", src: "/media/fabrics/ponte-double-knit-primary.webp", alt: "ponte double knit fabric" },
  "ponte-compact": { status: "final", src: "/media/fabrics/ponte-compact-primary.webp", alt: "ponte compact fabric" },
  "ponte-brushed": { status: "final", src: "/media/fabrics/ponte-brushed-primary.webp", alt: "ponte brushed fabric" },
  "ponte-structured": { status: "final", src: "/media/fabrics/ponte-structured-primary.webp", alt: "ponte structured fabric" },
  "ponte-lightweight": { status: "final", src: "/media/fabrics/ponte-lightweight-primary.webp", alt: "ponte lightweight fabric" },
  "ponte-matte": { status: "final", src: "/media/fabrics/ponte-matte-primary.webp", alt: "ponte matte fabric" },
  "ponte-ribbed": { status: "final", src: "/media/fabrics/ponte-ribbed-primary.webp", alt: "ponte ribbed fabric" },
  "ponte-travel": { status: "final", src: "/media/fabrics/ponte-travel-primary.webp", alt: "ponte travel fabric" },
  "tencel-plain-weave": { status: "final", src: "/media/fabrics/tencel-plain-weave-primary.webp", alt: "tencel plain weave fabric" },
  "tencel-twill": { status: "final", src: "/media/fabrics/tencel-twill-primary.webp", alt: "tencel twill fabric" },
  "tencel-denim": { status: "final", src: "/media/fabrics/tencel-denim-primary.webp", alt: "tencel denim fabric" },
  "tencel-shirting": { status: "final", src: "/media/fabrics/tencel-shirting-primary.webp", alt: "tencel shirting fabric" },
  "tencel-jersey": { status: "final", src: "/media/fabrics/tencel-jersey-primary.webp", alt: "tencel jersey fabric" },
  "tencel-heavy-twill": { status: "final", src: "/media/fabrics/tencel-heavy-twill-primary.webp", alt: "tencel heavy twill fabric" },
  "tencel-linen-blend": { status: "final", src: "/media/fabrics/tencel-linen-blend-primary.webp", alt: "tencel linen blend fabric" },
  "tencel-sateen": { status: "final", src: "/media/fabrics/tencel-sateen-primary.webp", alt: "tencel sateen fabric" },
  "tencel-brushed": { status: "final", src: "/media/fabrics/tencel-brushed-primary.webp", alt: "tencel brushed fabric" },
  "tencel-cotton-poplin": { status: "final", src: "/media/fabrics/tencel-cotton-poplin-primary.webp", alt: "tencel cotton poplin fabric" },
  "wool-cotton-twill": { status: "final", src: "/media/fabrics/wool-cotton-twill-primary.webp", alt: "wool cotton twill fabric" },
  "wool-linen-tailoring-open-weave": { status: "final", src: "/media/fabrics/wool-linen-tailoring-open-weave-primary.webp", alt: "wool linen tailoring open weave fabric" },
  "wool-silk-suiting": { status: "final", src: "/media/fabrics/wool-silk-suiting-primary.webp", alt: "wool silk suiting fabric" },
  "wool-viscose-twill": { status: "final", src: "/media/fabrics/wool-viscose-twill-primary.webp", alt: "wool viscose twill fabric" },
  "wool-polyester-suiting": { status: "final", src: "/media/fabrics/wool-polyester-suiting-primary.webp", alt: "wool polyester suiting fabric" },
  "wool-polyamide-crepe": { status: "final", src: "/media/fabrics/wool-polyamide-crepe-primary.webp", alt: "wool polyamide crepe fabric" },
  "wool-cashmere-melton": { status: "final", src: "/media/fabrics/wool-cashmere-melton-primary.webp", alt: "wool cashmere melton fabric" },
  "wool-mohair-fresco": { status: "final", src: "/media/fabrics/wool-mohair-fresco-primary.webp", alt: "wool mohair fresco fabric" },
  "wool-alpaca-brushed": { status: "final", src: "/media/fabrics/wool-alpaca-brushed-primary.webp", alt: "wool alpaca brushed fabric" },
  "wool-hemp-canvas": { status: "final", src: "/media/fabrics/wool-hemp-canvas-primary.webp", alt: "wool hemp canvas fabric" },
};
