import type { FabricQuestionSource } from "./types";

/**
 * Every question extracted from the two research reports.
 * Status is assigned before any page is rendered.
 * Estimated trend scores in the second report are not treated as search volume.
 */
export const FABRIC_QUESTION_SOURCES: readonly FabricQuestionSource[] = [
  {
    id: "r1-01",
    question: "What is fabric, and how is it defined?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Definitions",
    originalWording: "What is fabric, and how is it defined?",
    normalizedQuestion: "what is fabric",
    status: "PUBLISHED",
    reason: "Distinct definition intent.",
    destination: "what-is-fabric",
  },
  {
    id: "r1-40",
    question: "What is fabric?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Introduction",
    originalWording: "What is fabric?",
    normalizedQuestion: "what is fabric",
    status: "DUPLICATE",
    reason: "Same wording and intent as r1-01.",
    destination: "what-is-fabric",
  },
  {
    id: "r1-02",
    question: "How is fabric different from textile or cloth?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Definitions",
    originalWording: 'How is "fabric" different from "textile" or "cloth"?',
    normalizedQuestion: "fabric vs textile vs cloth",
    status: "PUBLISHED",
    reason: "Terminology comparison, not a definition of fabric alone.",
    destination: "fabric-vs-textile-vs-cloth",
  },
  {
    id: "r1-41",
    question: "Fabric vs textile?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Introduction",
    originalWording: "Fabric vs. textile?",
    normalizedQuestion: "fabric vs textile vs cloth",
    status: "DUPLICATE",
    reason: "Same comparison intent as r1-02.",
    destination: "fabric-vs-textile-vs-cloth",
  },
  {
    id: "r1-03",
    question: "What are warp and weft?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Definitions",
    originalWording:
      "What are warp and weft in weaving, and how do they differ?",
    normalizedQuestion: "what are warp and weft",
    status: "PUBLISHED",
    reason: "Distinct weaving terminology.",
    destination: "warp-and-weft",
  },
  {
    id: "r1-04",
    question: "What is a fiber versus a yarn versus a fabric?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Definitions",
    originalWording: "What is a fiber vs. yarn vs. fabric?",
    normalizedQuestion: "fiber vs yarn vs fabric",
    status: "PUBLISHED",
    reason: "Distinct material-structure question.",
    destination: "fiber-yarn-and-fabric",
  },
  {
    id: "r1-05",
    question: "How can I identify cotton versus linen?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording:
      "How can I identify cotton versus linen or other natural fibers?",
    normalizedQuestion: "cotton vs linen",
    status: "MERGED",
    reason:
      "The comparison already has a canonical guide. Identification notes live there rather than on a second URL.",
    destination: "/guides/cotton-vs-linen/",
  },
  {
    id: "r1-42",
    question: "How do I tell the difference between cotton and linen?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording: "How do I tell the difference between cotton and linen?",
    normalizedQuestion: "cotton vs linen",
    status: "DUPLICATE",
    reason: "Same cotton-versus-linen intent as r1-05.",
    destination: "/guides/cotton-vs-linen/",
  },
  {
    id: "r1-06",
    question: "What is polyester, and how does it differ from cotton or nylon?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording:
      "What is polyester fabric, and how does it differ from cotton or nylon?",
    normalizedQuestion: "polyester vs cotton and nylon",
    status: "PUBLISHED",
    reason: "Polyester comparison is not covered by the cotton-linen guide.",
    destination: "polyester-cotton-and-nylon",
  },
  {
    id: "r1-43",
    question: "How do I distinguish cotton from polyester?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording: "How to distinguish cotton vs. polyester?",
    normalizedQuestion: "polyester vs cotton and nylon",
    status: "MERGED",
    reason: "Cotton-versus-polyester is the core of the polyester page.",
    destination: "polyester-cotton-and-nylon",
  },
  {
    id: "r1-07",
    question: "Which fabrics work in hot weather?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording:
      "Which fabrics are best for hot weather (breathable, light weight)?",
    normalizedQuestion: "fabrics for hot weather",
    status: "PUBLISHED",
    reason: "Seasonal use question. No fabric is declared universally best.",
    destination: "fabrics-for-hot-weather",
  },
  {
    id: "r1-28",
    question: "What are the best fabrics for summer?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Use and care",
    originalWording:
      "What are the best fabrics for summer (lightweight, breathable)?",
    normalizedQuestion: "fabrics for hot weather",
    status: "DUPLICATE",
    reason: "Same hot-weather intent as r1-07.",
    destination: "fabrics-for-hot-weather",
  },
  {
    id: "r1-48",
    question: "What fabric is best for summer dresses?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Use and care",
    originalWording: "What fabric is best for summer dresses?",
    normalizedQuestion: "fabric for summer dresses",
    status: "MERGED",
    reason:
      "Dress selection already has a guide. Summer constraints are covered on the hot-weather page.",
    destination: "/guides/how-to-choose-fabric-for-dresses/",
  },
  {
    id: "r1-08",
    question: "Which fabrics suit winter clothing?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording:
      "Which fabrics are best for winter clothing (insulating, high GSM)?",
    normalizedQuestion: "fabrics for winter",
    status: "PUBLISHED",
    reason: "Distinct from hot-weather selection.",
    destination: "fabrics-for-winter",
  },
  {
    id: "r1-29",
    question: "What fabrics keep you warm in winter?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Use and care",
    originalWording: "What fabrics keep you warm in winter?",
    normalizedQuestion: "fabrics for winter",
    status: "DUPLICATE",
    reason: "Same winter intent as r1-08.",
    destination: "fabrics-for-winter",
  },
  {
    id: "r1-09",
    question: "What is Tencel or lyocell?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording: "What is Tencel/lyocell, and is it natural or synthetic?",
    normalizedQuestion: "what is tencel lyocell",
    status: "PUBLISHED",
    reason: "Material definition, including natural-versus-processed status.",
    destination: "what-is-tencel-lyocell",
  },
  {
    id: "r1-23",
    question: "Is Tencel natural or synthetic?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Sustainability",
    originalWording: "Is Tencel natural or synthetic?",
    normalizedQuestion: "what is tencel lyocell",
    status: "MERGED",
    reason: "Answered inside the Tencel definition, not as a second page.",
    destination: "what-is-tencel-lyocell",
  },
  {
    id: "r1-45",
    question: "What does Tencel really mean?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Sustainability",
    originalWording: "What does Tencel really mean?",
    normalizedQuestion: "what is tencel lyocell",
    status: "DUPLICATE",
    reason: "Same Tencel definition intent.",
    destination: "what-is-tencel-lyocell",
  },
  {
    id: "r1-10",
    question: "What are plain, twill, and satin weaves, and what is a knit?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording:
      "What are common weaves (plain, twill, satin) and knit types?",
    normalizedQuestion: "plain twill satin weaves and knits",
    status: "MERGED",
    reason: "Weave and knit explanations already have canonical guides.",
    destination: "/guides/woven-vs-knit-fabrics/",
  },
  {
    id: "r1-11",
    question: "What are chiffon, organza, and georgette used for?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording: "What are chiffon, organza, or georgette used for?",
    normalizedQuestion: "chiffon organza georgette uses",
    status: "PUBLISHED",
    reason:
      "Use question. The existing chiffon-versus-georgette guide stays the comparison canonical.",
    destination: "chiffon-organza-georgette-uses",
  },
  {
    id: "r1-30",
    question: "What is chiffon or organza used for?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Use and care",
    originalWording: "What is chiffon/organza used for?",
    normalizedQuestion: "chiffon organza georgette uses",
    status: "DUPLICATE",
    reason: "Subset of the chiffon, organza, and georgette use question.",
    destination: "chiffon-organza-georgette-uses",
  },
  {
    id: "r1-12",
    question: "What is thread count?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Quality",
    originalWording: "What is thread count and how is it calculated?",
    normalizedQuestion: "what is thread count",
    status: "PUBLISHED",
    reason: "Distinct quality metric from GSM.",
    destination: "what-is-thread-count",
  },
  {
    id: "r1-13",
    question: "Does a higher thread count always mean better fabric?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Quality",
    originalWording: "Does a higher thread count always mean better fabric?",
    normalizedQuestion: "does thread count mean better fabric",
    status: "PUBLISHED",
    reason:
      "Different intent from the definition: it challenges a quality claim.",
    destination: "thread-count-and-quality",
  },
  {
    id: "r1-14",
    question: "What is GSM in fabric?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Quality",
    originalWording: "What is GSM (grams per square meter) in fabric?",
    normalizedQuestion: "what is fabric gsm",
    status: "MERGED",
    reason: "The GSM guide is already the canonical explanation.",
    destination: "/guides/fabric-weight-and-gsm/",
  },
  {
    id: "r1-15",
    question: "How does GSM relate to fabric use?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Quality",
    originalWording: "How does GSM relate to fabric use?",
    normalizedQuestion: "what is fabric gsm",
    status: "MERGED",
    reason: "Use of GSM is part of the existing weight guide.",
    destination: "/guides/fabric-weight-and-gsm/",
  },
  {
    id: "r2-24",
    question: "What is fabric GSM and how is it measured?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Textile knowledge",
    originalWording: "What is fabric thickness (GSM) and how to measure it?",
    normalizedQuestion: "what is fabric gsm",
    status: "DUPLICATE",
    reason: "Same GSM intent. GSM is mass per area, not a thickness score.",
    destination: "/guides/fabric-weight-and-gsm/",
  },
  {
    id: "r1-16",
    question: "What GSM suits summer versus winter clothes?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Quality",
    originalWording: "What GSM is suitable for summer vs. winter clothes?",
    normalizedQuestion: "gsm for summer and winter",
    status: "MERGED",
    reason: "Weight selection already has a canonical guide.",
    destination: "/guides/how-to-choose-the-right-fabric-weight/",
  },
  {
    id: "r1-17",
    question: "How can fabric type be identified by touch or appearance?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Identification",
    originalWording:
      "How can I tell fabric type (cotton, polyester, linen, etc.) by touch or appearance?",
    normalizedQuestion: "how to identify fabric",
    status: "PUBLISHED",
    reason: "General identification intent.",
    destination: "how-to-identify-fabric",
  },
  {
    id: "r2-12",
    question: "What is this fabric?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Identification",
    originalWording: "What is this fabric? (sought identification)",
    normalizedQuestion: "how to identify fabric",
    status: "MERGED",
    reason:
      "A photo-identification request has the same intent as the identification guide.",
    destination: "how-to-identify-fabric",
  },
  {
    id: "r1-18",
    question: "What is a fabric burn test?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Identification",
    originalWording: "What is a burn test for fabric, and how to use it?",
    normalizedQuestion: "what is a fabric burn test",
    status: "PUBLISHED",
    reason: "Safety-limited explanation. No burn procedure is published.",
    destination: "what-is-a-fabric-burn-test",
  },
  {
    id: "r1-19",
    question: "What resources help identify fabrics?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Identification",
    originalWording: "What resources help identify fabrics?",
    normalizedQuestion: "fabric identification resources",
    status: "PUBLISHED",
    reason: "Points to records and labs, not a second how-to-identify article.",
    destination: "fabric-identification-resources",
  },
  {
    id: "r1-20",
    question: "Why does linen wrinkle more than cotton?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Identification",
    originalWording: "Why does linen wrinkle more than cotton?",
    normalizedQuestion: "why linen wrinkles more than cotton",
    status: "PUBLISHED",
    reason: "Specific behavior question, not the full cotton-linen guide.",
    destination: "why-linen-wrinkles",
  },
  {
    id: "r1-21",
    question: "Is linen more absorbent than cotton?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Identification",
    originalWording: "Is linen more absorbent than cotton?",
    normalizedQuestion: "is linen more absorbent than cotton",
    status: "PUBLISHED",
    reason: "Moisture question, distinct from wrinkling.",
    destination: "linen-and-cotton-absorbency",
  },
  {
    id: "r1-22",
    question: "What makes Tencel or lyocell described as sustainable?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Sustainability",
    originalWording: "What makes Tencel/lyocell sustainable?",
    normalizedQuestion: "tencel lyocell sustainability",
    status: "PUBLISHED",
    reason: "Process question, separate from the definition page.",
    destination: "tencel-lyocell-sustainability",
  },
  {
    id: "r1-47",
    question: "Why are hemp or Tencel described as more sustainable?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Sustainability",
    originalWording: "Why are fabrics like hemp or Tencel more sustainable?",
    normalizedQuestion: "eco friendly fabrics",
    status: "MERGED",
    reason: "Covered by the eco-friendly fabrics page without a ranking.",
    destination: "eco-friendly-fabrics",
  },
  {
    id: "r1-24",
    question: "What is organic cotton?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Sustainability",
    originalWording:
      "What is organic cotton, and how is it certified (GOTS etc.)?",
    normalizedQuestion: "what is organic cotton",
    status: "PUBLISHED",
    reason:
      "Certification explanation. No FabStitch product is labeled certified here.",
    destination: "what-is-organic-cotton",
  },
  {
    id: "r1-46",
    question: "What is organic cotton versus conventional cotton?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Sustainability",
    originalWording: "What is organic cotton vs. conventional cotton?",
    normalizedQuestion: "what is organic cotton",
    status: "DUPLICATE",
    reason: "Same organic-cotton intent.",
    destination: "what-is-organic-cotton",
  },
  {
    id: "r2-31",
    question:
      "What is the difference between regular cotton and organic cotton?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Sustainability",
    originalWording:
      "What is the difference between regular cotton and organic cotton?",
    normalizedQuestion: "what is organic cotton",
    status: "DUPLICATE",
    reason: "Same organic-cotton comparison.",
    destination: "what-is-organic-cotton",
  },
  {
    id: "r1-25",
    question: "What does OEKO-TEX Standard 100 mean?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Sustainability",
    originalWording: "What does Oeko-Tex Standard 100 certification mean?",
    normalizedQuestion: "what does oeko tex standard 100 mean",
    status: "PUBLISHED",
    reason: "Specific label, not a general eco-fabric list.",
    destination: "oeko-tex-standard-100",
  },
  {
    id: "r2-56",
    question: "What are the benefits of chemical-free printed fabrics?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Sustainability",
    originalWording: "What are the benefits of chemical-free printed fabrics?",
    normalizedQuestion: "what does oeko tex standard 100 mean",
    status: "MERGED",
    reason:
      "Chemical-free is not a verified standard. Substance testing belongs on the OEKO-TEX page.",
    destination: "oeko-tex-standard-100",
  },
  {
    id: "r1-26",
    question: "Which fabrics are described as eco-friendly?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Sustainability",
    originalWording: "Which fabrics are biodegradable or eco-friendly?",
    normalizedQuestion: "eco friendly fabrics",
    status: "PUBLISHED",
    reason: "Explains tradeoffs. Does not rank a winner.",
    destination: "eco-friendly-fabrics",
  },
  {
    id: "r2-15",
    question: "What are some sustainable fabrics?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Sustainability",
    originalWording: "What are some sustainable (eco-friendly) fabrics?",
    normalizedQuestion: "eco friendly fabrics",
    status: "DUPLICATE",
    reason: "Same eco-fabric intent.",
    destination: "eco-friendly-fabrics",
  },
  {
    id: "r1-27",
    question: "What eco-labels exist for fabrics?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Sustainability",
    originalWording: "What eco-labels exist for fabrics?",
    normalizedQuestion: "fabric eco labels",
    status: "PUBLISHED",
    reason: "Label map, linking to the specific certification pages.",
    destination: "fabric-eco-labels",
  },
  {
    id: "r1-31",
    question: "What is satin?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Use and care",
    originalWording: "What is satin?",
    normalizedQuestion: "what is satin",
    status: "PUBLISHED",
    reason:
      "Satin is a weave. Silk-versus-satin remains a separate existing guide.",
    destination: "what-is-satin",
  },
  {
    id: "r1-44",
    question: "What is the difference between silk and satin?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Fabric types",
    originalWording: "Silk vs. satin – what’s the difference?",
    normalizedQuestion: "silk vs satin",
    status: "MERGED",
    reason: "Canonical comparison already exists.",
    destination: "/guides/silk-vs-satin/",
  },
  {
    id: "r1-32",
    question: "What fabric works for activewear?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Use and care",
    originalWording: "What fabric is best for activewear?",
    normalizedQuestion: "fabric for activewear",
    status: "MERGED",
    reason: "Activewear selection already has a guide.",
    destination: "/guides/choosing-fabric-for-activewear/",
  },
  {
    id: "r2-28",
    question: "Which fabric works well for yoga?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Use cases",
    originalWording: "Which fabric works well on surfaces like yoga mats?",
    normalizedQuestion: "fabric for activewear",
    status: "MERGED",
    reason: "Yoga apparel is an activewear brief, not a mat-material question.",
    destination: "/guides/choosing-fabric-for-activewear/",
  },
  {
    id: "r2-55",
    question: "Which fabrics are better for outdoor sportswear?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Use cases",
    originalWording: "Which fabrics are better for outdoor sportswear?",
    normalizedQuestion: "fabric for activewear",
    status: "MERGED",
    reason: "Same performance-apparel intent as the activewear guide.",
    destination: "/guides/choosing-fabric-for-activewear/",
  },
  {
    id: "r1-33",
    question: "How should delicate fabrics be cared for?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Use and care",
    originalWording:
      "How do I care for delicate fabrics (silk, wool, synthetics)?",
    normalizedQuestion: "delicate fabric care",
    status: "PUBLISHED",
    reason: "Care principles without one instruction for every fiber.",
    destination: "delicate-fabric-care",
  },
  {
    id: "r1-50",
    question: "How do I wash or care for silk and wool?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Use and care",
    originalWording: "How to wash or care for silk/wool?",
    normalizedQuestion: "delicate fabric care",
    status: "MERGED",
    reason: "Silk and wool care sit on the delicate-fabric page.",
    destination: "delicate-fabric-care",
  },
  {
    id: "r2-27",
    question: "What are essential garment care tips?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording: "What are essential garment care tips?",
    normalizedQuestion: "everyday fabric laundry",
    status: "MERGED",
    reason: "General care is the laundry-mistakes page, not a third overview.",
    destination: "everyday-laundry-mistakes",
  },
  {
    id: "r2-34",
    question: "How should velvet or organza be ironed?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording: "How to handle/iron velvet (wool/organza)?",
    normalizedQuestion: "delicate fabric care",
    status: "MERGED",
    reason: "Pile and sheer ironing belong with delicate care, not a new URL.",
    destination: "delicate-fabric-care",
  },
  {
    id: "r2-49",
    question: "How to safely iron patterned fabrics?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording: "How to safely iron patterned fabrics?",
    normalizedQuestion: "delicate fabric care",
    status: "MERGED",
    reason:
      "Ironing prints is a care-label question covered with delicate care.",
    destination: "delicate-fabric-care",
  },
  {
    id: "r1-34",
    question: "Is there a marketplace for personal fabric-stash trading?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Marketplace",
    originalWording:
      "Is there a dedicated fabric marketplace for personal stash trading?",
    normalizedQuestion: "personal fabric marketplace",
    status: "PUBLISHED",
    reason:
      "Clarifies that FabStitch is B2B discovery, not a peer stash exchange.",
    destination: "personal-fabric-stash-marketplaces",
  },
  {
    id: "r1-35",
    question: "Where can I buy wholesale fabric online?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Marketplace",
    originalWording: "Where can I buy wholesale fabric online?",
    normalizedQuestion: "wholesale fabric",
    status: "MERGED",
    reason: "The wholesale page is the commercial canonical.",
    destination: "/wholesale-fabric/",
  },
  {
    id: "r1-36",
    question: "What is MOQ for fabric?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Marketplace",
    originalWording:
      "What is MOQ (Minimum Order Quantity) for fabrics and how to negotiate it?",
    normalizedQuestion: "what is fabric moq",
    status: "PUBLISHED",
    reason: "B2B term. No site-wide minimum is invented.",
    destination: "what-is-fabric-moq",
  },
  {
    id: "r1-37",
    question: "How do businesses request fabric samples?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Marketplace",
    originalWording: "How to order fabric samples from overseas suppliers?",
    normalizedQuestion: "how to request fabric samples",
    status: "PUBLISHED",
    reason: "Inquiry workflow, without inventing a sample checkout.",
    destination: "requesting-fabric-samples",
  },
  {
    id: "r1-38",
    question: "How can a buyer verify fabric quality from a supplier?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Marketplace",
    originalWording: "How to verify quality from a new fabric supplier?",
    normalizedQuestion: "verify fabric supplier quality",
    status: "PUBLISHED",
    reason: "Sourcing quality question.",
    destination: "verify-fabric-quality",
  },
  {
    id: "r2-50",
    question: "How can fabric quality be checked from a catalog?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Quality",
    originalWording:
      "What are ways to test fabric quality (e.g., in a catalog or pamphlet)?",
    normalizedQuestion: "verify fabric supplier quality",
    status: "MERGED",
    reason: "Remote checking is part of supplier verification.",
    destination: "verify-fabric-quality",
  },
  {
    id: "r1-39",
    question: "Where are sustainable or technical fabrics sourced?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Marketplace",
    originalWording:
      "Which marketplaces specialize in sustainable or technical fabrics?",
    normalizedQuestion: "sourcing sustainable technical fabrics",
    status: "PUBLISHED",
    reason:
      "Explains how to read a listing. Does not invent a specialist portal.",
    destination: "sourcing-sustainable-technical-fabrics",
  },
  {
    id: "r1-49",
    question: "Which fabrics suit upholstery or bedding?",
    sourceReport: "deep-research-report.md",
    sourceSection: "Use and care",
    originalWording: "Which fabric for upholstery or bedding?",
    normalizedQuestion: "upholstery and bedding fabrics",
    status: "PUBLISHED",
    reason: "Home-textile use. No automotive certification is claimed.",
    destination: "upholstery-and-bedding-fabrics",
  },
  {
    id: "r2-29",
    question: "What fabric suits sofa or car-seat covers?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Use cases",
    originalWording: "What is the best fabric for car seats/sofa upholstery?",
    normalizedQuestion: "upholstery and bedding fabrics",
    status: "MERGED",
    reason:
      "Sofa upholstery shares the upholstery page. Car seating is noted as a different spec.",
    destination: "upholstery-and-bedding-fabrics",
  },
  {
    id: "r2-01",
    question: "How do I fix a cigarette burn on a car seat?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Repairs",
    originalWording:
      "How do I fix a cigarette burn on my car’s fabric front seat?",
    normalizedQuestion: "car seat burn repair",
    status: "REJECTED-OFF-TOPIC",
    reason: "Auto-interior repair, not textile selection or fabric sourcing.",
  },
  {
    id: "r2-02",
    question: "Why do two merino sweaters have different ironing labels?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording:
      "Why do two sweaters of the same 100% merino wool material have different ironing instructions?",
    normalizedQuestion: "why wool care labels differ",
    status: "PUBLISHED",
    reason: "Care-label question, not a how-to-iron procedure.",
    destination: "why-wool-care-labels-differ",
  },
  {
    id: "r2-03",
    question: "How can cotton be softened?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording: "Are there any sure-fire ways to soften cotton?",
    normalizedQuestion: "how to soften cotton",
    status: "PUBLISHED",
    reason: "Hand and finish, without a universal home recipe.",
    destination: "softening-cotton",
  },
  {
    id: "r2-04",
    question: "What causes faded lines on jeans after washing?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording: "What causes faded lines in jeans after washing?",
    normalizedQuestion: "faded lines on jeans",
    status: "PUBLISHED",
    reason: "Denim wear question.",
    destination: "faded-lines-on-jeans",
  },
  {
    id: "r2-05",
    question: "How do I remove soot from clothes and bedding?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Cleaning",
    originalWording:
      "How do I get soot out of my clothes, blankets and pillows?",
    normalizedQuestion: "remove soot from clothes",
    status: "REJECTED-OFF-TOPIC",
    reason: "Household disaster cleaning, not a fabric-sourcing question.",
  },
  {
    id: "r2-06",
    question: "How do I repair a rip beside a load-bearing grommet?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Repairs",
    originalWording:
      "How to repair/reinforce a rip near a load-bearing fabric grommet?",
    normalizedQuestion: "repair load bearing grommet",
    status: "REJECTED-OFF-TOPIC",
    reason: "Equipment repair, not apparel fabric education.",
  },
  {
    id: "r2-07",
    question: "How can thread quality in a stitched garment be judged?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Quality",
    originalWording:
      "How can I know the quality of thread in stitched garments?",
    normalizedQuestion: "thread quality in garments",
    status: "PUBLISHED",
    reason: "Production quality, distinct from fabric thread count.",
    destination: "thread-quality-in-garments",
  },
  {
    id: "r2-08",
    question: "What is cork fabric used for?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Materials",
    originalWording: "What can I sew with cork fabric, and how to handle it?",
    normalizedQuestion: "what is cork fabric",
    status: "PUBLISHED",
    reason: "Specialty material. FabStitch does not claim a cork catalog.",
    destination: "what-is-cork-fabric",
  },
  {
    id: "r2-09",
    question: "Can outdoor upholstery fabric be used for apparel?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Use cases",
    originalWording: "Is it safe to use outdoor upholstery fabric for apparel?",
    normalizedQuestion: "outdoor upholstery fabric for apparel",
    status: "PUBLISHED",
    reason: "Use mismatch. No safety certification is invented.",
    destination: "outdoor-upholstery-for-apparel",
  },
  {
    id: "r2-10",
    question: "How do I choose fabric with more confidence?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Selection",
    originalWording: "Any tips to feel confident picking fabric?",
    normalizedQuestion: "how to choose fabric",
    status: "PUBLISHED",
    reason: "Selection method. Quilting color advice is not the page.",
    destination: "how-to-choose-fabric",
  },
  {
    id: "r2-11",
    question: "What is Aida cloth?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Materials",
    originalWording: "[Chat] Removing Aida cloth?",
    normalizedQuestion: "what is aida cloth",
    status: "PUBLISHED",
    reason: "Counted-thread cloth. Not sold as an apparel fabric here.",
    destination: "what-is-aida-cloth",
  },
  {
    id: "r2-13",
    question: "Is Microsoft Fabric the right career shortcut?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Off topic",
    originalWording:
      "Is Microsoft Fabric the right shortcut for a data analyst moving to data engineer?",
    normalizedQuestion: "microsoft fabric",
    status: "REJECTED-OFF-TOPIC",
    reason: "Microsoft Fabric is a data platform, not a textile.",
  },
  {
    id: "r2-14",
    question: "Which fabrics are comfortable in summer?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Use cases",
    originalWording: "Which fabrics are most comfortable for summer season?",
    normalizedQuestion: "fabrics for hot weather",
    status: "DUPLICATE",
    reason: "Same summer intent as the hot-weather page.",
    destination: "fabrics-for-hot-weather",
  },
  {
    id: "r2-16",
    question: "What are common laundry mistakes?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording:
      "What are common mistakes in everyday laundry for fabrics?",
    normalizedQuestion: "everyday fabric laundry",
    status: "PUBLISHED",
    reason: "Laundry errors, distinct from delicate-fiber care.",
    destination: "everyday-laundry-mistakes",
  },
  {
    id: "r2-17",
    question: "What is the main difference between cotton and polyester?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Comparisons",
    originalWording:
      "What is the main difference between cotton and polyester fabrics?",
    normalizedQuestion: "polyester vs cotton and nylon",
    status: "DUPLICATE",
    reason: "Same polyester-versus-cotton intent.",
    destination: "polyester-cotton-and-nylon",
  },
  {
    id: "r2-18",
    question: "What is the difference between chiffon, georgette, and satin?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Comparisons",
    originalWording:
      "What is the difference between chiffon, georgette and satin?",
    normalizedQuestion: "chiffon georgette and satin",
    status: "PUBLISHED",
    reason:
      "Three-way comparison. Existing chiffon-versus-georgette guide stays linked, not replaced.",
    destination: "chiffon-georgette-and-satin",
  },
  {
    id: "r2-19",
    question: "What is the difference between voile and cotton?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Comparisons",
    originalWording: "What is the difference between voile and cotton fabrics?",
    normalizedQuestion: "voile and cotton",
    status: "PUBLISHED",
    reason: "Construction versus fiber, not a fiber-versus-fiber page.",
    destination: "voile-and-cotton",
  },
  {
    id: "r2-20",
    question: "How are oil or wine stains approached on fabric?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording:
      "What are home remedies to remove fabric stains (oil/wine)?",
    normalizedQuestion: "fabric stain care",
    status: "PUBLISHED",
    reason: "Stain principles. No universal home recipe.",
    destination: "fabric-stain-care",
  },
  {
    id: "r2-45",
    question: "Which fabric releases cosmetic stains more easily?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording: "Which fabric is easier to remove cosmetic stains from?",
    normalizedQuestion: "fabric stain care",
    status: "MERGED",
    reason: "Cosmetic stains are part of stain care, not a fabric ranking.",
    destination: "fabric-stain-care",
  },
  {
    id: "r2-57",
    question: "How do I remove lipstick from fabric?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording: "How to remove lipstick or makeup stains from fabric?",
    normalizedQuestion: "fabric stain care",
    status: "MERGED",
    reason: "Same stain-care intent.",
    destination: "fabric-stain-care",
  },
  {
    id: "r2-21",
    question: "Which fabrics do not trap sweat?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Use cases",
    originalWording: "Which fabric does not trap sweat?",
    normalizedQuestion: "fabrics that do not trap sweat",
    status: "PUBLISHED",
    reason: "Moisture behavior, not only the activewear guide.",
    destination: "fabrics-and-sweat",
  },
  {
    id: "r2-22",
    question: "How do I tell georgette from satin?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Identification",
    originalWording: "How to identify if a fabric is georgette/satin?",
    normalizedQuestion: "identify georgette and satin",
    status: "PUBLISHED",
    reason: "Narrower than general identification.",
    destination: "identifying-georgette-and-satin",
  },
  {
    id: "r2-23",
    question: "How do I buy fabric by the metre or yard?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Sourcing",
    originalWording: "How to buy fabric based on measurements (meters/yards)?",
    normalizedQuestion: "buying fabric by length",
    status: "PUBLISHED",
    reason: "Length and width, distinct from the width guide.",
    destination: "buying-fabric-by-length",
  },
  {
    id: "r2-25",
    question: "How do I choose a woven wool or cotton?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Selection",
    originalWording: "How to choose woven fabrics (wool/cotton)?",
    normalizedQuestion: "choosing woven wool and cotton",
    status: "PUBLISHED",
    reason:
      "Selection brief. Weave definitions stay on the existing weave guide.",
    destination: "choosing-woven-wool-and-cotton",
  },
  {
    id: "r2-26",
    question: "How should a buyer read fabric prints?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Prints",
    originalWording: "What are the trendy fabric prints or patterns?",
    normalizedQuestion: "reading fabric prints",
    status: "PUBLISHED",
    reason: "No unverified 2026 trend ranking is published.",
    destination: "reading-fabric-prints",
  },
  {
    id: "r2-51",
    question: "What are the trending fabrics for 2026?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Prints",
    originalWording:
      "What are the trending fabrics in mainstream fashion for 2026?",
    normalizedQuestion: "reading fabric prints",
    status: "MERGED",
    reason:
      "Trend scores in the source are estimates. The print page refuses a fake ranking.",
    destination: "reading-fabric-prints",
  },
  {
    id: "r2-30",
    question: "What is ripstop fabric used for?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Materials",
    originalWording: "What is ripstop fabric used for (shoes/bags/jackets)?",
    normalizedQuestion: "what is ripstop fabric",
    status: "PUBLISHED",
    reason: "Construction definition.",
    destination: "what-is-ripstop",
  },
  {
    id: "r2-32",
    question: "What is the difference between microfiber and rayon?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Comparisons",
    originalWording:
      "What is the difference between microfiber and rayon fabrics?",
    normalizedQuestion: "microfiber and rayon",
    status: "PUBLISHED",
    reason: "Synthetic filament versus regenerated cellulose.",
    destination: "microfiber-and-rayon",
  },
  {
    id: "r2-33",
    question: "What cloths are used for structured jackets and borders?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Materials",
    originalWording:
      "What special fabrics are used in handicrafts (borders/Nehru jackets, etc.)?",
    normalizedQuestion: "fabrics for structured jackets",
    status: "PUBLISHED",
    reason: "Construction brief. No handicraft SKU is invented.",
    destination: "fabrics-for-structured-jackets",
  },
  {
    id: "r2-35",
    question: "How do I print sewing patterns at home?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Craft",
    originalWording: "How to print sewing patterns at home?",
    normalizedQuestion: "print sewing patterns",
    status: "REJECTED-OFF-TOPIC",
    reason: "Printer setup, not a fabric question.",
  },
  {
    id: "r2-36",
    question: "Which fabrics hold zippers and buttons?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Construction",
    originalWording:
      "Which fabrics are suitable for fasteners (zippers/buttons)?",
    normalizedQuestion: "fabrics for zippers and buttons",
    status: "PUBLISHED",
    reason: "Garment-construction constraint.",
    destination: "fabrics-for-fasteners",
  },
  {
    id: "r2-37",
    question: "What fabrics are considered for children's clothing?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Use cases",
    originalWording: "What is the softest fabric for children's clothing?",
    normalizedQuestion: "fabrics for childrens clothing",
    status: "PUBLISHED",
    reason: "Softness is a hand question, not a single winner.",
    destination: "fabrics-for-childrens-clothing",
  },
  {
    id: "r2-52",
    question: "What natural fabrics are discussed for baby clothes?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Use cases",
    originalWording: "What natural fabrics are safe for diapers/baby clothes?",
    normalizedQuestion: "fabrics for childrens clothing",
    status: "MERGED",
    reason:
      "Baby-clothing constraints sit on the children's page. No medical claim is made.",
    destination: "fabrics-for-childrens-clothing",
  },
  {
    id: "r2-38",
    question: "Why do fabric colors fade?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Quality",
    originalWording: "Why do colors fade in printed and solid fabrics?",
    normalizedQuestion: "why fabric color fades",
    status: "PUBLISHED",
    reason: "Colorfastness.",
    destination: "why-fabric-color-fades",
  },
  {
    id: "r2-40",
    question: "How is dye set in fabric?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Quality",
    originalWording: "What are methods to lock dye into fabrics?",
    normalizedQuestion: "why fabric color fades",
    status: "MERGED",
    reason:
      "Home dye-lock recipes are not published. Colorfastness is the canonical page.",
    destination: "why-fabric-color-fades",
  },
  {
    id: "r2-39",
    question: "How is sewing pucker reduced?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Construction",
    originalWording: "How to prevent puckering on fabric during sewing?",
    normalizedQuestion: "sewing pucker",
    status: "PUBLISHED",
    reason: "Cloth and tension, not a machine manual.",
    destination: "sewing-pucker",
  },
  {
    id: "r2-41",
    question: "How does new cloth differ from worn cloth?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Quality",
    originalWording:
      "What is the difference between new fabric (shirt/trousers) and old/worn fabric?",
    normalizedQuestion: "new and worn fabric",
    status: "PUBLISHED",
    reason: "Wear changes hand. Not a quality score.",
    destination: "new-and-worn-fabric",
  },
  {
    id: "r2-42",
    question: "Are crepe de chine and georgette the same?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Comparisons",
    originalWording: "Are crepe de chine and georgette the same fabric?",
    normalizedQuestion: "crepe de chine and georgette",
    status: "PUBLISHED",
    reason: "Named constructions in the FabStitch material set.",
    destination: "crepe-de-chine-and-georgette",
  },
  {
    id: "r2-43",
    question: "What lining cloth is used inside structured garments?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Materials",
    originalWording:
      "What lining fabric works best to make leather look stylish?",
    normalizedQuestion: "lining fabrics",
    status: "PUBLISHED",
    reason: "Lining brief. Leather styling claims are not made.",
    destination: "lining-fabrics",
  },
  {
    id: "r2-44",
    question: "How should clothes be stored?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording: "How to store/fold clothes to avoid stains and wrinkles?",
    normalizedQuestion: "storing clothes",
    status: "PUBLISHED",
    reason: "Storage, distinct from washing.",
    destination: "storing-clothes",
  },
  {
    id: "r2-46",
    question: "How should hand-dyed fabric be cared for?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Care",
    originalWording: "How to care for hand-dyed fabrics?",
    normalizedQuestion: "hand dyed fabric care",
    status: "PUBLISHED",
    reason: "Unverified colorfastness, distinct from general fading.",
    destination: "hand-dyed-fabric-care",
  },
  {
    id: "r2-47",
    question:
      "What is the difference between a face print and a reverse print?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Prints",
    originalWording:
      "What is the difference between digital print and reverse digital print fabrics?",
    normalizedQuestion: "digital print and reverse print",
    status: "PUBLISHED",
    reason: "Print placement. No proprietary process is invented.",
    destination: "digital-and-reverse-prints",
  },
  {
    id: "r2-48",
    question: "How do Tencel lyocell and viscose differ?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Comparisons",
    originalWording:
      "What is the difference between Tencel (Lyocell) and polyester rayon (viscose)?",
    normalizedQuestion: "tencel and viscose",
    status: "PUBLISHED",
    reason: "Two regenerated celluloses with different processes.",
    destination: "tencel-and-viscose",
  },
  {
    id: "r2-53",
    question: "How do fabric masks compare with N95 masks?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Health",
    originalWording:
      "How do fabric masks compare to N95 masks (with regard to valves)?",
    normalizedQuestion: "fabric masks and n95",
    status: "REJECTED-OFF-TOPIC",
    reason: "Medical PPE comparison, not apparel fabric sourcing.",
  },
  {
    id: "r2-54",
    question: "Which fabrics are described as skin-friendly?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Use cases",
    originalWording: "Which fabrics are considered skin-friendly?",
    normalizedQuestion: "skin friendly fabrics",
    status: "PUBLISHED",
    reason: "Hand and finish. No dermatology claim.",
    destination: "skin-comfort-and-fabric",
  },
  {
    id: "r2-58",
    question: "Which fiber blend is most durable?",
    sourceReport: "deep-research-report (1).md",
    sourceSection: "Quality",
    originalWording:
      "Which fiber blend (hybrid) is most durable in blended fabrics?",
    normalizedQuestion: "durable fiber blends",
    status: "PUBLISHED",
    reason: "Durability depends on construction. No blend is crowned.",
    destination: "durable-fiber-blends",
  },
];
