import type { SeedGroup } from "./types";
import type { SeedRow } from "./seeds";
import { IMG } from "./seeds";

function r(
  id: number,
  keyword: string,
  group: SeedGroup,
  topic: string,
  existingCanonical: string,
  peerKeyword: string,
  peer2Keyword: string,
  primaryUse: string,
  imageKey: keyof typeof IMG,
  imageAlt: string,
  collectionPath: string,
  bestForPath: string,
  definition: string,
  makeup: string,
  feel: string,
  weight: string,
  uses: string,
  strengths: string,
  limits: string,
  care: string,
  sampling: string,
  climate: string,
  mistake: string,
  specCheck: string,
): SeedRow {
  return [
    id,
    keyword,
    group,
    topic,
    existingCanonical,
    peerKeyword,
    peer2Keyword,
    primaryUse,
    imageKey,
    imageAlt,
    collectionPath,
    bestForPath,
    [
      definition,
      makeup,
      feel,
      weight,
      uses,
      strengths,
      limits,
      care,
      sampling,
      climate,
      mistake,
      specCheck,
    ],
  ];
}

export const SEED_ROWS_REST: readonly SeedRow[] = [
  r(
    11,
    "net fabric",
    "material",
    "net",
    "/discover/net-fabric/",
    "lace fabric",
    "mesh fabric",
    "dresses",
    "net",
    "Open net-like voile showing light through a fine weave",
    "",
    "/fabrics/best-for/dresses/",
    "Net is an open cloth with holes. It is used for overlay, trim, and some technical meshes.",
    "Name fibre, hole size, and whether it is dress net, tulle, or a technical mesh.",
    "Crisp or soft depending on finish. Open holes change both look and cover.",
    "Usually light. Technical nets can still feel firm.",
    "Overlays, eveningwear, millinery, and some sports ventilation.",
    "Sheer structure without the shine of satin.",
    "Snags, laddering, and poor cover. It rarely works as a self-lining.",
    "Gentle handling. Heat can melt some synthetic nets.",
    "Hold the sample over skin and over lining. Judge hole size in use.",
    "Common in evening and warm-weather overlays.",
    "Using dress net where a stable mesh or lining is required.",
    "Fibre, hole size, weight, width, and lining plan.",
  ),
  r(
    12,
    "lace fabric",
    "material",
    "lace",
    "/discover/lace/",
    "net fabric",
    "embroidered fabric",
    "dresses",
    "lace",
    "Open patterned lace-like jacquard with decorative voids",
    "",
    "/fabrics/best-for/dresses/",
    "Lace is a patterned open cloth. Motif, ground, and edge all change how it is cut.",
    "Name fibre, motif scale, ground (net or embroidered), and whether it has a scallop edge.",
    "Soft or crisp. Motif areas feel thicker than the ground.",
    "Usually light, but corded lace can feel substantial.",
    "Dresses, overlays, lingerie, and trims.",
    "Decorative face that can carry a garment without extra print.",
    "Motif matching, fragile grounds, and poor opacity.",
    "Often specialist clean. Heat can distort some synthetics.",
    "Lay a sample over lining. Check motif repeat across a seam.",
    "Used year-round for occasionwear.",
    "Ignoring motif repeat and scallop direction in marker making.",
    "Fibre, motif, ground, width, and edge type.",
  ),
  r(
    13,
    "jacquard fabric",
    "material",
    "jacquard",
    "/discover/jacquard/",
    "brocade fabric",
    "printed fabric",
    "upholstery",
    "jacquard",
    "Woven jacquard with a deconstructed pattern in the cloth",
    "",
    "/fabrics/best-for/upholstery/",
    "Jacquard is a woven pattern made in the cloth, not printed on the surface.",
    "Name fibre, motif scale, face and reverse, and whether it is apparel or furnishing weight.",
    "Patterned and often slightly dimensional. Reverse may look different from the face.",
    "Apparel jacquards can be light. Furnishing jacquards are often heavy.",
    "Jackets, dresses, and upholstery when the weight matches the use.",
    "Pattern that will not wash off like a print.",
    "Motif matching, stiffness, and abrasion on raised areas.",
    "Follow the published care line. Some jacquards need gentle clean.",
    "Check motif scale on a full width, not a tiny swatch only.",
    "Heavier jacquards read as cooler-weather or indoor furnishing cloth.",
    "Using a furnishing jacquard on a close-fitting dress without testing drape.",
    "Fibre, motif, weight, width, and face versus reverse.",
  ),
  r(
    14,
    "brocade fabric",
    "material",
    "brocade",
    "/discover/brocade/",
    "jacquard fabric",
    "satin fabric",
    "dresses",
    "brocade",
    "Ornate woven brocade-like jacquard with raised pattern",
    "",
    "/fabrics/best-for/dresses/",
    "Brocade is a richly patterned woven, often with extra yarns that sit on the face.",
    "Name fibre, extra-yarn type, motif, and whether it is apparel or furnishing.",
    "Stiffer and more ornamental than a plain satin. Pattern can feel raised.",
    "Usually mid to heavy. Light brocades exist but are less common.",
    "Occasion jackets, dresses, and some interiors.",
    "Ornament without embroidery or print.",
    "Bulk at seams, snagging of extra yarns, and poor drape for fluid dresses.",
    "Often specialist clean. Heat can flatten extra yarns.",
    "Fold a sample at a seam allowance. Check bulk and pattern crush.",
    "Often used for cooler indoor occasionwear.",
    "Treating brocade as a fluid evening satin.",
    "Fibre, extra yarns, motif, weight, and care.",
  ),
  r(
    15,
    "sequin fabric",
    "material",
    "sequin",
    "/discover/sequin-fabric/",
    "velvet fabric",
    "lace fabric",
    "dresses",
    "sequin",
    "Reflective decorative surface similar to evening pile cloth",
    "",
    "/fabrics/best-for/dresses/",
    "Sequin fabric carries sequins on a ground cloth. Ground, size, and stitch all matter.",
    "Name ground fibre, sequin material, coverage, and whether sequins are sewn or glued.",
    "Stiff and reflective. Ground can still be soft under the sequins.",
    "Weight depends on coverage. Dense sequins add substantial mass.",
    "Evening dresses, overlays, and statement panels.",
    "Light catch that a print cannot match.",
    "Shedding, snagging, and uncomfortable reverse. Seating can crush sequins.",
    "Usually specialist clean. Heat and agitation can strip sequins.",
    "Rub and fold a sample. Check shed and reverse comfort.",
    "Mostly occasionwear rather than daily climate clothing.",
    "Ignoring reverse comfort and lining when sequins sit against skin.",
    "Ground, sequin type, coverage, weight, and care.",
  ),
  r(
    16,
    "printed fabric",
    "material",
    "printed",
    "/discover/printed-fabric/",
    "jacquard fabric",
    "embroidered fabric",
    "dresses",
    "printed",
    "Printed cotton voile with colour sitting on a light woven face",
    "/collections/printed/",
    "/fabrics/best-for/dresses/",
    "Printed fabric carries colour or motif on a base cloth. Base cloth still rules performance.",
    "Name base fibre, print method if published, repeat size, and colourfastness notes.",
    "Hand follows the base cloth. A heavy print paste can add stiffness.",
    "Weight follows the base. Voile prints are light. Canvas prints are heavy.",
    "Dresses, shirts, home textiles, and many seasonal collections.",
    "Motif flexibility without weaving a jacquard.",
    "Fade, crocking, and misaligned repeats. Base cloth limits still apply.",
    "Wash tests matter. Some prints bleed or crack.",
    "Wash a sample if the garment will be washed. Check repeat across a panel.",
    "Seasonal prints exist for both warm and cool collections. Base cloth decides comfort.",
    "Buying the print and ignoring the base fibre and construction.",
    "Base cloth, print method, repeat, weight, and colourfastness.",
  ),
  r(
    17,
    "embroidered fabric",
    "material",
    "embroidered",
    "/discover/embroidered-fabric/",
    "lace fabric",
    "jacquard fabric",
    "dresses",
    "embroidered",
    "Decorative stitched surface on a patterned woven ground",
    "",
    "/fabrics/best-for/dresses/",
    "Embroidered fabric has stitch sitting on a ground cloth. Ground and stitch density change drape.",
    "Name ground fibre, stitch fibre, coverage, and whether embroidery is all-over or placed.",
    "Stitched areas feel thicker. Open ground between motifs stays closer to the base cloth.",
    "Weight rises with stitch density. All-over embroidery can feel heavy.",
    "Dresses, blouses, and occasion panels.",
    "Texture and motif without relying only on print.",
    "Stiffness, thread snag, and shrinkage mismatch between stitch and ground.",
    "Often gentle or specialist care. Heat can crush stitch.",
    "Bend a sample at a seam. Check bulk and thread security.",
    "Used year-round for occasion and decorative apparel.",
    "Ignoring how stitch density changes drape versus the unembroidered ground.",
    "Ground, stitch, coverage, weight, and care.",
  ),
  r(
    18,
    "organic cotton fabric",
    "material",
    "organic cotton",
    "/discover/organic-cotton/",
    "cotton fabric",
    "sustainable fabric",
    "shirts",
    "organic",
    "Soft organic cotton jersey with a fine looped face",
    "",
    "/fabrics/best-for/shirts/",
    "Organic cotton is cotton grown under an organic farming standard named on evidence, not on the word organic alone.",
    "Ask which standard is claimed and whether it applies to fibre, mill, or garment. Do not assume one label covers all steps.",
    "Hand still depends on yarn and construction. Organic status does not make every cloth soft.",
    "Weight still follows construction. Jersey, poplin, and canvas remain different.",
    "The same uses as other cottons: shirts, dresses, knits, and home cloth, when specs match.",
    "A farming claim that some buyers require, when evidence is attached.",
    "The word organic does not prove colourfastness, shrinkage, or mill conditions.",
    "Care follows construction, not the farming claim.",
    "Read the claim on the named page. Sample the actual construction.",
    "Climate comfort still follows weight and construction.",
    "Treating organic cotton as automatically lower impact at every later process step.",
    "Claim scope, construction, weight, width, and ordinary cotton tests.",
  ),
  r(
    19,
    "hemp fabric",
    "material",
    "hemp",
    "/discover/hemp/",
    "linen fabric",
    "cotton fabric",
    "trousers",
    "hemp",
    "Hemp-cotton denim with a dry, durable woven face",
    "",
    "/fabrics/best-for/trousers/",
    "Hemp is a bast fibre. Apparel hemp is often blended to soften the hand.",
    "Name hemp content, blend partners, and weave. Pure hemp and hemp-cotton do not feel the same.",
    "Dry and durable. Blends with cotton or viscose usually hang softer.",
    "Often mid-weight for trousers and jackets. Light hemp shirtings also exist.",
    "Trousers, jackets, bags, and some shirts.",
    "Strength and a dry character similar to linen families.",
    "Can feel firm. Colour and hand vary widely by mill and blend.",
    "Follow the published care line. Some hemp cloths soften after wash.",
    "Wash a sample if the garment will be washed. Judge hand after finishing.",
    "Used in warm weather when the cloth is open enough, and in layers when heavier.",
    "Assuming hemp is automatically the lowest-impact choice without reading the process.",
    "Hemp content, blend, weave, weight, and finish.",
  ),
  r(
    20,
    "bamboo fabric",
    "material",
    "bamboo",
    "/discover/bamboo/",
    "viscose fabric",
    "cotton fabric",
    "t-shirts",
    "bamboo",
    "Fine bamboo jersey loops with a soft knit surface",
    "",
    "/fabrics/best-for/knitwear/",
    "Bamboo on a fabric page often means a regenerated cellulose fibre made from bamboo pulp, not a woven bamboo strip.",
    "Read the fibre name. Bamboo viscose, lyocell-from-bamboo, and rare mechanically processed bamboo are different.",
    "Many bamboo viscose knits feel smooth and fluid.",
    "Jersey programs are often light. Wovens can sit heavier.",
    "T-shirts, underwear, and dresses when the construction matches.",
    "Soft knit hand in many viscose-from-bamboo programs.",
    "The word bamboo is not an environmental proof. Wet strength and pilling still need tests.",
    "Care follows the actual fibre and knit, not the plant name.",
    "Sample the named fibre. Do not substitute a cotton jersey without a new test.",
    "Light knits are common in warm-weather next-to-skin programs.",
    "Claiming bamboo cloth is automatically eco friendly without process evidence.",
    "Exact fibre name, construction, weight, and care.",
  ),
  r(
    21,
    "recycled fabric",
    "material",
    "recycled",
    "/discover/recycled-fabric/",
    "recycled polyester fabric",
    "sustainable fabric",
    "activewear",
    "recycled",
    "Recycled polyester ripstop with a tight technical weave",
    "",
    "/fabrics/best-for/activewear/",
    "Recycled fabric is made with some recycled input. The page should say what was recycled and how much.",
    "Ask for fibre type, recycled content percentage if published, and whether content is pre- or post-consumer.",
    "Hand follows the fibre family. Recycled polyester still feels like polyester unless otherwise finished.",
    "Weight still follows construction.",
    "Activewear, bags, outer shells, and some apparel wovens and knits.",
    "A materials claim some buyers require, when evidence is attached.",
    "Recycled content does not automatically mean lower impact, better colour, or better hand.",
    "Care follows the fibre family.",
    "Read the claim scope. Sample colour and pilling as you would for virgin fibre.",
    "Climate comfort still follows construction, not the recycled label.",
    "Using recycled as a substitute for a full specification.",
    "Fibre, recycled content, construction, weight, and ordinary quality tests.",
  ),
  r(
    22,
    "sustainable fabric",
    "sourcing",
    "sustainable",
    "/discover/sustainable-fabric/",
    "eco friendly fabric",
    "organic cotton fabric",
    "clothing",
    "sustainable",
    "Flax linen used in conversations about lower-impact fibre choices",
    "",
    "/fabrics/best-for/shirts/",
    "Sustainable fabric is a claim, not a single fibre. The useful page names the issue: fibre, chemistry, water, waste, or durability.",
    "Ask which issue is in scope and what evidence is attached. Do not treat the word as a fibre name.",
    "Hand and weight still belong to the actual cloth.",
    "There is no sustainable GSM. Weight follows construction.",
    "Any end use, if the named cloth actually meets the garment spec.",
    "A way to structure questions for mills and brands.",
    "The label can hide weak specs. Durability still matters.",
    "Care still follows the real fibre and finish.",
    "Sample the named cloth. A claim is not a swatch.",
    "Climate comfort is about construction, not the sustainability headline.",
    "Ranking one fibre as the most sustainable without context.",
    "Claim scope, fibre, construction, weight, and ordinary tests.",
  ),
  r(
    23,
    "eco friendly fabric",
    "sourcing",
    "eco friendly",
    "/discover/eco-friendly-fabric/",
    "sustainable fabric",
    "recycled fabric",
    "clothing",
    "eco",
    "Organic cotton jersey often used as an example in eco-claim reviews",
    "",
    "/fabrics/best-for/shirts/",
    "Eco friendly fabric is marketing language unless the page names a specific, evidenced practice.",
    "Prefer named fibre, process, or standard over the phrase eco friendly.",
    "Feel still comes from yarn and construction.",
    "Weight is independent of the eco headline.",
    "Only useful when the underlying cloth matches the garment.",
    "It can start a better conversation if it leads to evidence.",
    "Vague eco language can replace real specification.",
    "Care follows the real cloth.",
    "Ask for the evidence pack with the sample.",
    "Warm or cool comfort is not proven by an eco label.",
    "Using eco friendly as a fibre substitute in a tech pack.",
    "Named practice, fibre, construction, and tests.",
  ),
];
