import type { SeedGroup, SeedRecord } from "./types";

const IMG = {
  cotton: "/media/fabrics/cotton-poplin-primary.webp",
  linen: "/media/fabrics/european-flax-linen-primary.webp",
  wool: "/media/fabrics/tropical-wool-super-110s-130s-primary.webp",
  knit: "/media/fabrics/mercerized-cotton-jersey-primary.webp",
  denim: "/media/fabrics/lightweight-denim-primary.webp",
  viscose: "/media/fabrics/silk-georgette-primary.webp",
  rayon: "/media/fabrics/silk-georgette-primary.webp",
  chiffon: "/media/fabrics/silk-chiffon-primary.webp",
  velvet: "/media/fabrics/crushed-velvet-primary.webp",
  satin: "/media/fabrics/silk-satin-primary.webp",
  net: "/media/fabrics/cotton-voile-primary.webp",
  lace: "/media/fabrics/deconstructed-jacquard-primary.webp",
  jacquard: "/media/fabrics/deconstructed-jacquard-primary.webp",
  brocade: "/media/fabrics/deconstructed-jacquard-primary.webp",
  sequin: "/media/fabrics/crushed-velvet-primary.webp",
  printed: "/media/fabrics/cotton-voile-primary.webp",
  embroidered: "/media/fabrics/deconstructed-jacquard-primary.webp",
  organic: "/media/fabrics/organic-cotton-lawn-primary.webp",
  hemp: "/media/fabrics/hemp-cotton-denim-primary.webp",
  bamboo: "/media/fabrics/french-terry-modal-primary.webp",
  recycled: "/media/fabrics/recycled-polyester-chiffon-primary.webp",
  sustainable: "/media/fabrics/european-flax-linen-primary.webp",
  eco: "/media/fabrics/organic-cotton-lawn-primary.webp",
  breathable: "/media/fabrics/cotton-voile-primary.webp",
  stretch: "/media/fabrics/stretch-woven-compression-primary.webp",
  waterproof: "/media/fabrics/wool-hemp-canvas-primary.webp",
  lightweight: "/media/fabrics/cotton-voile-primary.webp",
  heavy: "/media/fabrics/wool-hemp-canvas-primary.webp",
  soft: "/media/fabrics/brushed-flannel-primary.webp",
  sheer: "/media/fabrics/silk-chiffon-primary.webp",
  textured: "/media/fabrics/fine-wale-corduroy-primary.webp",
  mesh: "/media/fabrics/stretch-woven-compression-primary.webp",
  canvas: "/media/fabrics/wool-hemp-canvas-primary.webp",
  fleece: "/media/fabrics/pima-cotton-fleece-primary.webp",
  jersey: "/media/fabrics/mercerized-cotton-jersey-primary.webp",
  terry: "/media/fabrics/pima-cotton-fleece-primary.webp",
  corduroy: "/media/fabrics/fine-wale-corduroy-primary.webp",
  flannel: "/media/fabrics/brushed-flannel-primary.webp",
  twill: "/media/fabrics/egyptian-cotton-twill-primary.webp",
  crepe: "/media/fabrics/silk-georgette-primary.webp",
  wholesale: "/media/fabrics/cotton-poplin-primary.webp",
  silk: "/media/fabrics/silk-satin-primary.webp",
  polyester: "/media/fabrics/wool-hemp-canvas-primary.webp",
  active: "/media/fabrics/stretch-woven-compression-primary.webp",
  pique: "/media/fabrics/birdseye-cotton-pique-primary.webp",
} as const;

export type SeedRow = [
  id: number,
  keyword: string,
  group: SeedGroup,
  topic: string,
  existingCanonical: string,
  peerKeyword: string,
  peer2Keyword: string,
  primaryUse: string,
  imageKey: keyof typeof IMG,
  imageAlt: string,
  collectionPath: string,
  bestForPath: string,
  facts: [
    definition: string,
    makeup: string,
    feel: string,
    weight: string,
    uses: string,
    strengths: string,
    limits: string,
    care: string,
    sampling: string,
    climate: string,
    mistake: string,
    specCheck: string,
  ],
];

function slugify(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

const ROWS: readonly SeedRow[] = [
  [
    1,
    "cotton fabric",
    "material",
    "cotton",
    "/collections/cotton/",
    "linen fabric",
    "polyester fabric",
    "shirts",
    "cotton",
    "Crisp cotton poplin folds used for shirts and dresses",
    "/collections/cotton/",
    "/fabrics/best-for/shirts/",
    [
      "Cotton is a plant fibre spun into yarns, then woven or knitted into cloth.",
      "A cotton brief should name fibre, yarn, weave or knit, and any stretch.",
      "Hand ranges from crisp poplin to soft jersey or brushed flannel.",
      "Shirtings sit lighter than denim, canvas, or fleece cottons.",
      "Shirts, dresses, trousers, uniforms, and many home textiles.",
      "Familiar to factories and easy to dye when the mill process is sound.",
      "It can wrinkle, shrink, and show through in pale, open weaves.",
      "Many cottons accept home wash, but finish still needs a published care line.",
      "Sample the colourway you will cut. White does not prove a dark cloth.",
      "Light open cottons suit warm weather. Heavier cottons work as layers.",
      "Treating poplin, voile, jersey, and canvas as the same cotton.",
      "Composition, construction, published weight, width, and care.",
    ],
  ],
  [
    2,
    "linen fabric",
    "material",
    "linen",
    "/collections/linen-lightweight/",
    "cotton fabric",
    "hemp fabric",
    "dresses",
    "linen",
    "Natural linen cloth with a dry hand and visible slub",
    "/collections/linen-lightweight/",
    "/fabrics/best-for/dresses/",
    [
      "Linen is flax fibre spun and woven, often with a dry, slubby character.",
      "State flax content, weave, and whether the cloth is washed or loom-state.",
      "Dry and cool. Washed linen hangs softer than stiff loom-state linen.",
      "Apparel linen is often light to mid-weight. Trouser linens can sit heavier.",
      "Summer shirts, dresses, trousers, blouses, and some home cloth.",
      "Breathable and distinctive when the yarn character is kept.",
      "It wrinkles. Cheap blends can lose the flax feel.",
      "Wash or steam can change size and drape. Follow the fabric page.",
      "Judge drape after finishing, not only on the roll.",
      "Often chosen for warm weather because air moves through the cloth.",
      "Expecting linen to stay perfectly smooth in daily wear.",
      "Flax content, weave, weight, width, and finish.",
    ],
  ],
  [
    3,
    "wool fabric",
    "material",
    "wool",
    "/fabrics/wool-fabric/",
    "cotton fabric",
    "fleece fabric",
    "coats",
    "wool",
    "Fine wool suiting with a smooth woven surface",
    "/collections/tailoring/",
    "/fabrics/best-for/tailoring/",
    [
      "Wool is a protein fibre from sheep, used in both wovens and knits.",
      "Name wool type, blend, and whether the cloth is worsted, woollen, or knit.",
      "Springy and warm. Worsted feels smoother. Woollen yarn feels loftier.",
      "Tropical suiting is relatively light. Coatings are heavy.",
      "Suits, trousers, jackets, coats, knitwear, and some uniforms.",
      "Recovery and a tailored hand when construction matches the garment.",
      "Heat and agitation can felt or shrink wool. Humid heat can feel heavy.",
      "Often dry clean or gentle care. Use the published care line.",
      "Sample suiting for tailoring, not a sweater knit, if the brief is woven.",
      "Strong in cool weather. Light worsteds still appear in milder seasons.",
      "Comparing wool as a fibre with twill as a weave.",
      "Composition, construction, weight, width, and yarn system.",
    ],
  ],
  [
    4,
    "knit fabric",
    "construction",
    "knit",
    "/guides/woven-vs-knit-fabrics/",
    "jersey fabric",
    "stretch fabric",
    "t-shirts",
    "knit",
    "Close looped surface of a mercerized cotton jersey knit",
    "",
    "/fabrics/best-for/knitwear/",
    [
      "Knit fabric is made by looping yarns. It usually stretches more than a comparable woven.",
      "Name knit type, fibre, gauge, and stretch if the mill publishes it.",
      "Soft and mobile. Fine gauges feel smoother than open loops.",
      "Fine jersey can be very light. Fleece and heavy interlock sit heavier.",
      "T-shirts, dresses, loungewear, activewear, and knitwear.",
      "Comfort and movement when recovery is adequate.",
      "Can grow, ladder, or show through when stretched. Edges may curl.",
      "Less agitation and lower heat help many knits keep shape.",
      "Stretch the sample as the garment will fit. Cover changes on the body.",
      "Light knits for warm weather. Dense or brushed knits for cooler weather.",
      "Calling every knit jersey. Rib, interlock, and terry are different.",
      "Knit type, fibre, weight, width, and recovery notes.",
    ],
  ],
  [
    5,
    "denim fabric",
    "material",
    "denim",
    "/collections/denim/",
    "canvas fabric",
    "twill fabric",
    "jeans",
    "denim",
    "Lightweight denim with a diagonal twill surface",
    "/collections/denim/",
    "/fabrics/best-for/trousers/",
    [
      "Denim is usually a twill, often cotton, with a coloured warp and paler weft.",
      "Record fibre, weight, stretch, and whether it is mill or selvedge denim.",
      "Firm at first. Softer after wash. Stretch denim feels more elastic.",
      "Shirt denim is far lighter than heavy jean ounces.",
      "Jeans, jackets, skirts, workwear, and some shirts.",
      "Durable face and a clear visual identity.",
      "Shrinkage, twist, and colour crocking should be tested.",
      "Wash rules depend on finish and stretch.",
      "Wash a sample if the garment will be washed. Measure size change.",
      "Light denim for warm weather. Heavy denim for cooler weather and work.",
      "Using shirt-weight denim for jeans, or jeans-weight denim for a light shirt.",
      "Fibre, construction, weight, stretch, width, and finish.",
    ],
  ],
  [
    6,
    "viscose fabric",
    "material",
    "viscose",
    "/discover/viscose/",
    "rayon fabric",
    "cotton fabric",
    "dresses",
    "viscose",
    "Fluid viscose-like drape shown on a fine georgette surface",
    "",
    "/fabrics/best-for/dresses/",
    [
      "Viscose is a regenerated cellulose fibre. Many viscose cloths drape softly.",
      "Ask for fibre content, construction, and wet-strength notes if published.",
      "Smooth and fluid. It can feel cooler than many polyesters.",
      "Dress viscose is often light. Heavier viscose twills exist for trousers.",
      "Dresses, blouses, linings, and fluid trousers.",
      "Drape and colour when dyeing is controlled.",
      "Can weaken when wet. Shrinkage and seam slippage need tests.",
      "Follow the mill care line. Heat and wet handling can distort some viscose.",
      "Wash or steam a sample if the garment will be washed.",
      "Light viscose often appears in warm-weather dresses.",
      "Treating viscose and rayon as identical without reading the mill name.",
      "Fibre name, construction, weight, width, and wet handling notes.",
    ],
  ],
  [
    7,
    "rayon fabric",
    "material",
    "rayon",
    "/discover/rayon/",
    "viscose fabric",
    "satin fabric",
    "dresses",
    "rayon",
    "Soft rayon-like drape on a fine woven surface",
    "",
    "/fabrics/best-for/dresses/",
    [
      "Rayon is a family name for regenerated cellulose fibres, including viscose in many markets.",
      "Confirm the mill name on the page. Do not assume modal, lyocell, and viscose behave the same.",
      "Often smooth and fluid. Some rayons feel drier than others.",
      "Dress weights are usually light. Suiting rayons can sit heavier.",
      "Dresses, blouses, linings, and some knits.",
      "Soft drape and easy colour when processing is sound.",
      "Wet strength, shrinkage, and pilling vary by process.",
      "Use the published care line. Some rayons need gentle wash.",
      "Sample the named fibre, not a generic “rayon” substitute.",
      "Light rayons are common in warm-weather dresses.",
      "Buying on the word rayon without checking process and construction.",
      "Exact fibre name, construction, weight, and care.",
    ],
  ],
  [
    8,
    "chiffon fabric",
    "material",
    "chiffon",
    "/discover/chiffon/",
    "satin fabric",
    "sheer fabric",
    "dresses",
    "chiffon",
    "Sheer silk chiffon with a fine, airy weave",
    "",
    "/fabrics/best-for/dresses/",
    [
      "Chiffon is a light, sheer woven, often in silk or polyester.",
      "Name fibre, sheer level, and whether it is silk or synthetic chiffon.",
      "Airy and slightly grainy. It floats rather than hangs like satin.",
      "Almost always light. Do not treat it as a lining-weight cloth.",
      "Evening dresses, overlays, blouses, and scarves.",
      "Sheer movement and a fine face when yarns are even.",
      "Snags, seam slippage, and show-through. It needs careful cutting.",
      "Gentle care. Heat can melt some polyester chiffons.",
      "Hold the sample over skin and lining. Judge opacity in use.",
      "Often used for warm-weather and evening overlays.",
      "Using chiffon as a self-lining when it is too sheer.",
      "Fibre, sheer level, weight, width, and lining plan.",
    ],
  ],
  [
    9,
    "velvet fabric",
    "material",
    "velvet",
    "/discover/velvet/",
    "satin fabric",
    "corduroy fabric",
    "dresses",
    "velvet",
    "Crushed velvet pile with directional light and shade",
    "",
    "/fabrics/best-for/dresses/",
    [
      "Velvet is a pile cloth. Light and shade change with pile direction.",
      "Name pile fibre, ground fibre, pile height, and crush or not.",
      "Soft and dense when pile is even. Crushed velvet looks more broken.",
      "Apparel velvets range from light dress pile to heavier coating pile.",
      "Dresses, jackets, upholstery, and evening separates.",
      "Rich face and a clear evening or winter identity.",
      "Marks, crush, and pile lean. Seating and packing can flatten pile.",
      "Often specialist clean. Steam and pressure can crush pile.",
      "Brush and hang a sample. Check pile direction across a panel.",
      "Heavier velvets read as cool-weather or indoor evening cloth.",
      "Ignoring pile direction when cutting panels.",
      "Pile fibre, ground, pile height, weight, and care.",
    ],
  ],
  [
    10,
    "satin fabric",
    "material",
    "satin",
    "/discover/satin/",
    "chiffon fabric",
    "silk fabric",
    "dresses",
    "satin",
    "Smooth silk satin with a reflective woven face",
    "",
    "/fabrics/best-for/dresses/",
    [
      "Satin is a weave with a smooth, reflective face. Fibre can be silk, polyester, or acetate.",
      "Name fibre, weave, and whether the reverse is dull or also shiny.",
      "Slippery and smooth. It catches light more than crepe or poplin.",
      "Charmeuse is relatively light. Duchesse satin is heavier.",
      "Dresses, linings, sleepwear, and evening separates.",
      "Lustre and fluid hang when fibre and finish match the brief.",
      "Snags, seam slippage, and heat shine. Pins can leave marks.",
      "Gentle care. High heat can glaze some satins.",
      "Drape a sample over a form. Judge both face shine and reverse.",
      "Used year-round for evening, and in lighter weights for warm weather.",
      "Calling every shiny cloth satin without checking weave and fibre.",
      "Fibre, weave, weight, width, and shine level.",
    ],
  ],
];

export { IMG, ROWS, slugify };

export function buildSeedRecords(
  extra: readonly SeedRow[] = [],
): readonly SeedRecord[] {
  return [...ROWS, ...extra].map((row) => {
    const [
      id,
      keyword,
      group,
      topic,
      existingCanonical,
      peerKeyword,
      peer2Keyword,
      primaryUse,
      imageKey,
      imageAlt,
      collectionPath,
      bestForPath,
      facts,
    ] = row;
    return {
      id,
      keyword,
      slug: slugify(keyword),
      group,
      topic,
      existingCanonical,
      peerKeyword,
      peerSlug: slugify(peerKeyword),
      peer2Keyword,
      peer2Slug: slugify(peer2Keyword),
      primaryUse,
      useSlug: slugify(primaryUse),
      collectionPath: collectionPath || undefined,
      bestForPath: bestForPath || undefined,
      image: IMG[imageKey],
      imageAlt,
      definition: facts[0],
      makeup: facts[1],
      feel: facts[2],
      weight: facts[3],
      uses: facts[4],
      strengths: facts[5],
      limits: facts[6],
      care: facts[7],
      sampling: facts[8],
      climate: facts[9],
      mistake: facts[10],
      specCheck: facts[11],
    };
  });
}
