import type { SeedGroup } from "./types";
import type { SeedRow } from "./seeds";
import { IMG } from "./seeds";

function r(
  id: number,
  keyword: string,
  group: SeedGroup,
  topic: string,
  existingCanonical: string,
  peerKeyword: string,
  peer2Keyword: string,
  primaryUse: string,
  imageKey: keyof typeof IMG,
  imageAlt: string,
  collectionPath: string,
  bestForPath: string,
  definition: string,
  makeup: string,
  feel: string,
  weight: string,
  uses: string,
  strengths: string,
  limits: string,
  care: string,
  sampling: string,
  climate: string,
  mistake: string,
  specCheck: string,
): SeedRow {
  return [
    id,
    keyword,
    group,
    topic,
    existingCanonical,
    peerKeyword,
    peer2Keyword,
    primaryUse,
    imageKey,
    imageAlt,
    collectionPath,
    bestForPath,
    [
      definition,
      makeup,
      feel,
      weight,
      uses,
      strengths,
      limits,
      care,
      sampling,
      climate,
      mistake,
      specCheck,
    ],
  ];
}

export const SEED_ROWS_81_100: readonly SeedRow[] = [
  r(
    81,
    "dress fabric",
    "application",
    "dress fabric",
    "/fabrics/best-for/dresses/",
    "fabric for dresses",
    "fashion fabric",
    "dresses",
    "satin",
    "Satin folds used as dress fabric",
    "",
    "/fabrics/best-for/dresses/",
    "Dress fabric is cloth specified for a dress block. It is not a fibre name.",
    "Silhouette, lining, stretch, and opacity belong in the first line of the brief.",
    "Slip dresses need fluid cloth. Shirt dresses need more stability.",
    "Mass follows silhouette. A ball gown and a sundress do not share one GSM band.",
    "Day, work, and evening dresses.",
    "A dress that hangs as sketched when cloth matches the block.",
    "Using leftover suiting because it is in stock.",
    "Wearer care should be realistic for the dress category.",
    "Toile first in a similar drape.",
    "Light unlined dresses for warm weather. Lined or heavier cloths for cooler weather.",
    "Calling every shiny cloth dress fabric.",
    "Block, drape, opacity, mass, and lining.",
  ),
  r(
    82,
    "shirt fabric",
    "application",
    "shirt fabric",
    "/fabrics/best-for/shirts/",
    "fabric for shirts",
    "clothing fabric",
    "shirts",
    "cotton",
    "Cotton poplin used as shirt fabric",
    "",
    "/fabrics/best-for/shirts/",
    "Shirt fabric is cloth for a shirt block: collar, placket, and cuff need stability or a planned knit substitute.",
    "Woven shirting and jersey tees are both shirts only if the pattern agrees.",
    "Crisp poplins hold a collar. Soft voiles need interlining plans.",
    "Usually lighter than trouser cloth in the same fibre.",
    "Dress shirts, overshirts, and knit shirts.",
    "A clean front when opacity and shrinkage are tested.",
    "Chest show-through and shrinking collars.",
    "Shirts are washed often.",
    "Collar sew test plus wash test.",
    "Linen and voile for heat. Flannel and heavy twill for cold.",
    "Using coat canvas as shirt fabric.",
    "Stability, opacity, mass, and wash.",
  ),
  r(
    83,
    "clothing fabric",
    "application",
    "clothing fabric",
    "/guides/",
    "fabric for clothing",
    "fashion fabric",
    "apparel",
    "cotton",
    "Everyday cotton cloth used as clothing fabric",
    "",
    "/fabrics/best-for/shirts/",
    "Clothing fabric means apparel cloth. The next word in the brief should be the garment.",
    "Split knits and wovens. Split next-to-skin and outer layers.",
    "Hand is judged in wear.",
    "There is no single clothing GSM.",
    "The whole apparel rack, once specified.",
    "A practical search only when it leads to a garment type.",
    "A generic clothing fabric PO.",
    "Care must match the wearer.",
    "Sample by garment, not by slogan.",
    "Season is per garment.",
    "One cloth for coats and underwear.",
    "Garment, construction, mass, and care.",
  ),
  r(
    84,
    "fashion fabric",
    "application",
    "fashion fabric",
    "/guides/",
    "designer fabric",
    "premium fabric",
    "collections",
    "satin",
    "Satin used as an example of fashion fabric",
    "",
    "/fabrics/best-for/dresses/",
    "Fashion fabric is apparel cloth used in seasonal collections. It still needs a spec, not only a look.",
    "Write silhouette and tests even when the collection is fashion-led.",
    "Look is not hand. Sample it.",
    "Fashion week photos do not include GSM. Add it.",
    "Ready-to-wear and capsule collections.",
    "Expression when construction still works in wear.",
    "Buying a look with no wash plan.",
    "Wearer care still matters after the show.",
    "Wear-test a sample garment.",
    "Seasonal stories should match actual climate comfort.",
    "Using fashion fabric as a quality grade.",
    "Look, spec, tests, and care.",
  ),
  r(
    85,
    "designer fabric",
    "application",
    "designer fabric",
    "/guides/",
    "fashion fabric",
    "luxury fabric",
    "collections",
    "jacquard",
    "Jacquard used in designer fabric conversations",
    "",
    "/fabrics/best-for/dresses/",
    "Designer fabric is a retail phrase. On a mill page it should still resolve to fibre, construction, and mass.",
    "Ask whether designer means a named house, a print designer, or a price band. Those are different.",
    "Hand still comes from yarn and finish.",
    "Designer is not a GSM.",
    "Collection development.",
    "A useful search only if it leads to a named cloth.",
    "Paying for a word instead of a spec.",
    "Care is still mill care.",
    "Sample the named quality.",
    "Climate follows construction.",
    "Assuming designer means better tests.",
    "Named cloth, spec, and tests.",
  ),
  r(
    86,
    "premium fabric",
    "application",
    "premium fabric",
    "/guides/",
    "luxury fabric",
    "designer fabric",
    "collections",
    "wool",
    "Fine wool used as one premium fabric example",
    "",
    "/fabrics/best-for/tailoring/",
    "Premium fabric is a value word. Define it with yarn, finish, testing, and handle, not with adjectives alone.",
    "Write what premium means in the brief: fibre grade, mill, or finishing.",
    "A premium hand should survive sampling and wash or clean tests.",
    "Premium is not automatically heavy or light.",
    "Tailoring, dresses, and shirts when the definition is written.",
    "Clearer QC when premium has tests.",
    "Premium as an excuse to skip GSM.",
    "Care should protect the finish you paid for.",
    "Compare two samples blind if you can.",
    "Comfort still follows construction.",
    "Using premium as a substitute for a mill name.",
    "Definition, tests, spec, and sample.",
  ),
  r(
    87,
    "luxury fabric",
    "application",
    "luxury fabric",
    "/guides/",
    "premium fabric",
    "silk fabric",
    "occasionwear",
    "silk",
    "Silk satin used as one luxury fabric example",
    "",
    "/fabrics/best-for/dresses/",
    "Luxury fabric is a market word. Useful pages still name silk, fine wool, or a finishing process.",
    "Replace luxury with fibre, origin claim only if evidenced, and construction.",
    "Luxury should be felt, then tested.",
    "Luxury is not a mass band.",
    "Occasionwear and high-price ready-to-wear.",
    "A richer face when yarn and finish match.",
    "Luxury language hiding polyester substitution.",
    "Specialist care is common. Write it.",
    "Sample in the light the customer will see.",
    "Occasion climate is indoor as often as outdoor.",
    "Treating luxury as a fibre.",
    "Fibre, construction, evidence, and care.",
  ),
  r(
    88,
    "fabric for activewear",
    "performance",
    "activewear fabric",
    "/fabrics/best-for/activewear/",
    "sportswear fabric",
    "moisture wicking fabric",
    "activewear",
    "active",
    "Stretch technical cloth used for activewear",
    "",
    "/fabrics/best-for/activewear/",
    "Fabric for activewear needs stretch or pattern ease, moisture management, and recovery after movement.",
    "Name the sport, coverage, and whether compression is required.",
    "Power meshes feel firmer than cotton jersey. Do not swap them silently.",
    "Mass should match coverage and support, not a fashion GSM guess.",
    "Tights, tops, bras, and outer layers.",
    "Movement when recovery is real.",
    "See-through on stretch. Heat if vapour cannot leave.",
    "Chlorine, sweat, and heat set their own care rules.",
    "Stretch on the body. Check cover at the squat if relevant.",
    "Heat and sweat are the climate. Outdoor cold needs a different layer.",
    "Using dress satin as a training tight.",
    "Sport, stretch, cover, and moisture path.",
  ),
  r(
    89,
    "moisture wicking fabric",
    "performance",
    "moisture wicking",
    "/discover/moisture-wicking-fabric/",
    "quick dry fabric",
    "breathable fabric",
    "sportswear",
    "active",
    "Technical stretch cloth used in moisture-wicking programs",
    "",
    "/fabrics/best-for/activewear/",
    "Moisture wicking fabric moves liquid sweat along yarns so it can evaporate. It is a behaviour, not a colour.",
    "Ask whether wicking is from fibre, knit structure, or finish, and whether it survives wash.",
    "A dry face can still sit on a wet back if the system fails.",
    "Mass still matters. A heavy wickable cloth can feel hot.",
    "Sportswear, uniforms, and some underwear.",
    "Comfort in sweat when the path to evaporation exists.",
    "Finishes that wash off. Cotton that absorbs but dries slowly.",
    "Re-test after wash if wicking is claimed.",
    "Sweat or drop tests on a washed sample if you rely on the claim.",
    "Most relevant during exercise and in heat.",
    "Printing moisture wicking on any polyester jersey.",
    "Mechanism, wash survival, construction, and mass.",
  ),
  r(
    90,
    "quick dry fabric",
    "performance",
    "quick dry",
    "/discover/quick-dry-fabric/",
    "moisture wicking fabric",
    "sportswear fabric",
    "travel and sport",
    "active",
    "Light technical cloth associated with quicker drying",
    "",
    "/fabrics/best-for/activewear/",
    "Quick dry fabric returns to a dry hand faster after wetting. Thin synthetics often dry faster than heavy cottons, but construction rules.",
    "Do not treat quick dry as waterproof. Drying speed and water resistance are different.",
    "A thin knit can feel clammy if it does not wick, even if it dries fast on a line.",
    "Lighter cloths often dry faster, all else equal.",
    "Travel shirts, sports, and some uniforms.",
    "Shorter wet time when the construction is honest.",
    "Odour in some synthetics. Heat if the cloth is dense.",
    "Line dry claims should match the care line.",
    "Wet and time a sample if drying speed is a buying reason.",
    "Useful in humid heat and after sport.",
    "Calling coated waterproof cloth quick dry without a test.",
    "Construction, mass, and a drying check.",
  ),
  r(
    91,
    "sportswear fabric",
    "performance",
    "sportswear fabric",
    "/fabrics/best-for/activewear/",
    "fabric for activewear",
    "breathable sports fabric",
    "sportswear",
    "active",
    "Compression-style stretch cloth used as sportswear fabric",
    "",
    "/fabrics/best-for/activewear/",
    "Sportswear fabric is cloth for sport garments. The sport still has to be named.",
    "Split running, training, racket, and field. Abrasion and stretch needs differ.",
    "Support cloths feel firmer than lifestyle jersey.",
    "Mass follows support and coverage.",
    "Jerseys, tights, shells, and socks are different specs.",
    "Performance when tests match the sport.",
    "Lifestyle jersey sold as match kit.",
    "Sweat, heat set, and sometimes chlorine.",
    "Move in a sample garment.",
    "Outdoor sport adds wind and rain. Indoor sport adds sweat and friction.",
    "One sportswear fabric line for every sport.",
    "Sport, stretch, abrasion, and cover.",
  ),
  r(
    92,
    "breathable sports fabric",
    "performance",
    "breathable sports",
    "/fabrics/best-for/activewear/",
    "breathable fabric",
    "sportswear fabric",
    "sportswear",
    "active",
    "Open technical cloth used as breathable sports fabric",
    "",
    "/fabrics/best-for/activewear/",
    "Breathable sports fabric is cloth that moves vapour during exercise. Open knits and some membranes are different systems.",
    "Name the system. A mesh panel is not a waterproof-breathable laminate.",
    "Open cloths feel airy. Laminates feel more closed but may still move vapour if designed to.",
    "Light open knits often feel cooler than coated shells.",
    "Training tops, jerseys, and some shells.",
    "Lower heat build-up when vapour can leave.",
    "Calling any mesh breathable without checking hole size and lining.",
    "Finishes can clog. Wash as instructed.",
    "Exercise in the sample if the claim matters.",
    "Heat and sweat are the climate that matters.",
    "Using a rain shell as a training tee.",
    "System, construction, mass, and lining.",
  ),
  r(
    93,
    "outdoor fabric",
    "performance",
    "outdoor fabric",
    "/fabrics/best-for/outerwear/",
    "waterproof fabric",
    "canvas fabric",
    "outdoor clothing",
    "waterproof",
    "Ripstop used as an outdoor fabric example",
    "",
    "/fabrics/best-for/outerwear/",
    "Outdoor fabric is cloth for weather, abrasion, or load outside. Rain, sun, and pack wear are different briefs.",
    "Name rain, UV, tear, and whether seams will be taped.",
    "Ripstops feel crisper than apparel satins.",
    "Shells vary from light windshirts to heavy packs.",
    "Jackets, trousers, tents, and bags.",
    "Protection when the system is complete.",
    "Fashion canvas sold as a mountain shell.",
    "DWR and coatings change after wash.",
    "Test the claim you are buying. Do not invent hydrostatic numbers.",
    "Weather is the climate. Indoor luxury is a different page.",
    "Using dress velvet as outdoor cloth.",
    "Hazard, barrier, mass, and seams.",
  ),
  r(
    94,
    "flame retardant fabric",
    "performance",
    "flame retardant",
    "/discover/flame-retardant-fabric/",
    "outdoor fabric",
    "upholstery fabric",
    "workwear",
    "canvas",
    "Dense canvas-like cloth used when discussing flame-retardant programs",
    "",
    "/fabrics/best-for/workwear/",
    "Flame retardant fabric is cloth that meets a named flammability standard. The standard name matters more than the adjective.",
    "Ask which standard, which test method, and whether the FR is inherent or a finish.",
    "FR finishes can change hand. Inherent FR fibres feel like their fibre family.",
    "Mass still belongs on the spec.",
    "Workwear, interiors, and some event cloth, when certified for that use.",
    "A documented test when the end use requires it.",
    "The words flame retardant without a standard.",
    "Some FR finishes change with wash. Follow the stated care and remaining life rules.",
    "Request the standard name with the sample. Do not invent a pass.",
    "This is a safety spec, not a season spec.",
    "Printing FR on a fashion cloth without a method.",
    "Standard name, inherent vs finish, mass, and care life.",
  ),
  r(
    95,
    "recycled polyester fabric",
    "performance",
    "recycled polyester",
    "/discover/recycled-polyester/",
    "recycled fabric",
    "wholesale polyester fabric",
    "sportswear",
    "recycled",
    "Recycled polyester ripstop used as a recycled polyester example",
    "",
    "/fabrics/best-for/activewear/",
    "Recycled polyester fabric is polyester with recycled content. The page should say how much and from what.",
    "Ask for content percentage if published, and whether the claim is third-party evidenced.",
    "Hand is still polyester unless otherwise finished.",
    "Mass follows construction, not the recycled headline.",
    "Sportswear, shells, bags, and some fashion wovens.",
    "A materials claim some programs require, when evidenced.",
    "Assuming recycled polyester is automatically lower impact in every factory step.",
    "Care follows polyester.",
    "Test pilling and colour as you would for virgin polyester.",
    "Comfort follows construction.",
    "Using recycled polyester as a synonym for sustainable with no other facts.",
    "Content, evidence, construction, mass, and tests.",
  ),
  r(
    96,
    "sustainable textile",
    "sourcing",
    "sustainable textile",
    "/discover/sustainable-fabric/",
    "sustainable fabric",
    "textile sourcing",
    "programs",
    "sustainable",
    "Linen used in sustainable textile discussions",
    "",
    "/fabrics/best-for/shirts/",
    "Sustainable textile is a claim across fibre, yarn, or cloth. Name the issue and the evidence.",
    "Split fibre, chemistry, energy, water, waste, and durability. One word cannot cover all.",
    "A sustainable textile still has a hand. Sample it.",
    "No sustainable GSM exists.",
    "Apparel and interiors programs with written goals.",
    "A better RFQ when issues are split.",
    "A poster word with no evidence pack.",
    "Durability is part of the conversation. A cloth that fails early is wasteful.",
    "Attach evidence to the sample.",
    "Climate comfort is still construction.",
    "Ranking one fibre as always best.",
    "Issue list, evidence, spec, and sample.",
  ),
  r(
    97,
    "textile sourcing",
    "sourcing",
    "textile sourcing",
    "/fabric-sourcing/",
    "fabric sourcing",
    "textile sourcing company",
    "programs",
    "wholesale",
    "Cotton cloth used as a textile sourcing brief example",
    "/fabric-sourcing/",
    "",
    "Textile sourcing is buying fibre, yarn, or cloth against a brief. On FabStitch the practical path is usually finished fabric.",
    "Write the layer: fibre, yarn, or fabric. Then write tests and quantity.",
    "The arrived goods are the result, not the search term.",
    "GSM is for fabric layer sourcing.",
    "Brands, mills, and converters.",
    "Fewer missed layers when the RFQ is precise.",
    "Sourcing yarn language for a cutting room that needs cloth.",
    "Testing sits inside sourcing.",
    "Sample the layer you will process next.",
    "Teams in FabStitch’s seven markets still write RFQs the same way.",
    "Starting from a country name instead of a spec.",
    "Layer, brief, sample, and tests.",
  ),
  r(
    98,
    "fabric sourcing company",
    "sourcing",
    "fabric sourcing company",
    "/fabric-sourcing/",
    "fabric sourcing",
    "textile sourcing company",
    "programs",
    "wholesale",
    "Cotton poplin used when evaluating a fabric sourcing company",
    "/fabric-sourcing/",
    "",
    "A fabric sourcing company helps find and buy cloth. It is not itself a fibre.",
    "Ask what they own: mill relationships, inventory, testing, or only introductions.",
    "You still sample cloth.",
    "A company name does not replace GSM.",
    "Brands without a mill team.",
    "Time saved when the brief is clear.",
    "A company that will not attach mill identity or tests.",
    "Care remains mill care.",
    "Keep samples labelled with mill quality names.",
    "Do not invent which countries the company covers.",
    "Hiring a sourcing company instead of writing a brief.",
    "Role, mill identity, spec, and sample.",
  ),
  r(
    99,
    "textile sourcing company",
    "sourcing",
    "textile sourcing company",
    "/fabric-sourcing/",
    "fabric sourcing company",
    "textile sourcing",
    "programs",
    "wholesale",
    "Technical cloth used when evaluating a textile sourcing company",
    "/fabric-sourcing/",
    "",
    "A textile sourcing company may work at fibre, yarn, or fabric layer. Confirm the layer.",
    "Ask for the layer map and the sample path.",
    "Yarn sourcing will not drape like cloth.",
    "GSM only when the output is fabric.",
    "Teams buying across layers.",
    "Clearer scopes.",
    "A company title with no layer map.",
    "Finished cloth still needs care lines.",
    "Sample the output layer.",
    "Keep geography on documents, not in slogans.",
    "Using textile sourcing company as a mill substitute without identity.",
    "Layer map, identity, spec, and sample.",
  ),
  r(
    100,
    "B2B fabric marketplace",
    "commercial",
    "B2B fabric marketplace",
    "/marketplace/",
    "fabric marketplace",
    "fabric wholesale",
    "source cloth",
    "cotton",
    "Cotton cloth on a B2B fabric marketplace browsing path",
    "/marketplace/",
    "",
    "A B2B fabric marketplace is built for business buyers who need mill cloth, specs, and enquiry, not only a retail fat quarter.",
    "Use filters, open named fabric pages, and enquire with a brief. The marketplace is not one mill.",
    "Sample the shortlist. B2B still has hand-feel.",
    "Each listing still needs its own mass data when published.",
    "Brands, wholesalers, and product teams.",
    "Discovery across mills with a shared catalogue language.",
    "B2B used as a synonym for untested cloth.",
    "Care is per named fabric.",
    "Enquire after reading the spec.",
    "FabStitch serves buyers in the United States, United Kingdom, Turkey, Pakistan, India, Bangladesh, and Singapore. Listing facts stay on listings.",
    "Treating the marketplace as a factory with invented capacity.",
    "Named fabric, brief, enquiry, and sample.",
  ),
];
