import type { SeedGroup } from "./types";
import type { SeedRow } from "./seeds";
import { IMG } from "./seeds";

function r(
  id: number,
  keyword: string,
  group: SeedGroup,
  topic: string,
  existingCanonical: string,
  peerKeyword: string,
  peer2Keyword: string,
  primaryUse: string,
  imageKey: keyof typeof IMG,
  imageAlt: string,
  collectionPath: string,
  bestForPath: string,
  definition: string,
  makeup: string,
  feel: string,
  weight: string,
  uses: string,
  strengths: string,
  limits: string,
  care: string,
  sampling: string,
  climate: string,
  mistake: string,
  specCheck: string,
): SeedRow {
  return [
    id,
    keyword,
    group,
    topic,
    existingCanonical,
    peerKeyword,
    peer2Keyword,
    primaryUse,
    imageKey,
    imageAlt,
    collectionPath,
    bestForPath,
    [
      definition,
      makeup,
      feel,
      weight,
      uses,
      strengths,
      limits,
      care,
      sampling,
      climate,
      mistake,
      specCheck,
    ],
  ];
}

export const SEED_ROWS_51_80: readonly SeedRow[] = [
  r(
    51,
    "fabric manufacturers",
    "commercial",
    "fabric manufacturers",
    "/fabric-sourcing/",
    "fabric manufacturer",
    "textile manufacturers",
    "mill programs",
    "wholesale",
    "Several woven qualities used when comparing fabric manufacturers",
    "/fabric-sourcing/",
    "",
    "Fabric manufacturers as a search is a mill shortlist. Compare processes, not adjectives.",
    "Table weaving, knitting, dyeing, and coating. Many mills do not do all four.",
    "Rank by sample against the same brief.",
    "Each mill quality still needs mass data.",
    "Sourcing teams building mill maps.",
    "Process fit when the map is honest.",
    "Long lists with no process column.",
    "Finishing differences change care.",
    "Sample two mills on the same construction when possible.",
    "Mill maps may include more than one of FabStitch’s target markets.",
    "Choosing a mill for geography instead of process fit.",
    "Process table, spec, and paired samples.",
  ),
  r(
    52,
    "textile manufacturer",
    "commercial",
    "textile manufacturer",
    "/fabric-sourcing/",
    "fabric manufacturer",
    "textile manufacturers",
    "textile programs",
    "polyester",
    "Ripstop representing a textile manufacturer conversation",
    "/fabric-sourcing/",
    "",
    "A textile manufacturer may spin, weave, knit, or finish. Confirm the step you need.",
    "Write the step in the brief: spinning, weaving, knitting, dyeing, coating.",
    "A spinning mill sample is yarn. A weaving mill sample is cloth.",
    "GSM is for cloth.",
    "Brands and converters buying at the right step.",
    "Less confusion when the step is named.",
    "A manufacturer title with no step list.",
    "Care starts at finished cloth.",
    "Sample the output of the step you will buy.",
    "Do not invent which country a mill is in unless the listing says so.",
    "Using textile manufacturer as a prestige synonym for trader.",
    "Step, output, spec, and sample.",
  ),
  r(
    53,
    "textile manufacturers",
    "commercial",
    "textile manufacturers",
    "/fabric-sourcing/",
    "textile manufacturer",
    "fabric manufacturers",
    "textile programs",
    "polyester",
    "Multiple technical cloths compared across textile manufacturers",
    "/fabric-sourcing/",
    "",
    "Textile manufacturers in the plural is a map of steps and outputs.",
    "Group names by spinning, weaving, knitting, and finishing.",
    "Compare outputs, not websites.",
    "Finished cloth still needs mass.",
    "Vendor mapping for product teams.",
    "Clearer RFQs.",
    "Mixing yarn mills and garment factories in one list.",
    "Care instructions come with finished cloth.",
    "RFQ the same brief to two comparable mills.",
    "Keep country facts on listings. Do not invent clusters.",
    "Treating every textile manufacturer as a fabric mill.",
    "Step groups, RFQ, and samples.",
  ),
  r(
    54,
    "fabric store online",
    "commercial",
    "fabric store online",
    "/marketplace/",
    "online fabric store",
    "buy fabric online",
    "sample and cut",
    "cotton",
    "Cotton poplin as seen when browsing an online fabric store",
    "/marketplace/",
    "",
    "An online fabric store lists cloth to browse and buy through a website. Units may be cuts or rolls.",
    "Read unit of sale, width, fibre, and return or sample rules before you cart.",
    "Screen colour is not hand. Order a sample when the lot is large.",
    "Published GSM still matters in an online store.",
    "Makers, students, and small brands buying named cloth.",
    "Search and filters when listings are complete.",
    "Missing width, fibre, or unit of sale.",
    "Care should be on the product page.",
    "Start with a sample cut when the project is new.",
    "Online stores serve many countries. Shipping claims belong on checkout, not in this article.",
    "Buying from a photo thumbnail without opening the spec.",
    "Unit, width, fibre, and sample rules.",
  ),
  r(
    55,
    "buy fabric online",
    "commercial",
    "buy fabric online",
    "/marketplace/",
    "fabric store online",
    "fabric online",
    "named cloth",
    "cotton",
    "Folded cotton cloth representing an online fabric purchase",
    "/marketplace/",
    "",
    "Buy fabric online means completing a purchase of named cloth through a site, with a clear unit of sale.",
    "Confirm fibre, construction, quantity, and whether the lot can repeat.",
    "You cannot feel the site. You can feel a sample.",
    "Mass should be visible before payment when the mill publishes it.",
    "Small cuts and wholesale rolls, depending on the listing.",
    "Speed when the listing is complete.",
    "Paying for an unnamed cloth.",
    "Keep the care line with the order record.",
    "Sample first on a new mill quality.",
    "Buyers sit in many markets. Duties and delivery are checkout facts, not article facts.",
    "Buying the cheapest listing without a fibre line.",
    "Named cloth, unit, quantity, and sample.",
  ),
  r(
    56,
    "fabric online",
    "commercial",
    "fabric online",
    "/marketplace/",
    "buy fabric online",
    "fabric marketplace",
    "browse cloth",
    "cotton",
    "Online-ready cotton cloth photography for fabric browsing",
    "/marketplace/",
    "",
    "Fabric online is a browse intent. The useful result is a named cloth page with specs, not a mood image.",
    "Use filters for fibre, use, and construction. Open the spec before you save a favourite.",
    "Favourites are not samples.",
    "If GSM is published, read it while you browse.",
    "Discovery for makers and product teams.",
    "Fast comparison when cards include fibre and use.",
    "Endless scrolling with no spec.",
    "Care lives on the cloth page.",
    "Shortlist, then sample.",
    "Browsing is global. Availability is listing-specific.",
    "Saving photos instead of spec pages.",
    "Named page, filters, and shortlist.",
  ),
  r(
    57,
    "online fabric store",
    "commercial",
    "online fabric store",
    "/marketplace/",
    "fabric store online",
    "fabric marketplace",
    "named cloth",
    "cotton",
    "Store-style cotton folds used in online fabric store guides",
    "/marketplace/",
    "",
    "An online fabric store is a catalogue of cloth with checkout. It may serve cuts, rolls, or both.",
    "Read whether you are in a remnant shop or a mill marketplace. The unit of sale changes.",
    "Catalogue photography should not replace a sample on bulk.",
    "Mass belongs on each product, not in the store slogan.",
    "Repeatable styles and one-off makes.",
    "A stable catalogue when SKUs are real.",
    "Stores that change unnamed lots under the same photo.",
    "Keep care with the SKU.",
    "Ask whether the SKU repeats.",
    "Catalogue access is not the same as local warehouse claims.",
    "Treating every online store as mill-direct.",
    "SKU, unit, repeatability, and spec.",
  ),
  r(
    58,
    "fabric marketplace",
    "commercial",
    "fabric marketplace",
    "/marketplace/",
    "textile marketplace",
    "B2B fabric marketplace",
    "source cloth",
    "cotton",
    "Marketplace-style cotton cloth ready for discovery",
    "/marketplace/",
    "",
    "A fabric marketplace gathers many mill qualities so buyers can discover, compare, and enquire.",
    "Use search and filters, then open a named fabric page. Enquiry is not a substitute for a spec.",
    "Compare hands by sampling the shortlist.",
    "Each card still needs its own mass data when published.",
    "Brands and makers sourcing across many mills.",
    "Discovery across qualities without pretending one mill is every mill.",
    "Marketplaces that hide mill identity or fibre.",
    "Care remains per fabric.",
    "Enquire after the spec is read, not before.",
    "FabStitch is used from seven target markets. Listings still carry their own facts.",
    "Treating the marketplace as a single factory.",
    "Named fabric, filters, enquiry, and sample.",
  ),
  r(
    59,
    "textile marketplace",
    "commercial",
    "textile marketplace",
    "/marketplace/",
    "fabric marketplace",
    "B2B fabric marketplace",
    "source textiles",
    "polyester",
    "Technical cloth as listed in a textile marketplace browse",
    "/marketplace/",
    "",
    "A textile marketplace may list fibre, yarn, or cloth. On FabStitch the public catalogue is fabric-led.",
    "Filter to the product you can cut. Yarn language on a fabric marketplace is a mismatch.",
    "Sample cloth, not a textile adjective.",
    "GSM is for fabric listings.",
    "Apparel and textile buyers discovering mill cloth.",
    "A shared catalogue language.",
    "Mixing fibre commodity ads with finished fabric pages.",
    "Care is per fabric page.",
    "Stay on named fabric pages for apparel cutting.",
    "International buyers still need listing-level facts.",
    "Using textile marketplace as a fibre name.",
    "Product type, named page, and sample.",
  ),
  r(
    60,
    "fabric supplier online",
    "commercial",
    "fabric supplier online",
    "/marketplace/",
    "fabric supplier",
    "buy fabric online",
    "enquire cloth",
    "cotton",
    "Cotton cloth representing an online fabric supplier listing",
    "/marketplace/",
    "",
    "A fabric supplier online is a mill or trader you can reach through a website or marketplace listing.",
    "Read the listing owner, spec, and enquiry path. A contact form is not a spec pack.",
    "Ask for a sample through the documented path.",
    "Online does not remove GSM.",
    "Remote sourcing for product teams.",
    "Access without assuming a local showroom.",
    "Suppliers with only a social photo grid.",
    "Keep care with the named quality.",
    "Sample before a first bulk instruction.",
    "Online reach is not a warehouse claim.",
    "Enquiring with no brief.",
    "Owner, spec, enquiry, and sample.",
  ),
  r(
    61,
    "wholesale cotton fabric",
    "wholesale-type",
    "wholesale cotton",
    "/collections/cotton/",
    "cotton fabric",
    "wholesale linen fabric",
    "shirts",
    "cotton",
    "Cotton poplin prepared for wholesale cotton programs",
    "/collections/cotton/",
    "/fabrics/best-for/shirts/",
    "Wholesale cotton fabric is cotton cloth sold in mill units for repeating programs.",
    "Keep cotton construction in the brief: poplin, twill, jersey, or canvas are not one MOQ line.",
    "Sample the construction you will cut.",
    "Cotton GSM bands differ for shirts, denim, and fleece.",
    "Shirts, dresses, uniforms, and home programs.",
    "Familiar mill base when specs are written.",
    "One cotton MOQ covering every construction.",
    "Care follows the named cotton quality.",
    "Sample colourways. Shrinkage tests belong on cotton programs.",
    "Cotton is sourced internationally. Do not invent mill locations.",
    "Buying wholesale cotton as if it were one SKU.",
    "Construction, mass, width, MOQ, and shrink tests.",
  ),
  r(
    62,
    "wholesale linen fabric",
    "wholesale-type",
    "wholesale linen",
    "/collections/linen-lightweight/",
    "linen fabric",
    "wholesale cotton fabric",
    "dresses",
    "linen",
    "Flax linen prepared for wholesale linen programs",
    "/collections/linen-lightweight/",
    "/fabrics/best-for/dresses/",
    "Wholesale linen fabric is flax cloth in mill units. Washed and loom-state linen are different buys.",
    "State flax content, weave, and finish in the wholesale brief.",
    "Judge drape after the finish you will ship.",
    "Apparel linen mass is not furnishing linen mass.",
    "Summer shirts, dresses, and trousers.",
    "A distinctive fibre when lots are consistent.",
    "Wrinkle surprise if the brief promised a smooth synthetic.",
    "Wash tests change linen size.",
    "Wash a production-like sample.",
    "Often planned for warm-weather deliveries.",
    "Mixing hemp, ramie, and linen on one wholesale line without naming fibre.",
    "Flax content, finish, mass, width, and MOQ.",
  ),
  r(
    63,
    "wholesale denim fabric",
    "wholesale-type",
    "wholesale denim",
    "/collections/denim/",
    "denim fabric",
    "wholesale cotton fabric",
    "jeans",
    "denim",
    "Denim twill prepared for wholesale jean programs",
    "/collections/denim/",
    "/fabrics/best-for/trousers/",
    "Wholesale denim fabric is mill denim in jean or shirting ounces, with stretch called out if present.",
    "Record ounce or GSM, stretch, and finish. Dry and washed denim sew differently.",
    "Wash a sample if the jean will be washed.",
    "Shirt denim and jean denim must not share one mass line.",
    "Jeans, jackets, and denim shirts.",
    "A known mill category with clear visual identity.",
    "Crocking and twist if tests are skipped.",
    "Finish chemistry changes care.",
    "Measure shrinkage and skew after wash.",
    "Weight band should match season and silhouette.",
    "Ordering one denim for shirts and jeans.",
    "Mass, stretch, finish, width, and wash tests.",
  ),
  r(
    64,
    "wholesale silk fabric",
    "wholesale-type",
    "wholesale silk",
    "/discover/silk/",
    "satin fabric",
    "wholesale satin fabric",
    "dresses",
    "silk",
    "Silk satin used in wholesale silk conversations",
    "",
    "/fabrics/best-for/dresses/",
    "Wholesale silk fabric is silk cloth in mill units. Weave still matters: satin, chiffon, crepe, and dupion are different.",
    "Name weave, momme or GSM if published, and whether the silk is degummed and finished.",
    "Hand is specific. Do not approve polyester satin as a silk stand-in without a new brief.",
    "Momme bands differ for chiffon, crepe, and duchesse.",
    "Dresses, blouses, linings, and scarves.",
    "Lustre and drape when the weave matches.",
    "Price pressure that quietly substitutes polyester.",
    "Many silks need gentle or specialist care.",
    "Sample the weave you will cut. Check colour in daylight.",
    "Light silks appear in warm-weather eveningwear. Heavier silks appear in cooler occasionwear.",
    "Buying wholesale silk as a single GSM.",
    "Weave, mass, width, MOQ, and care.",
  ),
  r(
    65,
    "wholesale polyester fabric",
    "wholesale-type",
    "wholesale polyester",
    "/discover/polyester/",
    "recycled polyester fabric",
    "wholesale satin fabric",
    "sportswear",
    "polyester",
    "Polyester ripstop used in wholesale polyester programs",
    "",
    "/fabrics/best-for/activewear/",
    "Wholesale polyester fabric is polyester cloth in mill units. Knit, woven, coated, and recycled programs are different buys.",
    "Name construction, denier or GSM, and any coating or recycled claim with evidence.",
    "Hand ranges from fluid satin to crisp ripstop.",
    "Mass bands differ for lining, outer shell, and fleece.",
    "Sportswear, linings, outerwear, and fashion wovens.",
    "Colour, strength, and easy-care in many constructions.",
    "Heat shine, pilling, and low vapour movement in dense constructions.",
    "Heat can glaze polyester. Follow the mill line.",
    "Test pilling and heat on a sample.",
    "Climate comfort depends on construction, not the fibre word alone.",
    "Treating all wholesale polyester as one sports knit.",
    "Construction, mass, claims, width, and tests.",
  ),
  r(
    66,
    "wholesale satin fabric",
    "wholesale-type",
    "wholesale satin",
    "/discover/satin/",
    "satin fabric",
    "wholesale silk fabric",
    "dresses",
    "satin",
    "Silk satin prepared for wholesale satin cutting",
    "",
    "/fabrics/best-for/dresses/",
    "Wholesale satin fabric is satin-weave cloth in mill units. Fibre may be silk, polyester, or acetate.",
    "Name fibre first. Satin is a weave.",
    "Slippery. Marker and sewing plans must match.",
    "Charmeuse and duchesse do not share one mass line.",
    "Dresses, linings, and sleepwear.",
    "Lustre at mill width when lots match.",
    "Snag and seam slippage in bulk if tests are skipped.",
    "Heat shine is a bulk risk.",
    "Sew a sample seam. Check slippage.",
    "Used year-round for evening and lining.",
    "Ordering polyester satin against a silk satin tech pack without a change note.",
    "Fibre, weave, mass, width, and MOQ.",
  ),
  r(
    67,
    "wholesale velvet fabric",
    "wholesale-type",
    "wholesale velvet",
    "/discover/velvet/",
    "velvet fabric",
    "wholesale satin fabric",
    "dresses",
    "velvet",
    "Crushed velvet prepared for wholesale velvet programs",
    "",
    "/fabrics/best-for/dresses/",
    "Wholesale velvet fabric is pile cloth in mill units. Pile direction must be locked in the marker.",
    "Name pile fibre, ground, pile height, and crush.",
    "Directional colour. Approve in the light you will sell in.",
    "Dress pile and furnishing pile are different masses.",
    "Dresses, jackets, and some interiors.",
    "A clear evening or winter face.",
    "Crush in packing and seating.",
    "Specialist care is common.",
    "Cut a trial panel with pile arrows.",
    "Heavier velvets sit in cooler deliveries.",
    "Mixing apparel and furnishing velvet on one PO.",
    "Pile, mass, width, MOQ, and packing notes.",
  ),
  r(
    68,
    "wholesale lace fabric",
    "wholesale-type",
    "wholesale lace",
    "/discover/lace/",
    "lace fabric",
    "wholesale chiffon fabric",
    "dresses",
    "lace",
    "Patterned lace-like cloth prepared for wholesale lace cutting",
    "",
    "/fabrics/best-for/dresses/",
    "Wholesale lace fabric is patterned open cloth in mill units. Repeat and scallop must be in the PO.",
    "Name motif scale, ground, fibre, and edge.",
    "Motif matching uses more cloth. Plan yield.",
    "Mass is usually light but corded lace can surprise.",
    "Dresses, overlays, and lingerie.",
    "Decorative face at mill width.",
    "Fragile grounds in bulk handling.",
    "Often specialist care.",
    "Lay a full repeat, not a postcard swatch.",
    "Occasion deliveries more than daily climate clothing.",
    "Ignoring scallop direction on a wholesale lace PO.",
    "Motif, edge, width, yield, and MOQ.",
  ),
  r(
    69,
    "wholesale chiffon fabric",
    "wholesale-type",
    "wholesale chiffon",
    "/discover/chiffon/",
    "chiffon fabric",
    "wholesale satin fabric",
    "dresses",
    "chiffon",
    "Silk chiffon prepared for wholesale chiffon programs",
    "",
    "/fabrics/best-for/dresses/",
    "Wholesale chiffon fabric is light sheer woven in mill units. Fibre must be named: silk or polyester.",
    "Record sheer level, fibre, and whether a lining cloth is sourced in the same colour.",
    "Airy and snag-prone. Handling in bulk needs discipline.",
    "Always light. Do not merge with satin mass lines.",
    "Overlays, dresses, and blouses.",
    "Sheer movement at mill width.",
    "Seam slippage and shade shift on pale lots.",
    "Heat can melt polyester chiffon.",
    "Sew a sample seam. Check opacity over lining.",
    "Warm-weather and evening overlays.",
    "Buying chiffon without a lining plan.",
    "Fibre, sheer, width, lining, and MOQ.",
  ),
  r(
    70,
    "wholesale knit fabric",
    "wholesale-type",
    "wholesale knit",
    "/guides/woven-vs-knit-fabrics/",
    "knit fabric",
    "wholesale cotton fabric",
    "t-shirts",
    "knit",
    "Cotton jersey prepared for wholesale knit programs",
    "",
    "/fabrics/best-for/knitwear/",
    "Wholesale knit fabric is looped cloth in mill units. Gauge, fibre, and finish define the SKU.",
    "Name knit type. Jersey, rib, interlock, and fleece are different wholesale lines.",
    "Stretch and recovery must be approved on body, not only on a roll.",
    "Fine jersey and fleece cannot share one mass line.",
    "T-shirts, dresses, and loungewear.",
    "Comfort programs at mill width.",
    "Growth and torque if tests are skipped.",
    "Heat can shrink some knits.",
    "Wash and measure a sample tube or panel.",
    "Light knits for warm weather. Brushed knits for cooler weather.",
    "Ordering wholesale knit as if it were one jersey.",
    "Knit type, mass, stretch, width, and wash tests.",
  ),
  r(
    71,
    "fabric for clothing",
    "application",
    "clothing fabric",
    "/guides/",
    "clothing fabric",
    "fashion fabric",
    "apparel",
    "cotton",
    "Cotton poplin used as a general clothing fabric example",
    "",
    "/fabrics/best-for/shirts/",
    "Fabric for clothing is cloth chosen to become garments. End use still has to be named: shirt, coat, or knit dress.",
    "Write garment type, climate, care, and silhouette before you pick fibre.",
    "Clothing hand is judged on the body, not only on the table.",
    "Mass bands differ by garment. A coat mass can ruin a shirt.",
    "All apparel families, once specified.",
    "A wide field of mill options when the brief is clear.",
    "A generic clothing search with no garment type.",
    "Care must match how the wearer will wash the garment.",
    "Sample the actual garment type, not a random swatch.",
    "Season follows garment and mass.",
    "Buying one cloth for an entire collection.",
    "Garment type, mass band, fibre, and care.",
  ),
  r(
    72,
    "fabric for dresses",
    "application",
    "dress fabric",
    "/fabrics/best-for/dresses/",
    "dress fabric",
    "fabric for skirts",
    "dresses",
    "satin",
    "Fluid satin used as a dress fabric example",
    "",
    "/fabrics/best-for/dresses/",
    "Fabric for dresses needs drape, opacity, and seam behaviour that match the silhouette.",
    "Name silhouette: shirt dress, slip, or structured. Then pick fibre and construction.",
    "Fluid cloths hang. Crisp cloths stand. Do not mix those goals.",
    "Light crepes and chiffons sit far from coating masses.",
    "Day dresses, evening dresses, and knit dresses are different specs.",
    "A clear silhouette when cloth and pattern agree.",
    "Show-through and cling if opacity and stretch are ignored.",
    "Care should match a wearable dress, not only a sample swatch.",
    "Muslin or toile in a similar drape, then the fashion cloth.",
    "Light open cloths for warm weather. Lined or heavier cloths for cooler weather.",
    "Using suiting canvas for a bias slip.",
    "Silhouette, drape, opacity, mass, and lining.",
  ),
  r(
    73,
    "fabric for shirts",
    "application",
    "shirt fabric",
    "/fabrics/best-for/shirts/",
    "shirt fabric",
    "fabric for clothing",
    "shirts",
    "cotton",
    "Cotton poplin used as a classic shirt fabric",
    "",
    "/fabrics/best-for/shirts/",
    "Fabric for shirts needs a stable woven or a planned knit, plus opacity at the chest and collar.",
    "Name woven vs knit, fibre, and whether the shirt is tailored or casual.",
    "Poplin feels crisp. Jersey feels mobile. Both can be shirts if the pattern matches.",
    "Shirt GSM is usually lighter than trouser GSM in the same fibre family.",
    "Dress shirts, casual shirts, and knit tees.",
    "A clean collar and placket when the cloth is stable enough.",
    "Show-through in pale poplins. Growth in unstable knits.",
    "Shirts are washed often. Care and colourfastness matter.",
    "Sew a collar sample. Check opacity and shrinkage.",
    "Light poplins and linens for warm weather. Flannel and heavier twills for cooler weather.",
    "Using dress-weight silk chiffon as an everyday work shirt.",
    "Construction, opacity, mass, and wash tests.",
  ),
  r(
    74,
    "fabric for pants",
    "application",
    "pants fabric",
    "/fabrics/best-for/trousers/",
    "fabric for skirts",
    "twill fabric",
    "trousers",
    "twill",
    "Cotton twill used as a trousers and pants fabric",
    "",
    "/fabrics/best-for/trousers/",
    "Fabric for pants needs abrasion resistance, opacity, and a mass that holds a crease or a casual fold, depending on the block.",
    "Name woven vs knit, stretch, and whether the pant is tailored, chino, or denim.",
    "Chino twill feels drier than viscose crepe. Both can make pants if the brief is honest.",
    "Trouser masses sit above most shirt masses.",
    "Chinos, denim, tailored trousers, and knit pants.",
    "Shape retention when recovery and mass match the block.",
    "Bagging at the knee if stretch recovery is weak.",
    "Pants are washed or cleaned often at stress points.",
    "Sit and walk in a sample pair or a sewn test panel.",
    "Lighter linens and viscose for warm weather. Wool and heavy twill for cooler weather.",
    "Using shirt poplin as the only pant cloth.",
    "Mass, stretch, abrasion, and opacity.",
  ),
  r(
    75,
    "fabric for skirts",
    "application",
    "skirt fabric",
    "/fabrics/best-for/dresses/",
    "fabric for dresses",
    "fabric for pants",
    "skirts",
    "twill",
    "Twill and fluid cloths used when planning skirt fabric",
    "",
    "/fabrics/best-for/dresses/",
    "Fabric for skirts follows silhouette: pencil, A-line, or bias. Drape and opacity change with that choice.",
    "Name length, lining, and whether the skirt must hold a crease.",
    "Stiff cloth stands. Fluid cloth moves. Pleats need a cloth that remembers a fold.",
    "Mass should match length. A long fluid skirt can still be light. A mini often needs more opacity.",
    "Work skirts, evening skirts, and denim skirts.",
    "A clean hang when grain and drape agree.",
    "Seat shine, cling, and show-through.",
    "Lining changes both care and comfort.",
    "Walk in a toile. Check seat and hem.",
    "Light cloths for warm weather. Lined wools and velvets for cooler weather.",
    "Using unlined chiffon for a desk-length work skirt without a lining plan.",
    "Silhouette, opacity, mass, and lining.",
  ),
  r(
    76,
    "fabric for bags",
    "application",
    "bag fabric",
    "/fabrics/best-for/bags/",
    "canvas fabric",
    "upholstery fabric",
    "bags",
    "canvas",
    "Tight canvas used as a bag fabric example",
    "",
    "/fabrics/best-for/bags/",
    "Fabric for bags needs tear strength, abrasion, and a structure that holds hardware.",
    "Name load, lining, coating, and whether the bag is fashion or work.",
    "Canvas and coated cloths feel firmer than apparel satins.",
    "Bag cloth is usually heavier than shirt cloth.",
    "Totes, backpacks, and small leather-goods textiles.",
    "Shape and durability when specs match load.",
    "Needle holes, coating crack, and colour rub on pale linings.",
    "Coatings change wipe-clean care.",
    "Sew a handle join. Pull it.",
    "Outdoor bags may need water resistance. City totes may not.",
    "Using dress chiffon as a load-bearing tote.",
    "Mass, coating, tear, and hardware plan.",
  ),
  r(
    77,
    "fabric for upholstery",
    "application",
    "upholstery",
    "/fabrics/best-for/upholstery/",
    "upholstery fabric",
    "sofa fabric",
    "sofas",
    "jacquard",
    "Furnishing jacquard used as an upholstery fabric example",
    "",
    "/fabrics/best-for/upholstery/",
    "Fabric for upholstery needs abrasion, colourfastness, and a hand that survives sitting.",
    "Ask for abrasion method if claimed, fibre, and whether the cloth is apparel leftover or a furnishing quality.",
    "Furnishing cloths feel drier and firmer than dress satins.",
    "Usually heavier than apparel dress cloth.",
    "Sofas, chairs, and some cushions.",
    "Longer wear when the quality is a furnishing spec.",
    "Pilling, seam slippage, and fading in sun.",
    "Cleaning codes belong on the cloth. Do not guess.",
    "Rub and fold a sample. Check seam allowance bulk.",
    "Indoor climate matters more than fashion season, but sun rooms still fade some dyes.",
    "Using apparel satin as sofa cloth without an abrasion check.",
    "Abrasion, fibre, mass, and cleaning code.",
  ),
  r(
    78,
    "upholstery fabric",
    "application",
    "upholstery fabric",
    "/fabrics/best-for/upholstery/",
    "fabric for upholstery",
    "sofa fabric",
    "sofas",
    "jacquard",
    "Heavy patterned woven used as upholstery fabric",
    "",
    "/fabrics/best-for/upholstery/",
    "Upholstery fabric is cloth specified for furniture, not a renamed dress fabric.",
    "Look for furnishing tests, not only a pretty face.",
    "Firmlier hand. Pile upholsteries crush under sit bones.",
    "Mass is usually high compared with shirts.",
    "Seating, screens, and some headboards.",
    "A furniture identity when tests exist.",
    "Apparel leftovers sold as upholstery.",
    "Follow the cleaning code.",
    "Request the test method name if abrasion is claimed. Do not invent a score.",
    "Sun and indoor heat matter more than fashion season.",
    "Skipping seam slippage tests on loosely woven upholstery.",
    "Test names, fibre, mass, and cleaning.",
  ),
  r(
    79,
    "curtain fabric",
    "application",
    "curtain fabric",
    "/fabrics/best-for/drapery/",
    "sheer fabric",
    "upholstery fabric",
    "windows",
    "linen",
    "Linen folds used as a curtain fabric example",
    "",
    "/fabrics/best-for/drapery/",
    "Curtain fabric is cloth for windows. Light control, drape, and fade sit in the brief.",
    "Name sheer vs blackout vs decorative, and whether a lining is separate.",
    "Soft folds need drape. Stiff blackouts need mass and coatings.",
    "Sheers are light. Blackouts can be heavy.",
    "Sheers, drapes, and lined curtains.",
    "Light control when the system includes lining and header.",
    "Fade, sag, and heat at windows.",
    "Some coatings cannot be washed. Follow the page.",
    "Hang a length if you can. A 10 cm swatch hides drape.",
    "South-facing sun is harsher on dye than a north window. This is practical, not a trend claim.",
    "Using unlined silk chiffon as a blackout curtain.",
    "Light control, lining, mass, and fade notes.",
  ),
  r(
    80,
    "sofa fabric",
    "application",
    "sofa fabric",
    "/fabrics/best-for/upholstery/",
    "upholstery fabric",
    "fabric for upholstery",
    "sofas",
    "velvet",
    "Velvet pile used as one sofa fabric family",
    "",
    "/fabrics/best-for/upholstery/",
    "Sofa fabric is upholstery chosen for seating. Rub, pets, and cleaning sit in the brief.",
    "Ask who sits, whether food happens on the sofa, and whether pile is acceptable.",
    "Tight wovens feel more practical than deep pile for daily sitters.",
    "Usually heavy.",
    "Family sofas, formal sofas, and outdoor sofas are different specs.",
    "Comfort and look when the family matches the room.",
    "Crush, claw pulls, and stain on pale pile.",
    "Cleaning code first. Do not invent washability.",
    "Sit on a large sample if the vendor allows.",
    "Indoor sofas still fade near windows.",
    "Choosing evening velvet for a family dog sofa without a second thought.",
    "Use case, pile, tests, and cleaning.",
  ),
];
