import type { SeedGroup } from "./types";
import type { SeedRow } from "./seeds";
import { IMG } from "./seeds";

function r(
  id: number,
  keyword: string,
  group: SeedGroup,
  topic: string,
  existingCanonical: string,
  peerKeyword: string,
  peer2Keyword: string,
  primaryUse: string,
  imageKey: keyof typeof IMG,
  imageAlt: string,
  collectionPath: string,
  bestForPath: string,
  definition: string,
  makeup: string,
  feel: string,
  weight: string,
  uses: string,
  strengths: string,
  limits: string,
  care: string,
  sampling: string,
  climate: string,
  mistake: string,
  specCheck: string,
): SeedRow {
  return [
    id,
    keyword,
    group,
    topic,
    existingCanonical,
    peerKeyword,
    peer2Keyword,
    primaryUse,
    imageKey,
    imageAlt,
    collectionPath,
    bestForPath,
    [
      definition,
      makeup,
      feel,
      weight,
      uses,
      strengths,
      limits,
      care,
      sampling,
      climate,
      mistake,
      specCheck,
    ],
  ];
}

export const SEED_ROWS_24_50: readonly SeedRow[] = [
  r(
    24,
    "breathable fabric",
    "property",
    "breathable",
    "/discover/breathable-fabric/",
    "moisture wicking fabric",
    "waterproof fabric",
    "sportswear",
    "breathable",
    "Open cotton voile that lets air move through a light weave",
    "",
    "/fabrics/best-for/activewear/",
    "Breathable fabric lets moisture vapour and air move more readily than a sealed cloth. It is a behaviour, not a fibre name.",
    "Ask how breathability is achieved: open weave, knit structure, membrane, or finish. Lab claims should be named if used.",
    "Open cloths often feel cooler. Coatings can feel clammy even if the fibre is cotton.",
    "Light open cloths usually feel more breathable than heavy coated cloths, but construction still rules.",
    "Shirts, sportswear, dresses, and any garment worn in heat or during movement.",
    "Comfort in heat when the structure actually moves vapour.",
    "A marketing word without a construction. Waterproof coatings often reduce breathability.",
    "Finishes can change breathability after wash. Recheck after care tests.",
    "Wear or steam a sample. A swatch in still air is a weak proof.",
    "Most relevant in warm weather and during exercise.",
    "Calling any cotton breathable regardless of coating, density, or lining.",
    "Construction, coatings, weight, and any published vapour test.",
  ),
  r(
    25,
    "stretch fabric",
    "property",
    "stretch",
    "/discover/stretch-fabric/",
    "knit fabric",
    "sportswear fabric",
    "activewear",
    "stretch",
    "Stretch woven with recovery used in compression-style apparel",
    "",
    "/fabrics/best-for/activewear/",
    "Stretch fabric extends under load. Elastane, knit structure, or both can create stretch.",
    "Record stretch direction, recovery, and elastane percentage if published.",
    "More mobile than a rigid woven. Poor recovery feels baggy after wear.",
    "Weight is independent of stretch. Light and heavy stretch cloths both exist.",
    "Activewear, denim, tailored stretch wovens, and close-fitting dresses.",
    "Ease of movement and closer fit when recovery is adequate.",
    "Growth, heat damage to elastane, and shade change on stretch.",
    "Heat and chlorine can damage elastane. Follow the care line.",
    "Stretch and release a sample. Check recovery after a few minutes.",
    "Used year-round. Climate comfort still follows fibre and density.",
    "Specifying stretch without saying two-way, four-way, or recovery.",
    "Stretch direction, recovery, fibre, weight, and care.",
  ),
  r(
    26,
    "waterproof fabric",
    "property",
    "waterproof",
    "/discover/waterproof/",
    "breathable fabric",
    "outdoor fabric",
    "outdoor clothing",
    "waterproof",
    "Tight ripstop used in weather-resistant outdoor programs",
    "",
    "/fabrics/best-for/outerwear/",
    "Waterproof fabric resists liquid water under the conditions the mill names. Water-resistant is a weaker claim.",
    "Ask whether the cloth is coated, laminated, or densely woven, and whether seams will be taped.",
    "Coatings can feel stiffer. Some laminates feel quieter and more flexible.",
    "Shell cloths vary. Do not guess millimetres of water column unless the page publishes a test.",
    "Outerwear, bags, and some workwear.",
    "Weather protection when the system includes seams and closures.",
    "Reduced breathability, noisy hand, and finish wear after wash.",
    "Some finishes decline after wash. Follow the mill aftercare.",
    "If a water test is claimed, ask how it was measured. A splash on a swatch is not a hydrostatic test.",
    "Most relevant in wet weather. Heat comfort depends on vapour movement.",
    "Calling a DWR finish waterproof without a published barrier.",
    "Barrier type, seams, weight, and any published water test.",
  ),
  r(
    27,
    "lightweight fabric",
    "property",
    "lightweight",
    "/discover/understanding-lightweight-fabric/",
    "heavy fabric",
    "sheer fabric",
    "shirts",
    "lightweight",
    "Fine cotton voile representing a light apparel weight band",
    "",
    "/fabrics/best-for/shirts/",
    "Lightweight fabric sits in a lower mass band for its use. GSM is mass per square metre. Lower GSM is usually lighter cloth.",
    "Always read published GSM or ounce with construction. Light denim and light chiffon are not interchangeable.",
    "Often more fluid and cooler than a heavy counterpart in the same fibre.",
    "The whole point of the label is mass. Still confirm the number on the page.",
    "Shirts, dresses, linings, and summer layers.",
    "Less bulk and often easier drape.",
    "Show-through, weaker seams, and a cheap look if the yarn is poor.",
    "Light cloths can still shrink. Care follows fibre.",
    "Hold to light. Check opacity and seam strength on a sample.",
    "Often chosen for warm weather, but evening chiffon is also light.",
    "Using one lightweight number across shirts, denim, and coating.",
    "Published mass, construction, opacity, and width.",
  ),
  r(
    28,
    "heavy fabric",
    "property",
    "heavy",
    "/discover/heavy-fabric/",
    "lightweight fabric",
    "canvas fabric",
    "coats",
    "heavy",
    "Dense hemp canvas representing a heavier woven mass",
    "",
    "/fabrics/best-for/outerwear/",
    "Heavy fabric sits in a higher mass band for its use. Higher GSM usually means more mass per square metre.",
    "Read the published mass with the end use. Heavy shirting is still lighter than coating.",
    "Often firmer, warmer, and more opaque.",
    "Mass is the defining spec. Confirm it. Do not guess.",
    "Coats, trousers, workwear, bags, and upholstery.",
    "Durability and cover when construction is sound.",
    "Bulk, heat, and difficult sewing if needles and seams are wrong.",
    "Heavy cloths can still have finishes that need gentle care.",
    "Sew a sample seam. Check bulk, needle marks, and drape.",
    "Often used in cool weather and for load-bearing goods.",
    "Calling any dark cloth heavy without a mass number.",
    "Published mass, construction, end use, and seam plan.",
  ),
  r(
    29,
    "soft fabric",
    "property",
    "soft",
    "/discover/soft-fabric/",
    "textured fabric",
    "flannel fabric",
    "clothing",
    "soft",
    "Brushed flannel with a raised, soft nap",
    "",
    "/fabrics/best-for/loungewear/",
    "Soft fabric is a hand description. Brushing, fibre, yarn, and finish all change softness.",
    "Ask what creates the hand: fibre, enzyme, silicone, or nap. Softness can wash off.",
    "Pleasant next to skin when the finish is stable.",
    "Softness is not a GSM. Light and heavy cloths can both feel soft.",
    "Next-to-skin apparel, baby programs, loungewear, and dresses.",
    "Comfort and a perceived quality lift when the hand lasts.",
    "Pilling on brushed faces. Some silicone finishes feel greasy or wash out.",
    "Wash a sample. Judge hand after care, not only in the showroom.",
    "Rub and wash. Check pilling and whether softness remains.",
    "Brushed softness can feel warmer. Open soft knits can still feel cool.",
    "Buying on the word soft without a construction or wash test.",
    "Fibre, finish, construction, and wash-hand notes.",
  ),
  r(
    30,
    "sheer fabric",
    "property",
    "sheer",
    "/discover/sheer-fabric/",
    "chiffon fabric",
    "lightweight fabric",
    "dresses",
    "sheer",
    "Sheer silk chiffon showing light through an open weave",
    "",
    "/fabrics/best-for/dresses/",
    "Sheer fabric lets light and skin show through. Opacity is a design choice, not a defect, when planned.",
    "Record opacity, fibre, and lining plan. Sheer is not the same as lightweight opaque.",
    "Airy. Some sheers feel crisp (organza). Others feel fluid (chiffon).",
    "Usually light, but a heavy lace can still be sheer in the ground.",
    "Overlays, eveningwear, blouses, and lingerie.",
    "Layering and light without adding bulk.",
    "Modesty, lining cost, and snagging.",
    "Gentle care. Heat can melt some synthetic sheers.",
    "Hold over skin in daylight. Check lining needs.",
    "Common in warm-weather and evening programs.",
    "Skipping lining when the brief needs cover.",
    "Opacity, fibre, weight, and lining plan.",
  ),
  r(
    31,
    "textured fabric",
    "property",
    "textured",
    "/discover/textured-fabric/",
    "soft fabric",
    "corduroy fabric",
    "upholstery",
    "textured",
    "Fine-wale corduroy ridges as an example of surface texture",
    "",
    "/fabrics/best-for/upholstery/",
    "Textured fabric has a surface you can see or feel: ribs, slubs, crepe, pile, or seersucker.",
    "Name the texture type. Texture from yarn, weave, and finish behave differently in wash.",
    "More grip and visual depth than a flat poplin.",
    "Texture is not mass. Light crepes and heavy cords both count as textured.",
    "Jackets, trousers, dresses, and upholstery.",
    "Visual interest without print.",
    "Crush, dirt in recesses, and abrasion on high points.",
    "Some textures flatten with heat and pressure.",
    "Crush and steam a sample. Check whether texture returns.",
    "Pile textures often read as cooler-weather. Seersucker reads as warm-weather.",
    "Calling every uneven cloth slubbed without naming the construction.",
    "Texture type, fibre, weight, and crush recovery.",
  ),
  r(
    32,
    "mesh fabric",
    "property",
    "mesh",
    "/discover/mesh-fabric/",
    "net fabric",
    "breathable fabric",
    "activewear",
    "mesh",
    "Open technical mesh-like stretch cloth used for ventilation",
    "",
    "/fabrics/best-for/activewear/",
    "Mesh is an open structure with holes. Apparel mesh is often knitted for sports ventilation.",
    "Name hole size, fibre, stretch, and whether it is lining mesh or outer mesh.",
    "Airy. Power mesh feels firmer than dress net.",
    "Usually light. Power mesh can still feel strong.",
    "Activewear, lining, bags, and ventilation panels.",
    "Airflow and lower mass.",
    "Show-through, snagging, and poor opacity.",
    "Heat can distort some synthetic meshes.",
    "Stretch and look through a sample. Check hole size against the use.",
    "Common in sports and warm-weather ventilation.",
    "Using dress net as a sports mesh, or the reverse.",
    "Hole size, fibre, stretch, weight, and use.",
  ),
  r(
    33,
    "canvas fabric",
    "construction",
    "canvas",
    "/discover/canvas/",
    "denim fabric",
    "heavy fabric",
    "bags",
    "canvas",
    "Wool-hemp canvas with a tight, durable plain weave",
    "",
    "/fabrics/best-for/bags/",
    "Canvas is a tight, usually plain-woven cloth made for strength. Fibre is often cotton, hemp, or blends.",
    "Name fibre, weight, weave, and whether it is apparel or bag canvas.",
    "Firm and dry. Coatings make it stiffer and sometimes more water resistant.",
    "Usually mid to heavy. Shirt canvas is not bag canvas.",
    "Bags, workwear, sneakers, and some trousers.",
    "Strength and a workwear identity.",
    "Bulk, stiffness, and needle damage if the spec is too heavy for apparel.",
    "Coatings change care. Follow the page.",
    "Sew a sample. Check needle marks and stiffness at folds.",
    "Heavier canvases read as work and cooler weather. Lighter canvases appear in warm-weather trousers.",
    "Using bag canvas in a shirt block.",
    "Fibre, weave, weight, coating, and end use.",
  ),
  r(
    34,
    "fleece fabric",
    "construction",
    "fleece",
    "/discover/fleece/",
    "terry fabric",
    "knit fabric",
    "hoodies",
    "fleece",
    "Pima cotton fleece with a raised, insulating knit face",
    "",
    "/fabrics/best-for/loungewear/",
    "Fleece is a knit with a raised surface that traps air. It is not the same as woven wool coating.",
    "Name fibre, face, back, and whether it is microfleece, sherpa, or French terry related.",
    "Soft and insulating. Pilling is a common risk on the face.",
    "Usually mid to heavy compared with jersey.",
    "Hoodies, midlayers, and loungewear.",
    "Warmth at relatively low stiffness.",
    "Pilling, static, and heat if the fibre is polyester in exercise.",
    "Wash inside out when the mill allows. Heat can worsen pills.",
    "Rub a sample. Check pilling and stretch recovery.",
    "Chosen for cool weather. Not a summer shirting.",
    "Confusing fleece, terry, and wool coating.",
    "Fibre, pile, weight, and pilling notes.",
  ),
  r(
    35,
    "jersey fabric",
    "construction",
    "jersey",
    "/discover/jersey/",
    "knit fabric",
    "stretch fabric",
    "t-shirts",
    "jersey",
    "Mercerized cotton jersey with even knit loops",
    "",
    "/fabrics/best-for/knitwear/",
    "Jersey is a single-knit cloth with a smooth face and a different reverse. It is one knit family, not all knits.",
    "Name fibre, gauge, and whether it is single jersey, slub, or viscose jersey.",
    "Soft and mobile. Edges often curl.",
    "Fine jersey is light. Heavy jersey exists for dresses and winter tees.",
    "T-shirts, dresses, and underwear.",
    "Comfort and a familiar factory base.",
    "Growth, show-through, and curling hems.",
    "Lower heat helps many jerseys keep size.",
    "Stretch on the body. Check cover and recovery.",
    "Light jersey for warm weather. Heavy jersey for cooler tees.",
    "Using jersey as a synonym for every knit.",
    "Fibre, gauge, weight, and recovery.",
  ),
  r(
    36,
    "terry fabric",
    "construction",
    "terry",
    "/discover/terry-fabric/",
    "fleece fabric",
    "knit fabric",
    "loungewear",
    "terry",
    "Looped terry-like knit surface used for towels and loungewear",
    "",
    "/fabrics/best-for/loungewear/",
    "Terry has loops that absorb water. French terry has loops on one side and a smoother face.",
    "Name loop type, fibre, and whether it is towel terry or apparel French terry.",
    "Soft and thirsty. Loops can snag.",
    "Usually mid-weight or heavier than jersey.",
    "Loungewear, towels, baby cloth, and some sports.",
    "Absorbency and a casual identity.",
    "Bulk, longer dry time, and loop pull.",
    "Loops can distort in hot dryers.",
    "Wet a sample. Check absorbency and loop security.",
    "Worn in many climates as loungewear. Not a dress shirting.",
    "Calling French terry and towel terry the same cloth.",
    "Loop type, fibre, weight, and absorbency.",
  ),
  r(
    37,
    "corduroy fabric",
    "construction",
    "corduroy",
    "/discover/corduroy/",
    "velvet fabric",
    "textured fabric",
    "trousers",
    "corduroy",
    "Fine-wale corduroy ridges running along the cloth",
    "",
    "/fabrics/best-for/trousers/",
    "Corduroy is a piled woven with wales (ridges). Wale count changes the look.",
    "Name fibre, wale count, and whether it is needlecord or wide wale.",
    "Soft pile with directional colour, similar in that way to velvet.",
    "Usually mid-weight. Needlecord can be lighter than wide wale.",
    "Trousers, jackets, and dresses.",
    "Texture and a cool-weather identity.",
    "Pile crush, dirt in wales, and seam bulk.",
    "Steam and pressure can crush wales.",
    "Check wale direction on a sample panel.",
    "Often chosen for cooler weather.",
    "Ignoring wale direction in the marker.",
    "Fibre, wale count, weight, and pile care.",
  ),
  r(
    38,
    "flannel fabric",
    "construction",
    "flannel",
    "/discover/flannel/",
    "soft fabric",
    "wool fabric",
    "shirts",
    "flannel",
    "Brushed flannel with a raised, matte nap",
    "",
    "/fabrics/best-for/shirts/",
    "Flannel is a slightly napped cloth, often cotton or wool, made for a soft, matte hand.",
    "Name fibre, nap, and whether it is shirting or coating flannel.",
    "Soft and dull. Wool flannel feels springier than cotton flannel.",
    "Shirting flannel is mid-light to mid. Coating flannel is heavier.",
    "Shirts, trousers, and some jackets.",
    "Soft hand and a cool-weather look.",
    "Pilling and a dusty look if nap is weak.",
    "Brushing can change after wash.",
    "Wash a shirted sample. Check nap and shrinkage.",
    "Common in cool weather. Light cotton flannel still appears in mild seasons.",
    "Treating wool flannel and cotton flannel as one spec.",
    "Fibre, nap, weight, and care.",
  ),
  r(
    39,
    "twill fabric",
    "construction",
    "twill",
    "/discover/understanding-twill-fabric/",
    "denim fabric",
    "canvas fabric",
    "trousers",
    "twill",
    "Egyptian cotton twill with a diagonal weave line",
    "",
    "/fabrics/best-for/trousers/",
    "Twill is a weave with a diagonal line. Denim is often a twill, but not every twill is denim.",
    "Name fibre, twill direction, and weight. Chino, gabardine, and denim are different twills.",
    "Usually more drape than a tight plain canvas of similar mass.",
    "Chinos sit mid. Coat gabardine can be heavier. Shirt twills can be light.",
    "Trousers, chinos, jackets, and some shirts.",
    "Drape and hiding of soil compared with some plain weaves.",
    "Skew after wash on some denims and twills.",
    "Follow fibre care. Finish still matters.",
    "Wash a sample if the garment will be washed. Check skew and hand.",
    "Used in all seasons depending on fibre and mass.",
    "Using twill, denim, and chino as identical words.",
    "Fibre, twill type, weight, and finish.",
  ),
  r(
    40,
    "crepe fabric",
    "construction",
    "crepe",
    "/discover/crepe/",
    "satin fabric",
    "chiffon fabric",
    "dresses",
    "crepe",
    "Crêpe-like georgette with a dry, pebbled surface",
    "",
    "/fabrics/best-for/dresses/",
    "Crepe has a pebbled, dry surface from high-twist yarns, a crepe weave, or a finish.",
    "Name fibre and crepe type: georgette, crepe de chine, or wool crepe.",
    "Dry and often matte. It hangs with more texture than satin.",
    "Dress crepes are often light. Wool crepe suiting sits heavier.",
    "Dresses, blouses, and some suiting.",
    "Matte drape and less shine than satin.",
    "Snagging of high-twist yarns and shrinkage.",
    "Steam can relax some crepes. Test first.",
    "Drape a sample. Check pebble and stretch.",
    "Used year-round. Light crepes appear in warm-weather dresses.",
    "Calling every matte cloth crepe.",
    "Fibre, crepe type, weight, and drape.",
  ),
  r(
    41,
    "fabric wholesale",
    "commercial",
    "fabric wholesale",
    "/wholesale-fabric/",
    "wholesale fabric",
    "fabric marketplace",
    "bulk apparel",
    "wholesale",
    "Cotton poplin folds representing mill cloth sold in wholesale units",
    "/wholesale-fabric/",
    "",
    "Fabric wholesale means buying mill cloth in mill units, often rolls, with MOQ and sampling rules.",
    "A wholesale brief still needs fibre, construction, weight, width, colour, and MOQ.",
    "Hand is judged on a production-like sample, not only a photo.",
    "Wholesale does not change GSM. Mass still lives on the fabric page.",
    "Apparel, home, and accessories programs that need repeating lots.",
    "Repeatable lots when quality systems exist.",
    "MOQ, colour continuity, and lead time still need written answers. Do not invent them here.",
    "Care remains a mill fact. Wholesale status does not change washing physics.",
    "Ask for a sample from the production dye lot when possible.",
    "Sourcing is global. FabStitch is used from the United States, United Kingdom, Turkey, Pakistan, India, Bangladesh, and Singapore.",
    "Treating wholesale as a fibre or a GSM.",
    "MOQ, sample policy, specs, and named cloth.",
  ),
  r(
    42,
    "wholesale fabric",
    "commercial",
    "wholesale fabric",
    "/wholesale-fabric/",
    "fabric wholesale",
    "buy fabric online",
    "bulk apparel",
    "wholesale",
    "Stacked mill-ready cotton cloth used in wholesale conversations",
    "/wholesale-fabric/",
    "",
    "Wholesale fabric is mill cloth offered for bulk programs rather than single-cut retail remnants.",
    "Confirm unit of sale, MOQ, and whether cutting is allowed. Photos are not a unit of sale.",
    "Judge hand on cloth, not on listing language.",
    "Mass still needs a published number or a sample scale.",
    "Brands, makers, and wholesalers building repeating styles.",
    "Access to mill units when the listing is complete.",
    "Incomplete listings that hide width, fibre, or MOQ.",
    "Care is still on the fabric page.",
    "Request a sample before a first bulk lot.",
    "Buyers in FabStitch’s seven target markets still need the same spec discipline.",
    "Using wholesale fabric as a synonym for cheap cloth.",
    "Unit of sale, MOQ, specs, and sample path.",
  ),
  r(
    43,
    "fabric supplier",
    "commercial",
    "fabric supplier",
    "/fabric-sourcing/",
    "fabric suppliers",
    "textile supplier",
    "apparel programs",
    "wholesale",
    "Mill cotton cloth used when evaluating a fabric supplier",
    "/fabric-sourcing/",
    "",
    "A fabric supplier sells cloth. Some mill. Some trade. The listing should make the role clear.",
    "Ask who holds inventory, who dyes, and who can re-order the same quality.",
    "A supplier cannot be felt. The cloth can. Sample it.",
    "Supplier identity does not replace GSM.",
    "Any program that needs repeating cloth.",
    "A path to mill cloth when communication is clear.",
    "Unclear origin, missing test data, and changing lots.",
    "Care is a cloth fact, not a supplier slogan.",
    "Sample first. Compare dye lots if the program will repeat.",
    "Suppliers may sit in many countries. Do not invent factory counts.",
    "Choosing a supplier name instead of a written spec.",
    "Role, spec pack, sample, and reorder path.",
  ),
  r(
    44,
    "fabric suppliers",
    "commercial",
    "fabric suppliers",
    "/fabric-sourcing/",
    "fabric supplier",
    "textile suppliers",
    "apparel programs",
    "wholesale",
    "Multiple mill cloth options laid out for supplier comparison",
    "/fabric-sourcing/",
    "",
    "Fabric suppliers is the plural search. The work is still comparing named cloths, not collecting logos.",
    "Compare spec packs side by side: fibre, construction, tests, MOQ, and sample rules.",
    "Hands differ. Rank cloth, then communication quality.",
    "Each option still needs its own mass number.",
    "Sourcing shortlists for brands and product teams.",
    "Choice, if listings are complete enough to compare.",
    "Too many incomplete options. A shortlist of three complete packs is more useful than twenty photos.",
    "Care lines should be compared, not assumed identical.",
    "Sample the shortlist in the same light.",
    "Shortlists may include mills in more than one of FabStitch’s target markets.",
    "Picking the longest catalogue instead of the fittest spec.",
    "Side-by-side specs, samples, and reorder proof.",
  ),
  r(
    45,
    "fabric sourcing",
    "sourcing",
    "fabric sourcing",
    "/fabric-sourcing/",
    "textile sourcing",
    "fabric sourcing company",
    "apparel programs",
    "wholesale",
    "Cotton poplin used as a working example in fabric sourcing briefs",
    "/fabric-sourcing/",
    "",
    "Fabric sourcing is the process of finding, sampling, and buying cloth that matches a written brief.",
    "A sourcing brief names end use, fibre, construction, mass, width, colour, tests, and quantity.",
    "Sourcing is judged by the cloth that arrives, not by the search phrase.",
    "Mass belongs in the brief as a band, not a guess.",
    "Apparel, home, and accessories development.",
    "Fewer failed samples when the brief is written first.",
    "Searching without a brief. That creates random cloth.",
    "Care and testing sit inside sourcing, not after it.",
    "Sample against the brief. Reject politely when the spec misses.",
    "Teams in the United States, United Kingdom, Turkey, Pakistan, India, Bangladesh, and Singapore still write the same kind of brief.",
    "Starting sourcing from a trend word instead of an end use.",
    "Brief, sample, tests, MOQ, and named mill cloth.",
  ),
  r(
    46,
    "textile supplier",
    "commercial",
    "textile supplier",
    "/fabric-sourcing/",
    "fabric supplier",
    "textile manufacturer",
    "textile programs",
    "wholesale",
    "Technical ripstop representing industrial textile supply conversations",
    "/fabric-sourcing/",
    "",
    "A textile supplier may sell fibre, yarn, or cloth. Confirm which layer you are buying.",
    "Name the product: greige, finished fabric, or yarn. Mixed catalogues need filters.",
    "Yarn hand is not fabric hand. Sample the form you will cut.",
    "GSM applies to cloth, not to a yarn cone.",
    "Mills, brands, and converters.",
    "Access to the right layer of the chain.",
    "Buying yarn language when you needed finished cloth.",
    "Care applies once you have cloth.",
    "Sample the finished quality you will sew.",
    "Textile trade sits across FabStitch’s target markets. Do not invent capacities.",
    "Using textile supplier as a vague synonym for any mill.",
    "Product layer, spec, sample, and reorder.",
  ),
  r(
    47,
    "textile suppliers",
    "commercial",
    "textile suppliers",
    "/fabric-sourcing/",
    "textile supplier",
    "fabric suppliers",
    "textile programs",
    "wholesale",
    "Several textile qualities compared during supplier shortlisting",
    "/fabric-sourcing/",
    "",
    "Textile suppliers as a search is a shortlist problem. Compare product layer and proof, not adjectives.",
    "Build a table: who sells yarn, who sells greige, who sells finished cloth.",
    "Rank by sample quality against the brief.",
    "Each finished cloth still needs mass data.",
    "Sourcing teams building a vendor map.",
    "A map of who does what.",
    "Duplicate trading names with no mill identity.",
    "Care lines should be requested with finished cloth.",
    "Sample two or three, not twenty, once the table is clean.",
    "Vendor maps may span several countries. Keep facts on the listing.",
    "Confusing a trader list with a mill list.",
    "Layer, identity, spec, and sample.",
  ),
  r(
    48,
    "wholesale textile",
    "commercial",
    "wholesale textile",
    "/wholesale-fabric/",
    "textile wholesale",
    "wholesale fabric",
    "bulk programs",
    "wholesale",
    "Mill-ready cloth representing wholesale textile units",
    "/wholesale-fabric/",
    "",
    "Wholesale textile means bulk units of fibre, yarn, or cloth. Confirm the unit.",
    "MOQ, packing, and width (for cloth) belong on the offer.",
    "Hand tests apply to the form you will process next.",
    "For cloth, still read GSM.",
    "Converters and brands buying repeating lots.",
    "Mill units instead of remnant cuts.",
    "Unclear whether the offer is yarn or fabric.",
    "Care is for finished cloth.",
    "Sample the production quality.",
    "Wholesale textile trade is international. Do not invent lead times.",
    "Using wholesale textile as a style name.",
    "Unit, MOQ, spec, and sample.",
  ),
  r(
    49,
    "textile wholesale",
    "commercial",
    "textile wholesale",
    "/wholesale-fabric/",
    "wholesale textile",
    "fabric wholesale",
    "bulk programs",
    "wholesale",
    "Folded mill cloth used in textile wholesale planning",
    "/wholesale-fabric/",
    "",
    "Textile wholesale is the same commercial intent as buying mill goods in bulk, with a textile-industry wording.",
    "Write the product layer first, then quantity, then tests.",
    "Photos of mills are not a hand-feel.",
    "Mass numbers still belong on cloth offers.",
    "Repeating production programs.",
    "Clear lots when documentation exists.",
    "Keyword-only listings with no width or fibre.",
    "Care remains a mill instruction.",
    "Align sample and bulk dye process before the first lot.",
    "Buyers across FabStitch markets still need documents, not slogans.",
    "Treating textile wholesale as a different fibre from fabric wholesale.",
    "Layer, quantity, tests, and documents.",
  ),
  r(
    50,
    "fabric manufacturer",
    "commercial",
    "fabric manufacturer",
    "/fabric-sourcing/",
    "fabric manufacturers",
    "textile manufacturer",
    "mill programs",
    "wholesale",
    "Woven cotton used when discussing a fabric manufacturer",
    "/fabric-sourcing/",
    "",
    "A fabric manufacturer weaves, knits, or finishes cloth. Traders may still appear in search results. Confirm the role.",
    "Ask what the mill actually does: weaving, knitting, dyeing, coating, or all of these.",
    "Mill visits and samples beat a logo.",
    "Manufacturer identity does not replace mass specs.",
    "Brands that need mill-direct programs.",
    "Shorter questions when the mill owns the process.",
    "A manufacturer name with no process map.",
    "Finishing still sets care.",
    "Sample from the mill’s finishing line when possible.",
    "Mills exist in many countries. Do not invent a factory list here.",
    "Assuming every manufacturer can dye every fibre.",
    "Process map, spec, sample, and capacity questions asked in writing.",
  ),
];
